/*******************************************************************************
* Filename      : hrtimtimcregisters.hpp
*
* Details       : High Resolution Timer: TIMC. This header file is
*                 auto-generated for STM32H745_CM7 device.
*
*
*******************************************************************************/

#if !defined(HRTIMTIMCREGISTERS_HPP)
#define HRTIMTIMCREGISTERS_HPP

#include "hrtimtimcfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct HRTIM_TIMC
{
  struct HRTIM_TIMCTIMCCRBase {} ;

  struct TIMCCR : public RegisterBase<0x40017580, 32, ReadWriteMode>
  {
    using UPDGAT = HRTIM_TIMC_TIMCCR_UPDGAT_Values<HRTIM_TIMC::TIMCCR, 28, 4, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using PREEN = HRTIM_TIMC_TIMCCR_PREEN_Values<HRTIM_TIMC::TIMCCR, 27, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using DACSYNC = HRTIM_TIMC_TIMCCR_DACSYNC_Values<HRTIM_TIMC::TIMCCR, 25, 2, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using MSTU = HRTIM_TIMC_TIMCCR_MSTU_Values<HRTIM_TIMC::TIMCCR, 24, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TEU = HRTIM_TIMC_TIMCCR_TEU_Values<HRTIM_TIMC::TIMCCR, 23, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TDU = HRTIM_TIMC_TIMCCR_TDU_Values<HRTIM_TIMC::TIMCCR, 22, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TCU = HRTIM_TIMC_TIMCCR_TCU_Values<HRTIM_TIMC::TIMCCR, 21, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TBU = HRTIM_TIMC_TIMCCR_TBU_Values<HRTIM_TIMC::TIMCCR, 20, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TxRSTU = HRTIM_TIMC_TIMCCR_TxRSTU_Values<HRTIM_TIMC::TIMCCR, 18, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using TxREPU = HRTIM_TIMC_TIMCCR_TxREPU_Values<HRTIM_TIMC::TIMCCR, 17, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using DELCMP4 = HRTIM_TIMC_TIMCCR_DELCMP4_Values<HRTIM_TIMC::TIMCCR, 14, 2, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using DELCMP2 = HRTIM_TIMC_TIMCCR_DELCMP2_Values<HRTIM_TIMC::TIMCCR, 12, 2, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using SYNCSTRTx = HRTIM_TIMC_TIMCCR_SYNCSTRTx_Values<HRTIM_TIMC::TIMCCR, 11, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using SYNCRSTx = HRTIM_TIMC_TIMCCR_SYNCRSTx_Values<HRTIM_TIMC::TIMCCR, 10, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using PSHPLL = HRTIM_TIMC_TIMCCR_PSHPLL_Values<HRTIM_TIMC::TIMCCR, 6, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using HALF = HRTIM_TIMC_TIMCCR_HALF_Values<HRTIM_TIMC::TIMCCR, 5, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using RETRIG = HRTIM_TIMC_TIMCCR_RETRIG_Values<HRTIM_TIMC::TIMCCR, 4, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using CONT = HRTIM_TIMC_TIMCCR_CONT_Values<HRTIM_TIMC::TIMCCR, 3, 1, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using CK_PSCx = HRTIM_TIMC_TIMCCR_CK_PSCx_Values<HRTIM_TIMC::TIMCCR, 0, 3, ReadWriteMode, HRTIM_TIMCTIMCCRBase> ;
    using FieldValues = HRTIM_TIMC_TIMCCR_CK_PSCx_Values<HRTIM_TIMC::TIMCCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMCCRPack  = Register<0x40017580, 32, ReadWriteMode, HRTIM_TIMCTIMCCRBase, T...> ;

  struct HRTIM_TIMCTIMCISRBase {} ;

  struct TIMCISR : public RegisterBase<0x40017584, 32, ReadMode>
  {
    using O2STAT = HRTIM_TIMC_TIMCISR_O2STAT_Values<HRTIM_TIMC::TIMCISR, 19, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using O1STAT = HRTIM_TIMC_TIMCISR_O1STAT_Values<HRTIM_TIMC::TIMCISR, 18, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using IPPSTAT = HRTIM_TIMC_TIMCISR_IPPSTAT_Values<HRTIM_TIMC::TIMCISR, 17, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CPPSTAT = HRTIM_TIMC_TIMCISR_CPPSTAT_Values<HRTIM_TIMC::TIMCISR, 16, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using DLYPRT = HRTIM_TIMC_TIMCISR_DLYPRT_Values<HRTIM_TIMC::TIMCISR, 14, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using RST = HRTIM_TIMC_TIMCISR_RST_Values<HRTIM_TIMC::TIMCISR, 13, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using RSTx2 = HRTIM_TIMC_TIMCISR_RSTx2_Values<HRTIM_TIMC::TIMCISR, 12, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using SETx2 = HRTIM_TIMC_TIMCISR_SETx2_Values<HRTIM_TIMC::TIMCISR, 11, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using RSTx1 = HRTIM_TIMC_TIMCISR_RSTx1_Values<HRTIM_TIMC::TIMCISR, 10, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using SETx1 = HRTIM_TIMC_TIMCISR_SETx1_Values<HRTIM_TIMC::TIMCISR, 9, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CPT2 = HRTIM_TIMC_TIMCISR_CPT2_Values<HRTIM_TIMC::TIMCISR, 8, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CPT1 = HRTIM_TIMC_TIMCISR_CPT1_Values<HRTIM_TIMC::TIMCISR, 7, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using UPD = HRTIM_TIMC_TIMCISR_UPD_Values<HRTIM_TIMC::TIMCISR, 6, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using REP = HRTIM_TIMC_TIMCISR_REP_Values<HRTIM_TIMC::TIMCISR, 4, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CMP4 = HRTIM_TIMC_TIMCISR_CMP4_Values<HRTIM_TIMC::TIMCISR, 3, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CMP3 = HRTIM_TIMC_TIMCISR_CMP3_Values<HRTIM_TIMC::TIMCISR, 2, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CMP2 = HRTIM_TIMC_TIMCISR_CMP2_Values<HRTIM_TIMC::TIMCISR, 1, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using CMP1 = HRTIM_TIMC_TIMCISR_CMP1_Values<HRTIM_TIMC::TIMCISR, 0, 1, ReadMode, HRTIM_TIMCTIMCISRBase> ;
    using FieldValues = HRTIM_TIMC_TIMCISR_CMP1_Values<HRTIM_TIMC::TIMCISR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMCISRPack  = Register<0x40017584, 32, ReadMode, HRTIM_TIMCTIMCISRBase, T...> ;

  struct HRTIM_TIMCTIMCICRBase {} ;

  struct TIMCICR : public RegisterBase<0x40017588, 32, WriteMode>
  {
    using DLYPRTC = HRTIM_TIMC_TIMCICR_DLYPRTC_Values<HRTIM_TIMC::TIMCICR, 14, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using RSTC = HRTIM_TIMC_TIMCICR_RSTC_Values<HRTIM_TIMC::TIMCICR, 13, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using RSTx2C = HRTIM_TIMC_TIMCICR_RSTx2C_Values<HRTIM_TIMC::TIMCICR, 12, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using SET2xC = HRTIM_TIMC_TIMCICR_SET2xC_Values<HRTIM_TIMC::TIMCICR, 11, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using RSTx1C = HRTIM_TIMC_TIMCICR_RSTx1C_Values<HRTIM_TIMC::TIMCICR, 10, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using SET1xC = HRTIM_TIMC_TIMCICR_SET1xC_Values<HRTIM_TIMC::TIMCICR, 9, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CPT2C = HRTIM_TIMC_TIMCICR_CPT2C_Values<HRTIM_TIMC::TIMCICR, 8, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CPT1C = HRTIM_TIMC_TIMCICR_CPT1C_Values<HRTIM_TIMC::TIMCICR, 7, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using UPDC = HRTIM_TIMC_TIMCICR_UPDC_Values<HRTIM_TIMC::TIMCICR, 6, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using REPC = HRTIM_TIMC_TIMCICR_REPC_Values<HRTIM_TIMC::TIMCICR, 4, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CMP4C = HRTIM_TIMC_TIMCICR_CMP4C_Values<HRTIM_TIMC::TIMCICR, 3, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CMP3C = HRTIM_TIMC_TIMCICR_CMP3C_Values<HRTIM_TIMC::TIMCICR, 2, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CMP2C = HRTIM_TIMC_TIMCICR_CMP2C_Values<HRTIM_TIMC::TIMCICR, 1, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using CMP1C = HRTIM_TIMC_TIMCICR_CMP1C_Values<HRTIM_TIMC::TIMCICR, 0, 1, WriteMode, HRTIM_TIMCTIMCICRBase> ;
    using FieldValues = HRTIM_TIMC_TIMCICR_CMP1C_Values<HRTIM_TIMC::TIMCICR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMCICRPack  = Register<0x40017588, 32, WriteMode, HRTIM_TIMCTIMCICRBase, T...> ;

  struct HRTIM_TIMCTIMCDIER5Base {} ;

  struct TIMCDIER5 : public RegisterBase<0x4001758C, 32, ReadWriteMode>
  {
    using DLYPRTDE = HRTIM_TIMC_TIMCDIER5_DLYPRTDE_Values<HRTIM_TIMC::TIMCDIER5, 30, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTDE = HRTIM_TIMC_TIMCDIER5_RSTDE_Values<HRTIM_TIMC::TIMCDIER5, 29, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTx2DE = HRTIM_TIMC_TIMCDIER5_RSTx2DE_Values<HRTIM_TIMC::TIMCDIER5, 28, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using SETx2DE = HRTIM_TIMC_TIMCDIER5_SETx2DE_Values<HRTIM_TIMC::TIMCDIER5, 27, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTx1DE = HRTIM_TIMC_TIMCDIER5_RSTx1DE_Values<HRTIM_TIMC::TIMCDIER5, 26, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using SET1xDE = HRTIM_TIMC_TIMCDIER5_SET1xDE_Values<HRTIM_TIMC::TIMCDIER5, 25, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CPT2DE = HRTIM_TIMC_TIMCDIER5_CPT2DE_Values<HRTIM_TIMC::TIMCDIER5, 24, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CPT1DE = HRTIM_TIMC_TIMCDIER5_CPT1DE_Values<HRTIM_TIMC::TIMCDIER5, 23, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using UPDDE = HRTIM_TIMC_TIMCDIER5_UPDDE_Values<HRTIM_TIMC::TIMCDIER5, 22, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using REPDE = HRTIM_TIMC_TIMCDIER5_REPDE_Values<HRTIM_TIMC::TIMCDIER5, 20, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP4DE = HRTIM_TIMC_TIMCDIER5_CMP4DE_Values<HRTIM_TIMC::TIMCDIER5, 19, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP3DE = HRTIM_TIMC_TIMCDIER5_CMP3DE_Values<HRTIM_TIMC::TIMCDIER5, 18, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP2DE = HRTIM_TIMC_TIMCDIER5_CMP2DE_Values<HRTIM_TIMC::TIMCDIER5, 17, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP1DE = HRTIM_TIMC_TIMCDIER5_CMP1DE_Values<HRTIM_TIMC::TIMCDIER5, 16, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using DLYPRTIE = HRTIM_TIMC_TIMCDIER5_DLYPRTIE_Values<HRTIM_TIMC::TIMCDIER5, 14, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTIE = HRTIM_TIMC_TIMCDIER5_RSTIE_Values<HRTIM_TIMC::TIMCDIER5, 13, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTx2IE = HRTIM_TIMC_TIMCDIER5_RSTx2IE_Values<HRTIM_TIMC::TIMCDIER5, 12, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using SETx2IE = HRTIM_TIMC_TIMCDIER5_SETx2IE_Values<HRTIM_TIMC::TIMCDIER5, 11, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using RSTx1IE = HRTIM_TIMC_TIMCDIER5_RSTx1IE_Values<HRTIM_TIMC::TIMCDIER5, 10, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using SET1xIE = HRTIM_TIMC_TIMCDIER5_SET1xIE_Values<HRTIM_TIMC::TIMCDIER5, 9, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CPT2IE = HRTIM_TIMC_TIMCDIER5_CPT2IE_Values<HRTIM_TIMC::TIMCDIER5, 8, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CPT1IE = HRTIM_TIMC_TIMCDIER5_CPT1IE_Values<HRTIM_TIMC::TIMCDIER5, 7, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using UPDIE = HRTIM_TIMC_TIMCDIER5_UPDIE_Values<HRTIM_TIMC::TIMCDIER5, 6, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using REPIE = HRTIM_TIMC_TIMCDIER5_REPIE_Values<HRTIM_TIMC::TIMCDIER5, 4, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP4IE = HRTIM_TIMC_TIMCDIER5_CMP4IE_Values<HRTIM_TIMC::TIMCDIER5, 3, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP3IE = HRTIM_TIMC_TIMCDIER5_CMP3IE_Values<HRTIM_TIMC::TIMCDIER5, 2, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP2IE = HRTIM_TIMC_TIMCDIER5_CMP2IE_Values<HRTIM_TIMC::TIMCDIER5, 1, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using CMP1IE = HRTIM_TIMC_TIMCDIER5_CMP1IE_Values<HRTIM_TIMC::TIMCDIER5, 0, 1, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base> ;
    using FieldValues = HRTIM_TIMC_TIMCDIER5_CMP1IE_Values<HRTIM_TIMC::TIMCDIER5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMCDIER5Pack  = Register<0x4001758C, 32, ReadWriteMode, HRTIM_TIMCTIMCDIER5Base, T...> ;

  struct HRTIM_TIMCCNTCRBase {} ;

  struct CNTCR : public RegisterBase<0x40017590, 32, ReadWriteMode>
  {
    using CNTx = HRTIM_TIMC_CNTCR_CNTx_Values<HRTIM_TIMC::CNTCR, 0, 16, ReadWriteMode, HRTIM_TIMCCNTCRBase> ;
    using FieldValues = HRTIM_TIMC_CNTCR_CNTx_Values<HRTIM_TIMC::CNTCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CNTCRPack  = Register<0x40017590, 32, ReadWriteMode, HRTIM_TIMCCNTCRBase, T...> ;

  struct HRTIM_TIMCPERCRBase {} ;

  struct PERCR : public RegisterBase<0x40017594, 32, ReadWriteMode>
  {
    using PERx = HRTIM_TIMC_PERCR_PERx_Values<HRTIM_TIMC::PERCR, 0, 16, ReadWriteMode, HRTIM_TIMCPERCRBase> ;
    using FieldValues = HRTIM_TIMC_PERCR_PERx_Values<HRTIM_TIMC::PERCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using PERCRPack  = Register<0x40017594, 32, ReadWriteMode, HRTIM_TIMCPERCRBase, T...> ;

  struct HRTIM_TIMCREPCRBase {} ;

  struct REPCR : public RegisterBase<0x40017598, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMC_REPCR_REPx_Values<HRTIM_TIMC::REPCR, 0, 8, ReadWriteMode, HRTIM_TIMCREPCRBase> ;
    using FieldValues = HRTIM_TIMC_REPCR_REPx_Values<HRTIM_TIMC::REPCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using REPCRPack  = Register<0x40017598, 32, ReadWriteMode, HRTIM_TIMCREPCRBase, T...> ;

  struct HRTIM_TIMCCMP1CRBase {} ;

  struct CMP1CR : public RegisterBase<0x4001759C, 32, ReadWriteMode>
  {
    using CMP1x = HRTIM_TIMC_CMP1CR_CMP1x_Values<HRTIM_TIMC::CMP1CR, 0, 16, ReadWriteMode, HRTIM_TIMCCMP1CRBase> ;
    using FieldValues = HRTIM_TIMC_CMP1CR_CMP1x_Values<HRTIM_TIMC::CMP1CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1CRPack  = Register<0x4001759C, 32, ReadWriteMode, HRTIM_TIMCCMP1CRBase, T...> ;

  struct HRTIM_TIMCCMP1CCRBase {} ;

  struct CMP1CCR : public RegisterBase<0x400175A0, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMC_CMP1CCR_REPx_Values<HRTIM_TIMC::CMP1CCR, 16, 8, ReadWriteMode, HRTIM_TIMCCMP1CCRBase> ;
    using CMP1x = HRTIM_TIMC_CMP1CCR_CMP1x_Values<HRTIM_TIMC::CMP1CCR, 0, 16, ReadWriteMode, HRTIM_TIMCCMP1CCRBase> ;
    using FieldValues = HRTIM_TIMC_CMP1CCR_CMP1x_Values<HRTIM_TIMC::CMP1CCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1CCRPack  = Register<0x400175A0, 32, ReadWriteMode, HRTIM_TIMCCMP1CCRBase, T...> ;

  struct HRTIM_TIMCCMP2CRBase {} ;

  struct CMP2CR : public RegisterBase<0x400175A4, 32, ReadWriteMode>
  {
    using CMP2x = HRTIM_TIMC_CMP2CR_CMP2x_Values<HRTIM_TIMC::CMP2CR, 0, 16, ReadWriteMode, HRTIM_TIMCCMP2CRBase> ;
    using FieldValues = HRTIM_TIMC_CMP2CR_CMP2x_Values<HRTIM_TIMC::CMP2CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP2CRPack  = Register<0x400175A4, 32, ReadWriteMode, HRTIM_TIMCCMP2CRBase, T...> ;

  struct HRTIM_TIMCCMP3CRBase {} ;

  struct CMP3CR : public RegisterBase<0x400175A8, 32, ReadWriteMode>
  {
    using CMP3x = HRTIM_TIMC_CMP3CR_CMP3x_Values<HRTIM_TIMC::CMP3CR, 0, 16, ReadWriteMode, HRTIM_TIMCCMP3CRBase> ;
    using FieldValues = HRTIM_TIMC_CMP3CR_CMP3x_Values<HRTIM_TIMC::CMP3CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP3CRPack  = Register<0x400175A8, 32, ReadWriteMode, HRTIM_TIMCCMP3CRBase, T...> ;

  struct HRTIM_TIMCCMP4CRBase {} ;

  struct CMP4CR : public RegisterBase<0x400175AC, 32, ReadWriteMode>
  {
    using CMP4x = HRTIM_TIMC_CMP4CR_CMP4x_Values<HRTIM_TIMC::CMP4CR, 0, 16, ReadWriteMode, HRTIM_TIMCCMP4CRBase> ;
    using FieldValues = HRTIM_TIMC_CMP4CR_CMP4x_Values<HRTIM_TIMC::CMP4CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP4CRPack  = Register<0x400175AC, 32, ReadWriteMode, HRTIM_TIMCCMP4CRBase, T...> ;

  struct HRTIM_TIMCCPT1CRBase {} ;

  struct CPT1CR : public RegisterBase<0x400175B0, 32, ReadMode>
  {
    using CPT1x = HRTIM_TIMC_CPT1CR_CPT1x_Values<HRTIM_TIMC::CPT1CR, 0, 16, ReadMode, HRTIM_TIMCCPT1CRBase> ;
    using FieldValues = HRTIM_TIMC_CPT1CR_CPT1x_Values<HRTIM_TIMC::CPT1CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1CRPack  = Register<0x400175B0, 32, ReadMode, HRTIM_TIMCCPT1CRBase, T...> ;

  struct HRTIM_TIMCCPT2CRBase {} ;

  struct CPT2CR : public RegisterBase<0x400175B4, 32, ReadMode>
  {
    using CPT2x = HRTIM_TIMC_CPT2CR_CPT2x_Values<HRTIM_TIMC::CPT2CR, 0, 16, ReadMode, HRTIM_TIMCCPT2CRBase> ;
    using FieldValues = HRTIM_TIMC_CPT2CR_CPT2x_Values<HRTIM_TIMC::CPT2CR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2CRPack  = Register<0x400175B4, 32, ReadMode, HRTIM_TIMCCPT2CRBase, T...> ;

  struct HRTIM_TIMCDTCRBase {} ;

  struct DTCR : public RegisterBase<0x400175B8, 32, ReadWriteMode>
  {
    using DTFLKx = HRTIM_TIMC_DTCR_DTFLKx_Values<HRTIM_TIMC::DTCR, 31, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTFSLKx = HRTIM_TIMC_DTCR_DTFSLKx_Values<HRTIM_TIMC::DTCR, 30, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using SDTFx = HRTIM_TIMC_DTCR_SDTFx_Values<HRTIM_TIMC::DTCR, 25, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTFx = HRTIM_TIMC_DTCR_DTFx_Values<HRTIM_TIMC::DTCR, 16, 9, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTRLKx = HRTIM_TIMC_DTCR_DTRLKx_Values<HRTIM_TIMC::DTCR, 15, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTRSLKx = HRTIM_TIMC_DTCR_DTRSLKx_Values<HRTIM_TIMC::DTCR, 14, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTPRSC = HRTIM_TIMC_DTCR_DTPRSC_Values<HRTIM_TIMC::DTCR, 10, 3, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using SDTRx = HRTIM_TIMC_DTCR_SDTRx_Values<HRTIM_TIMC::DTCR, 9, 1, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using DTRx = HRTIM_TIMC_DTCR_DTRx_Values<HRTIM_TIMC::DTCR, 0, 9, ReadWriteMode, HRTIM_TIMCDTCRBase> ;
    using FieldValues = HRTIM_TIMC_DTCR_DTRx_Values<HRTIM_TIMC::DTCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using DTCRPack  = Register<0x400175B8, 32, ReadWriteMode, HRTIM_TIMCDTCRBase, T...> ;

  struct HRTIM_TIMCSETC1RBase {} ;

  struct SETC1R : public RegisterBase<0x400175BC, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMC_SETC1R_UPDATE_Values<HRTIM_TIMC::SETC1R, 31, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT10 = HRTIM_TIMC_SETC1R_EXTEVNT10_Values<HRTIM_TIMC::SETC1R, 30, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT9 = HRTIM_TIMC_SETC1R_EXTEVNT9_Values<HRTIM_TIMC::SETC1R, 29, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT8 = HRTIM_TIMC_SETC1R_EXTEVNT8_Values<HRTIM_TIMC::SETC1R, 28, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT7 = HRTIM_TIMC_SETC1R_EXTEVNT7_Values<HRTIM_TIMC::SETC1R, 27, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT6 = HRTIM_TIMC_SETC1R_EXTEVNT6_Values<HRTIM_TIMC::SETC1R, 26, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT5 = HRTIM_TIMC_SETC1R_EXTEVNT5_Values<HRTIM_TIMC::SETC1R, 25, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT4 = HRTIM_TIMC_SETC1R_EXTEVNT4_Values<HRTIM_TIMC::SETC1R, 24, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT3 = HRTIM_TIMC_SETC1R_EXTEVNT3_Values<HRTIM_TIMC::SETC1R, 23, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT2 = HRTIM_TIMC_SETC1R_EXTEVNT2_Values<HRTIM_TIMC::SETC1R, 22, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using EXTEVNT1 = HRTIM_TIMC_SETC1R_EXTEVNT1_Values<HRTIM_TIMC::SETC1R, 21, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT9 = HRTIM_TIMC_SETC1R_TIMEVNT9_Values<HRTIM_TIMC::SETC1R, 20, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT8 = HRTIM_TIMC_SETC1R_TIMEVNT8_Values<HRTIM_TIMC::SETC1R, 19, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT7 = HRTIM_TIMC_SETC1R_TIMEVNT7_Values<HRTIM_TIMC::SETC1R, 18, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT6 = HRTIM_TIMC_SETC1R_TIMEVNT6_Values<HRTIM_TIMC::SETC1R, 17, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT5 = HRTIM_TIMC_SETC1R_TIMEVNT5_Values<HRTIM_TIMC::SETC1R, 16, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT4 = HRTIM_TIMC_SETC1R_TIMEVNT4_Values<HRTIM_TIMC::SETC1R, 15, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT3 = HRTIM_TIMC_SETC1R_TIMEVNT3_Values<HRTIM_TIMC::SETC1R, 14, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT2 = HRTIM_TIMC_SETC1R_TIMEVNT2_Values<HRTIM_TIMC::SETC1R, 13, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using TIMEVNT1 = HRTIM_TIMC_SETC1R_TIMEVNT1_Values<HRTIM_TIMC::SETC1R, 12, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using MSTCMP4 = HRTIM_TIMC_SETC1R_MSTCMP4_Values<HRTIM_TIMC::SETC1R, 11, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using MSTCMP3 = HRTIM_TIMC_SETC1R_MSTCMP3_Values<HRTIM_TIMC::SETC1R, 10, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using MSTCMP2 = HRTIM_TIMC_SETC1R_MSTCMP2_Values<HRTIM_TIMC::SETC1R, 9, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using MSTCMP1 = HRTIM_TIMC_SETC1R_MSTCMP1_Values<HRTIM_TIMC::SETC1R, 8, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using MSTPER = HRTIM_TIMC_SETC1R_MSTPER_Values<HRTIM_TIMC::SETC1R, 7, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using CMP4 = HRTIM_TIMC_SETC1R_CMP4_Values<HRTIM_TIMC::SETC1R, 6, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using CMP3 = HRTIM_TIMC_SETC1R_CMP3_Values<HRTIM_TIMC::SETC1R, 5, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using CMP2 = HRTIM_TIMC_SETC1R_CMP2_Values<HRTIM_TIMC::SETC1R, 4, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using CMP1 = HRTIM_TIMC_SETC1R_CMP1_Values<HRTIM_TIMC::SETC1R, 3, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using PER = HRTIM_TIMC_SETC1R_PER_Values<HRTIM_TIMC::SETC1R, 2, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using RESYNC = HRTIM_TIMC_SETC1R_RESYNC_Values<HRTIM_TIMC::SETC1R, 1, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using SST = HRTIM_TIMC_SETC1R_SST_Values<HRTIM_TIMC::SETC1R, 0, 1, ReadWriteMode, HRTIM_TIMCSETC1RBase> ;
    using FieldValues = HRTIM_TIMC_SETC1R_SST_Values<HRTIM_TIMC::SETC1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETC1RPack  = Register<0x400175BC, 32, ReadWriteMode, HRTIM_TIMCSETC1RBase, T...> ;

  struct HRTIM_TIMCRSTC1RBase {} ;

  struct RSTC1R : public RegisterBase<0x400175C0, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMC_RSTC1R_UPDATE_Values<HRTIM_TIMC::RSTC1R, 31, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT10 = HRTIM_TIMC_RSTC1R_EXTEVNT10_Values<HRTIM_TIMC::RSTC1R, 30, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT9 = HRTIM_TIMC_RSTC1R_EXTEVNT9_Values<HRTIM_TIMC::RSTC1R, 29, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT8 = HRTIM_TIMC_RSTC1R_EXTEVNT8_Values<HRTIM_TIMC::RSTC1R, 28, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT7 = HRTIM_TIMC_RSTC1R_EXTEVNT7_Values<HRTIM_TIMC::RSTC1R, 27, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT6 = HRTIM_TIMC_RSTC1R_EXTEVNT6_Values<HRTIM_TIMC::RSTC1R, 26, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT5 = HRTIM_TIMC_RSTC1R_EXTEVNT5_Values<HRTIM_TIMC::RSTC1R, 25, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT4 = HRTIM_TIMC_RSTC1R_EXTEVNT4_Values<HRTIM_TIMC::RSTC1R, 24, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT3 = HRTIM_TIMC_RSTC1R_EXTEVNT3_Values<HRTIM_TIMC::RSTC1R, 23, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT2 = HRTIM_TIMC_RSTC1R_EXTEVNT2_Values<HRTIM_TIMC::RSTC1R, 22, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using EXTEVNT1 = HRTIM_TIMC_RSTC1R_EXTEVNT1_Values<HRTIM_TIMC::RSTC1R, 21, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT9 = HRTIM_TIMC_RSTC1R_TIMEVNT9_Values<HRTIM_TIMC::RSTC1R, 20, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT8 = HRTIM_TIMC_RSTC1R_TIMEVNT8_Values<HRTIM_TIMC::RSTC1R, 19, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT7 = HRTIM_TIMC_RSTC1R_TIMEVNT7_Values<HRTIM_TIMC::RSTC1R, 18, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT6 = HRTIM_TIMC_RSTC1R_TIMEVNT6_Values<HRTIM_TIMC::RSTC1R, 17, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT5 = HRTIM_TIMC_RSTC1R_TIMEVNT5_Values<HRTIM_TIMC::RSTC1R, 16, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT4 = HRTIM_TIMC_RSTC1R_TIMEVNT4_Values<HRTIM_TIMC::RSTC1R, 15, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT3 = HRTIM_TIMC_RSTC1R_TIMEVNT3_Values<HRTIM_TIMC::RSTC1R, 14, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT2 = HRTIM_TIMC_RSTC1R_TIMEVNT2_Values<HRTIM_TIMC::RSTC1R, 13, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using TIMEVNT1 = HRTIM_TIMC_RSTC1R_TIMEVNT1_Values<HRTIM_TIMC::RSTC1R, 12, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using MSTCMP4 = HRTIM_TIMC_RSTC1R_MSTCMP4_Values<HRTIM_TIMC::RSTC1R, 11, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using MSTCMP3 = HRTIM_TIMC_RSTC1R_MSTCMP3_Values<HRTIM_TIMC::RSTC1R, 10, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using MSTCMP2 = HRTIM_TIMC_RSTC1R_MSTCMP2_Values<HRTIM_TIMC::RSTC1R, 9, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using MSTCMP1 = HRTIM_TIMC_RSTC1R_MSTCMP1_Values<HRTIM_TIMC::RSTC1R, 8, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using MSTPER = HRTIM_TIMC_RSTC1R_MSTPER_Values<HRTIM_TIMC::RSTC1R, 7, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using CMP4 = HRTIM_TIMC_RSTC1R_CMP4_Values<HRTIM_TIMC::RSTC1R, 6, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using CMP3 = HRTIM_TIMC_RSTC1R_CMP3_Values<HRTIM_TIMC::RSTC1R, 5, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using CMP2 = HRTIM_TIMC_RSTC1R_CMP2_Values<HRTIM_TIMC::RSTC1R, 4, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using CMP1 = HRTIM_TIMC_RSTC1R_CMP1_Values<HRTIM_TIMC::RSTC1R, 3, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using PER = HRTIM_TIMC_RSTC1R_PER_Values<HRTIM_TIMC::RSTC1R, 2, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using RESYNC = HRTIM_TIMC_RSTC1R_RESYNC_Values<HRTIM_TIMC::RSTC1R, 1, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using SRT = HRTIM_TIMC_RSTC1R_SRT_Values<HRTIM_TIMC::RSTC1R, 0, 1, ReadWriteMode, HRTIM_TIMCRSTC1RBase> ;
    using FieldValues = HRTIM_TIMC_RSTC1R_SRT_Values<HRTIM_TIMC::RSTC1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTC1RPack  = Register<0x400175C0, 32, ReadWriteMode, HRTIM_TIMCRSTC1RBase, T...> ;

  struct HRTIM_TIMCSETC2RBase {} ;

  struct SETC2R : public RegisterBase<0x400175C4, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMC_SETC2R_UPDATE_Values<HRTIM_TIMC::SETC2R, 31, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT10 = HRTIM_TIMC_SETC2R_EXTEVNT10_Values<HRTIM_TIMC::SETC2R, 30, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT9 = HRTIM_TIMC_SETC2R_EXTEVNT9_Values<HRTIM_TIMC::SETC2R, 29, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT8 = HRTIM_TIMC_SETC2R_EXTEVNT8_Values<HRTIM_TIMC::SETC2R, 28, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT7 = HRTIM_TIMC_SETC2R_EXTEVNT7_Values<HRTIM_TIMC::SETC2R, 27, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT6 = HRTIM_TIMC_SETC2R_EXTEVNT6_Values<HRTIM_TIMC::SETC2R, 26, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT5 = HRTIM_TIMC_SETC2R_EXTEVNT5_Values<HRTIM_TIMC::SETC2R, 25, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT4 = HRTIM_TIMC_SETC2R_EXTEVNT4_Values<HRTIM_TIMC::SETC2R, 24, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT3 = HRTIM_TIMC_SETC2R_EXTEVNT3_Values<HRTIM_TIMC::SETC2R, 23, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT2 = HRTIM_TIMC_SETC2R_EXTEVNT2_Values<HRTIM_TIMC::SETC2R, 22, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using EXTEVNT1 = HRTIM_TIMC_SETC2R_EXTEVNT1_Values<HRTIM_TIMC::SETC2R, 21, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT9 = HRTIM_TIMC_SETC2R_TIMEVNT9_Values<HRTIM_TIMC::SETC2R, 20, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT8 = HRTIM_TIMC_SETC2R_TIMEVNT8_Values<HRTIM_TIMC::SETC2R, 19, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT7 = HRTIM_TIMC_SETC2R_TIMEVNT7_Values<HRTIM_TIMC::SETC2R, 18, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT6 = HRTIM_TIMC_SETC2R_TIMEVNT6_Values<HRTIM_TIMC::SETC2R, 17, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT5 = HRTIM_TIMC_SETC2R_TIMEVNT5_Values<HRTIM_TIMC::SETC2R, 16, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT4 = HRTIM_TIMC_SETC2R_TIMEVNT4_Values<HRTIM_TIMC::SETC2R, 15, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT3 = HRTIM_TIMC_SETC2R_TIMEVNT3_Values<HRTIM_TIMC::SETC2R, 14, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT2 = HRTIM_TIMC_SETC2R_TIMEVNT2_Values<HRTIM_TIMC::SETC2R, 13, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using TIMEVNT1 = HRTIM_TIMC_SETC2R_TIMEVNT1_Values<HRTIM_TIMC::SETC2R, 12, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using MSTCMP4 = HRTIM_TIMC_SETC2R_MSTCMP4_Values<HRTIM_TIMC::SETC2R, 11, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using MSTCMP3 = HRTIM_TIMC_SETC2R_MSTCMP3_Values<HRTIM_TIMC::SETC2R, 10, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using MSTCMP2 = HRTIM_TIMC_SETC2R_MSTCMP2_Values<HRTIM_TIMC::SETC2R, 9, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using MSTCMP1 = HRTIM_TIMC_SETC2R_MSTCMP1_Values<HRTIM_TIMC::SETC2R, 8, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using MSTPER = HRTIM_TIMC_SETC2R_MSTPER_Values<HRTIM_TIMC::SETC2R, 7, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using CMP4 = HRTIM_TIMC_SETC2R_CMP4_Values<HRTIM_TIMC::SETC2R, 6, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using CMP3 = HRTIM_TIMC_SETC2R_CMP3_Values<HRTIM_TIMC::SETC2R, 5, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using CMP2 = HRTIM_TIMC_SETC2R_CMP2_Values<HRTIM_TIMC::SETC2R, 4, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using CMP1 = HRTIM_TIMC_SETC2R_CMP1_Values<HRTIM_TIMC::SETC2R, 3, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using PER = HRTIM_TIMC_SETC2R_PER_Values<HRTIM_TIMC::SETC2R, 2, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using RESYNC = HRTIM_TIMC_SETC2R_RESYNC_Values<HRTIM_TIMC::SETC2R, 1, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using SST = HRTIM_TIMC_SETC2R_SST_Values<HRTIM_TIMC::SETC2R, 0, 1, ReadWriteMode, HRTIM_TIMCSETC2RBase> ;
    using FieldValues = HRTIM_TIMC_SETC2R_SST_Values<HRTIM_TIMC::SETC2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETC2RPack  = Register<0x400175C4, 32, ReadWriteMode, HRTIM_TIMCSETC2RBase, T...> ;

  struct HRTIM_TIMCRSTC2RBase {} ;

  struct RSTC2R : public RegisterBase<0x400175C8, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMC_RSTC2R_UPDATE_Values<HRTIM_TIMC::RSTC2R, 31, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT10 = HRTIM_TIMC_RSTC2R_EXTEVNT10_Values<HRTIM_TIMC::RSTC2R, 30, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT9 = HRTIM_TIMC_RSTC2R_EXTEVNT9_Values<HRTIM_TIMC::RSTC2R, 29, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT8 = HRTIM_TIMC_RSTC2R_EXTEVNT8_Values<HRTIM_TIMC::RSTC2R, 28, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT7 = HRTIM_TIMC_RSTC2R_EXTEVNT7_Values<HRTIM_TIMC::RSTC2R, 27, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT6 = HRTIM_TIMC_RSTC2R_EXTEVNT6_Values<HRTIM_TIMC::RSTC2R, 26, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT5 = HRTIM_TIMC_RSTC2R_EXTEVNT5_Values<HRTIM_TIMC::RSTC2R, 25, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT4 = HRTIM_TIMC_RSTC2R_EXTEVNT4_Values<HRTIM_TIMC::RSTC2R, 24, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT3 = HRTIM_TIMC_RSTC2R_EXTEVNT3_Values<HRTIM_TIMC::RSTC2R, 23, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT2 = HRTIM_TIMC_RSTC2R_EXTEVNT2_Values<HRTIM_TIMC::RSTC2R, 22, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using EXTEVNT1 = HRTIM_TIMC_RSTC2R_EXTEVNT1_Values<HRTIM_TIMC::RSTC2R, 21, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT9 = HRTIM_TIMC_RSTC2R_TIMEVNT9_Values<HRTIM_TIMC::RSTC2R, 20, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT8 = HRTIM_TIMC_RSTC2R_TIMEVNT8_Values<HRTIM_TIMC::RSTC2R, 19, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT7 = HRTIM_TIMC_RSTC2R_TIMEVNT7_Values<HRTIM_TIMC::RSTC2R, 18, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT6 = HRTIM_TIMC_RSTC2R_TIMEVNT6_Values<HRTIM_TIMC::RSTC2R, 17, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT5 = HRTIM_TIMC_RSTC2R_TIMEVNT5_Values<HRTIM_TIMC::RSTC2R, 16, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT4 = HRTIM_TIMC_RSTC2R_TIMEVNT4_Values<HRTIM_TIMC::RSTC2R, 15, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT3 = HRTIM_TIMC_RSTC2R_TIMEVNT3_Values<HRTIM_TIMC::RSTC2R, 14, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT2 = HRTIM_TIMC_RSTC2R_TIMEVNT2_Values<HRTIM_TIMC::RSTC2R, 13, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using TIMEVNT1 = HRTIM_TIMC_RSTC2R_TIMEVNT1_Values<HRTIM_TIMC::RSTC2R, 12, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using MSTCMP4 = HRTIM_TIMC_RSTC2R_MSTCMP4_Values<HRTIM_TIMC::RSTC2R, 11, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using MSTCMP3 = HRTIM_TIMC_RSTC2R_MSTCMP3_Values<HRTIM_TIMC::RSTC2R, 10, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using MSTCMP2 = HRTIM_TIMC_RSTC2R_MSTCMP2_Values<HRTIM_TIMC::RSTC2R, 9, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using MSTCMP1 = HRTIM_TIMC_RSTC2R_MSTCMP1_Values<HRTIM_TIMC::RSTC2R, 8, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using MSTPER = HRTIM_TIMC_RSTC2R_MSTPER_Values<HRTIM_TIMC::RSTC2R, 7, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using CMP4 = HRTIM_TIMC_RSTC2R_CMP4_Values<HRTIM_TIMC::RSTC2R, 6, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using CMP3 = HRTIM_TIMC_RSTC2R_CMP3_Values<HRTIM_TIMC::RSTC2R, 5, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using CMP2 = HRTIM_TIMC_RSTC2R_CMP2_Values<HRTIM_TIMC::RSTC2R, 4, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using CMP1 = HRTIM_TIMC_RSTC2R_CMP1_Values<HRTIM_TIMC::RSTC2R, 3, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using PER = HRTIM_TIMC_RSTC2R_PER_Values<HRTIM_TIMC::RSTC2R, 2, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using RESYNC = HRTIM_TIMC_RSTC2R_RESYNC_Values<HRTIM_TIMC::RSTC2R, 1, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using SRT = HRTIM_TIMC_RSTC2R_SRT_Values<HRTIM_TIMC::RSTC2R, 0, 1, ReadWriteMode, HRTIM_TIMCRSTC2RBase> ;
    using FieldValues = HRTIM_TIMC_RSTC2R_SRT_Values<HRTIM_TIMC::RSTC2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTC2RPack  = Register<0x400175C8, 32, ReadWriteMode, HRTIM_TIMCRSTC2RBase, T...> ;

  struct HRTIM_TIMCEEFCR1Base {} ;

  struct EEFCR1 : public RegisterBase<0x400175CC, 32, ReadWriteMode>
  {
    using EE5FLTR = HRTIM_TIMC_EEFCR1_EE5FLTR_Values<HRTIM_TIMC::EEFCR1, 25, 4, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE5LTCH = HRTIM_TIMC_EEFCR1_EE5LTCH_Values<HRTIM_TIMC::EEFCR1, 24, 1, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE4FLTR = HRTIM_TIMC_EEFCR1_EE4FLTR_Values<HRTIM_TIMC::EEFCR1, 19, 4, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE4LTCH = HRTIM_TIMC_EEFCR1_EE4LTCH_Values<HRTIM_TIMC::EEFCR1, 18, 1, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE3FLTR = HRTIM_TIMC_EEFCR1_EE3FLTR_Values<HRTIM_TIMC::EEFCR1, 13, 4, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE3LTCH = HRTIM_TIMC_EEFCR1_EE3LTCH_Values<HRTIM_TIMC::EEFCR1, 12, 1, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE2FLTR = HRTIM_TIMC_EEFCR1_EE2FLTR_Values<HRTIM_TIMC::EEFCR1, 7, 4, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE2LTCH = HRTIM_TIMC_EEFCR1_EE2LTCH_Values<HRTIM_TIMC::EEFCR1, 6, 1, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE1FLTR = HRTIM_TIMC_EEFCR1_EE1FLTR_Values<HRTIM_TIMC::EEFCR1, 1, 4, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using EE1LTCH = HRTIM_TIMC_EEFCR1_EE1LTCH_Values<HRTIM_TIMC::EEFCR1, 0, 1, ReadWriteMode, HRTIM_TIMCEEFCR1Base> ;
    using FieldValues = HRTIM_TIMC_EEFCR1_EE1LTCH_Values<HRTIM_TIMC::EEFCR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFCR1Pack  = Register<0x400175CC, 32, ReadWriteMode, HRTIM_TIMCEEFCR1Base, T...> ;

  struct HRTIM_TIMCEEFCR2Base {} ;

  struct EEFCR2 : public RegisterBase<0x400175D0, 32, ReadWriteMode>
  {
    using EE10FLTR = HRTIM_TIMC_EEFCR2_EE10FLTR_Values<HRTIM_TIMC::EEFCR2, 25, 4, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE10LTCH = HRTIM_TIMC_EEFCR2_EE10LTCH_Values<HRTIM_TIMC::EEFCR2, 24, 1, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE9FLTR = HRTIM_TIMC_EEFCR2_EE9FLTR_Values<HRTIM_TIMC::EEFCR2, 19, 4, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE9LTCH = HRTIM_TIMC_EEFCR2_EE9LTCH_Values<HRTIM_TIMC::EEFCR2, 18, 1, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE8FLTR = HRTIM_TIMC_EEFCR2_EE8FLTR_Values<HRTIM_TIMC::EEFCR2, 13, 4, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE8LTCH = HRTIM_TIMC_EEFCR2_EE8LTCH_Values<HRTIM_TIMC::EEFCR2, 12, 1, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE7FLTR = HRTIM_TIMC_EEFCR2_EE7FLTR_Values<HRTIM_TIMC::EEFCR2, 7, 4, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE7LTCH = HRTIM_TIMC_EEFCR2_EE7LTCH_Values<HRTIM_TIMC::EEFCR2, 6, 1, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE6FLTR = HRTIM_TIMC_EEFCR2_EE6FLTR_Values<HRTIM_TIMC::EEFCR2, 1, 4, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using EE6LTCH = HRTIM_TIMC_EEFCR2_EE6LTCH_Values<HRTIM_TIMC::EEFCR2, 0, 1, ReadWriteMode, HRTIM_TIMCEEFCR2Base> ;
    using FieldValues = HRTIM_TIMC_EEFCR2_EE6LTCH_Values<HRTIM_TIMC::EEFCR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFCR2Pack  = Register<0x400175D0, 32, ReadWriteMode, HRTIM_TIMCEEFCR2Base, T...> ;

  struct HRTIM_TIMCRSTCRBase {} ;

  struct RSTCR : public RegisterBase<0x400175D4, 32, ReadWriteMode>
  {
    using TIMECMP4 = HRTIM_TIMC_RSTCR_TIMECMP4_Values<HRTIM_TIMC::RSTCR, 30, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMECMP2 = HRTIM_TIMC_RSTCR_TIMECMP2_Values<HRTIM_TIMC::RSTCR, 29, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMECMP1 = HRTIM_TIMC_RSTCR_TIMECMP1_Values<HRTIM_TIMC::RSTCR, 28, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMDCMP4 = HRTIM_TIMC_RSTCR_TIMDCMP4_Values<HRTIM_TIMC::RSTCR, 27, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMDCMP2 = HRTIM_TIMC_RSTCR_TIMDCMP2_Values<HRTIM_TIMC::RSTCR, 26, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMDCMP1 = HRTIM_TIMC_RSTCR_TIMDCMP1_Values<HRTIM_TIMC::RSTCR, 25, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMBCMP4 = HRTIM_TIMC_RSTCR_TIMBCMP4_Values<HRTIM_TIMC::RSTCR, 24, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMBCMP2 = HRTIM_TIMC_RSTCR_TIMBCMP2_Values<HRTIM_TIMC::RSTCR, 23, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMBCMP1 = HRTIM_TIMC_RSTCR_TIMBCMP1_Values<HRTIM_TIMC::RSTCR, 22, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMACMP4 = HRTIM_TIMC_RSTCR_TIMACMP4_Values<HRTIM_TIMC::RSTCR, 21, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMACMP2 = HRTIM_TIMC_RSTCR_TIMACMP2_Values<HRTIM_TIMC::RSTCR, 20, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using TIMACMP1 = HRTIM_TIMC_RSTCR_TIMACMP1_Values<HRTIM_TIMC::RSTCR, 19, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT10 = HRTIM_TIMC_RSTCR_EXTEVNT10_Values<HRTIM_TIMC::RSTCR, 18, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT9 = HRTIM_TIMC_RSTCR_EXTEVNT9_Values<HRTIM_TIMC::RSTCR, 17, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT8 = HRTIM_TIMC_RSTCR_EXTEVNT8_Values<HRTIM_TIMC::RSTCR, 16, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT7 = HRTIM_TIMC_RSTCR_EXTEVNT7_Values<HRTIM_TIMC::RSTCR, 15, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT6 = HRTIM_TIMC_RSTCR_EXTEVNT6_Values<HRTIM_TIMC::RSTCR, 14, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT5 = HRTIM_TIMC_RSTCR_EXTEVNT5_Values<HRTIM_TIMC::RSTCR, 13, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT4 = HRTIM_TIMC_RSTCR_EXTEVNT4_Values<HRTIM_TIMC::RSTCR, 12, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT3 = HRTIM_TIMC_RSTCR_EXTEVNT3_Values<HRTIM_TIMC::RSTCR, 11, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT2 = HRTIM_TIMC_RSTCR_EXTEVNT2_Values<HRTIM_TIMC::RSTCR, 10, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using EXTEVNT1 = HRTIM_TIMC_RSTCR_EXTEVNT1_Values<HRTIM_TIMC::RSTCR, 9, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using MSTCMP4 = HRTIM_TIMC_RSTCR_MSTCMP4_Values<HRTIM_TIMC::RSTCR, 8, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using MSTCMP3 = HRTIM_TIMC_RSTCR_MSTCMP3_Values<HRTIM_TIMC::RSTCR, 7, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using MSTCMP2 = HRTIM_TIMC_RSTCR_MSTCMP2_Values<HRTIM_TIMC::RSTCR, 6, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using MSTCMP1 = HRTIM_TIMC_RSTCR_MSTCMP1_Values<HRTIM_TIMC::RSTCR, 5, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using MSTPER = HRTIM_TIMC_RSTCR_MSTPER_Values<HRTIM_TIMC::RSTCR, 4, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using CMP4 = HRTIM_TIMC_RSTCR_CMP4_Values<HRTIM_TIMC::RSTCR, 3, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using CMP2 = HRTIM_TIMC_RSTCR_CMP2_Values<HRTIM_TIMC::RSTCR, 2, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using UPDT = HRTIM_TIMC_RSTCR_UPDT_Values<HRTIM_TIMC::RSTCR, 1, 1, ReadWriteMode, HRTIM_TIMCRSTCRBase> ;
    using FieldValues = HRTIM_TIMC_RSTCR_UPDT_Values<HRTIM_TIMC::RSTCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTCRPack  = Register<0x400175D4, 32, ReadWriteMode, HRTIM_TIMCRSTCRBase, T...> ;

  struct HRTIM_TIMCCHPCRBase {} ;

  struct CHPCR : public RegisterBase<0x400175D8, 32, ReadWriteMode>
  {
    using STRTPW = HRTIM_TIMC_CHPCR_STRTPW_Values<HRTIM_TIMC::CHPCR, 7, 4, ReadWriteMode, HRTIM_TIMCCHPCRBase> ;
    using CHPDTY = HRTIM_TIMC_CHPCR_CHPDTY_Values<HRTIM_TIMC::CHPCR, 4, 3, ReadWriteMode, HRTIM_TIMCCHPCRBase> ;
    using CHPFRQ = HRTIM_TIMC_CHPCR_CHPFRQ_Values<HRTIM_TIMC::CHPCR, 0, 4, ReadWriteMode, HRTIM_TIMCCHPCRBase> ;
    using FieldValues = HRTIM_TIMC_CHPCR_CHPFRQ_Values<HRTIM_TIMC::CHPCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CHPCRPack  = Register<0x400175D8, 32, ReadWriteMode, HRTIM_TIMCCHPCRBase, T...> ;

  struct HRTIM_TIMCCPT1CCRBase {} ;

  struct CPT1CCR : public RegisterBase<0x400175DC, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMC_CPT1CCR_TECMP2_Values<HRTIM_TIMC::CPT1CCR, 31, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TECMP1 = HRTIM_TIMC_CPT1CCR_TECMP1_Values<HRTIM_TIMC::CPT1CCR, 30, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TE1RST = HRTIM_TIMC_CPT1CCR_TE1RST_Values<HRTIM_TIMC::CPT1CCR, 29, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TE1SET = HRTIM_TIMC_CPT1CCR_TE1SET_Values<HRTIM_TIMC::CPT1CCR, 28, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TDCMP2 = HRTIM_TIMC_CPT1CCR_TDCMP2_Values<HRTIM_TIMC::CPT1CCR, 27, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TDCMP1 = HRTIM_TIMC_CPT1CCR_TDCMP1_Values<HRTIM_TIMC::CPT1CCR, 26, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TD1RST = HRTIM_TIMC_CPT1CCR_TD1RST_Values<HRTIM_TIMC::CPT1CCR, 25, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TD1SET = HRTIM_TIMC_CPT1CCR_TD1SET_Values<HRTIM_TIMC::CPT1CCR, 24, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TBCMP2 = HRTIM_TIMC_CPT1CCR_TBCMP2_Values<HRTIM_TIMC::CPT1CCR, 19, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TBCMP1 = HRTIM_TIMC_CPT1CCR_TBCMP1_Values<HRTIM_TIMC::CPT1CCR, 18, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TB1RST = HRTIM_TIMC_CPT1CCR_TB1RST_Values<HRTIM_TIMC::CPT1CCR, 17, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TB1SET = HRTIM_TIMC_CPT1CCR_TB1SET_Values<HRTIM_TIMC::CPT1CCR, 16, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TACMP2 = HRTIM_TIMC_CPT1CCR_TACMP2_Values<HRTIM_TIMC::CPT1CCR, 15, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TACMP1 = HRTIM_TIMC_CPT1CCR_TACMP1_Values<HRTIM_TIMC::CPT1CCR, 14, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TA1RST = HRTIM_TIMC_CPT1CCR_TA1RST_Values<HRTIM_TIMC::CPT1CCR, 13, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using TA1SET = HRTIM_TIMC_CPT1CCR_TA1SET_Values<HRTIM_TIMC::CPT1CCR, 12, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV10CPT = HRTIM_TIMC_CPT1CCR_EXEV10CPT_Values<HRTIM_TIMC::CPT1CCR, 11, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV9CPT = HRTIM_TIMC_CPT1CCR_EXEV9CPT_Values<HRTIM_TIMC::CPT1CCR, 10, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV8CPT = HRTIM_TIMC_CPT1CCR_EXEV8CPT_Values<HRTIM_TIMC::CPT1CCR, 9, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV7CPT = HRTIM_TIMC_CPT1CCR_EXEV7CPT_Values<HRTIM_TIMC::CPT1CCR, 8, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV6CPT = HRTIM_TIMC_CPT1CCR_EXEV6CPT_Values<HRTIM_TIMC::CPT1CCR, 7, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV5CPT = HRTIM_TIMC_CPT1CCR_EXEV5CPT_Values<HRTIM_TIMC::CPT1CCR, 6, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV4CPT = HRTIM_TIMC_CPT1CCR_EXEV4CPT_Values<HRTIM_TIMC::CPT1CCR, 5, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV3CPT = HRTIM_TIMC_CPT1CCR_EXEV3CPT_Values<HRTIM_TIMC::CPT1CCR, 4, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV2CPT = HRTIM_TIMC_CPT1CCR_EXEV2CPT_Values<HRTIM_TIMC::CPT1CCR, 3, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using EXEV1CPT = HRTIM_TIMC_CPT1CCR_EXEV1CPT_Values<HRTIM_TIMC::CPT1CCR, 2, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using UDPCPT = HRTIM_TIMC_CPT1CCR_UDPCPT_Values<HRTIM_TIMC::CPT1CCR, 1, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using SWCPT = HRTIM_TIMC_CPT1CCR_SWCPT_Values<HRTIM_TIMC::CPT1CCR, 0, 1, ReadWriteMode, HRTIM_TIMCCPT1CCRBase> ;
    using FieldValues = HRTIM_TIMC_CPT1CCR_SWCPT_Values<HRTIM_TIMC::CPT1CCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1CCRPack  = Register<0x400175DC, 32, ReadWriteMode, HRTIM_TIMCCPT1CCRBase, T...> ;

  struct HRTIM_TIMCCPT2CCRBase {} ;

  struct CPT2CCR : public RegisterBase<0x400175E0, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMC_CPT2CCR_TECMP2_Values<HRTIM_TIMC::CPT2CCR, 31, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TECMP1 = HRTIM_TIMC_CPT2CCR_TECMP1_Values<HRTIM_TIMC::CPT2CCR, 30, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TE1RST = HRTIM_TIMC_CPT2CCR_TE1RST_Values<HRTIM_TIMC::CPT2CCR, 29, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TE1SET = HRTIM_TIMC_CPT2CCR_TE1SET_Values<HRTIM_TIMC::CPT2CCR, 28, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TDCMP2 = HRTIM_TIMC_CPT2CCR_TDCMP2_Values<HRTIM_TIMC::CPT2CCR, 27, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TDCMP1 = HRTIM_TIMC_CPT2CCR_TDCMP1_Values<HRTIM_TIMC::CPT2CCR, 26, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TD1RST = HRTIM_TIMC_CPT2CCR_TD1RST_Values<HRTIM_TIMC::CPT2CCR, 25, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TD1SET = HRTIM_TIMC_CPT2CCR_TD1SET_Values<HRTIM_TIMC::CPT2CCR, 24, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TBCMP2 = HRTIM_TIMC_CPT2CCR_TBCMP2_Values<HRTIM_TIMC::CPT2CCR, 19, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TBCMP1 = HRTIM_TIMC_CPT2CCR_TBCMP1_Values<HRTIM_TIMC::CPT2CCR, 18, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TB1RST = HRTIM_TIMC_CPT2CCR_TB1RST_Values<HRTIM_TIMC::CPT2CCR, 17, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TB1SET = HRTIM_TIMC_CPT2CCR_TB1SET_Values<HRTIM_TIMC::CPT2CCR, 16, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TACMP2 = HRTIM_TIMC_CPT2CCR_TACMP2_Values<HRTIM_TIMC::CPT2CCR, 15, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TACMP1 = HRTIM_TIMC_CPT2CCR_TACMP1_Values<HRTIM_TIMC::CPT2CCR, 14, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TA1RST = HRTIM_TIMC_CPT2CCR_TA1RST_Values<HRTIM_TIMC::CPT2CCR, 13, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using TA1SET = HRTIM_TIMC_CPT2CCR_TA1SET_Values<HRTIM_TIMC::CPT2CCR, 12, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV10CPT = HRTIM_TIMC_CPT2CCR_EXEV10CPT_Values<HRTIM_TIMC::CPT2CCR, 11, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV9CPT = HRTIM_TIMC_CPT2CCR_EXEV9CPT_Values<HRTIM_TIMC::CPT2CCR, 10, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV8CPT = HRTIM_TIMC_CPT2CCR_EXEV8CPT_Values<HRTIM_TIMC::CPT2CCR, 9, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV7CPT = HRTIM_TIMC_CPT2CCR_EXEV7CPT_Values<HRTIM_TIMC::CPT2CCR, 8, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV6CPT = HRTIM_TIMC_CPT2CCR_EXEV6CPT_Values<HRTIM_TIMC::CPT2CCR, 7, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV5CPT = HRTIM_TIMC_CPT2CCR_EXEV5CPT_Values<HRTIM_TIMC::CPT2CCR, 6, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV4CPT = HRTIM_TIMC_CPT2CCR_EXEV4CPT_Values<HRTIM_TIMC::CPT2CCR, 5, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV3CPT = HRTIM_TIMC_CPT2CCR_EXEV3CPT_Values<HRTIM_TIMC::CPT2CCR, 4, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV2CPT = HRTIM_TIMC_CPT2CCR_EXEV2CPT_Values<HRTIM_TIMC::CPT2CCR, 3, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using EXEV1CPT = HRTIM_TIMC_CPT2CCR_EXEV1CPT_Values<HRTIM_TIMC::CPT2CCR, 2, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using UDPCPT = HRTIM_TIMC_CPT2CCR_UDPCPT_Values<HRTIM_TIMC::CPT2CCR, 1, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using SWCPT = HRTIM_TIMC_CPT2CCR_SWCPT_Values<HRTIM_TIMC::CPT2CCR, 0, 1, ReadWriteMode, HRTIM_TIMCCPT2CCRBase> ;
    using FieldValues = HRTIM_TIMC_CPT2CCR_SWCPT_Values<HRTIM_TIMC::CPT2CCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2CCRPack  = Register<0x400175E0, 32, ReadWriteMode, HRTIM_TIMCCPT2CCRBase, T...> ;

  struct HRTIM_TIMCOUTCRBase {} ;

  struct OUTCR : public RegisterBase<0x400175E4, 32, ReadWriteMode>
  {
    using DIDL2 = HRTIM_TIMC_OUTCR_DIDL2_Values<HRTIM_TIMC::OUTCR, 23, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using CHP2 = HRTIM_TIMC_OUTCR_CHP2_Values<HRTIM_TIMC::OUTCR, 22, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using FAULT2 = HRTIM_TIMC_OUTCR_FAULT2_Values<HRTIM_TIMC::OUTCR, 20, 2, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using IDLES2 = HRTIM_TIMC_OUTCR_IDLES2_Values<HRTIM_TIMC::OUTCR, 19, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using IDLEM2 = HRTIM_TIMC_OUTCR_IDLEM2_Values<HRTIM_TIMC::OUTCR, 18, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using POL2 = HRTIM_TIMC_OUTCR_POL2_Values<HRTIM_TIMC::OUTCR, 17, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using DLYPRT = HRTIM_TIMC_OUTCR_DLYPRT_Values<HRTIM_TIMC::OUTCR, 10, 3, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using DLYPRTEN = HRTIM_TIMC_OUTCR_DLYPRTEN_Values<HRTIM_TIMC::OUTCR, 9, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using DTEN = HRTIM_TIMC_OUTCR_DTEN_Values<HRTIM_TIMC::OUTCR, 8, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using DIDL1 = HRTIM_TIMC_OUTCR_DIDL1_Values<HRTIM_TIMC::OUTCR, 7, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using CHP1 = HRTIM_TIMC_OUTCR_CHP1_Values<HRTIM_TIMC::OUTCR, 6, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using FAULT1 = HRTIM_TIMC_OUTCR_FAULT1_Values<HRTIM_TIMC::OUTCR, 4, 2, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using IDLES1 = HRTIM_TIMC_OUTCR_IDLES1_Values<HRTIM_TIMC::OUTCR, 3, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using IDLEM1 = HRTIM_TIMC_OUTCR_IDLEM1_Values<HRTIM_TIMC::OUTCR, 2, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using POL1 = HRTIM_TIMC_OUTCR_POL1_Values<HRTIM_TIMC::OUTCR, 1, 1, ReadWriteMode, HRTIM_TIMCOUTCRBase> ;
    using FieldValues = HRTIM_TIMC_OUTCR_POL1_Values<HRTIM_TIMC::OUTCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OUTCRPack  = Register<0x400175E4, 32, ReadWriteMode, HRTIM_TIMCOUTCRBase, T...> ;

  struct HRTIM_TIMCFLTCRBase {} ;

  struct FLTCR : public RegisterBase<0x400175E8, 32, ReadWriteMode>
  {
    using FLTLCK = HRTIM_TIMC_FLTCR_FLTLCK_Values<HRTIM_TIMC::FLTCR, 31, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FLT5EN = HRTIM_TIMC_FLTCR_FLT5EN_Values<HRTIM_TIMC::FLTCR, 4, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FLT4EN = HRTIM_TIMC_FLTCR_FLT4EN_Values<HRTIM_TIMC::FLTCR, 3, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FLT3EN = HRTIM_TIMC_FLTCR_FLT3EN_Values<HRTIM_TIMC::FLTCR, 2, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FLT2EN = HRTIM_TIMC_FLTCR_FLT2EN_Values<HRTIM_TIMC::FLTCR, 1, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FLT1EN = HRTIM_TIMC_FLTCR_FLT1EN_Values<HRTIM_TIMC::FLTCR, 0, 1, ReadWriteMode, HRTIM_TIMCFLTCRBase> ;
    using FieldValues = HRTIM_TIMC_FLTCR_FLT1EN_Values<HRTIM_TIMC::FLTCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using FLTCRPack  = Register<0x400175E8, 32, ReadWriteMode, HRTIM_TIMCFLTCRBase, T...> ;

} ;

#endif //#if !defined(HRTIMTIMCREGISTERS_HPP)
