/*******************************************************************************
* Filename      : hrtimtimdregisters.hpp
*
* Details       : High Resolution Timer: TIMD. This header file is
*                 auto-generated for STM32H745_CM7 device.
*
*
*******************************************************************************/

#if !defined(HRTIMTIMDREGISTERS_HPP)
#define HRTIMTIMDREGISTERS_HPP

#include "hrtimtimdfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct HRTIM_TIMD
{
  struct HRTIM_TIMDTIMDCRBase {} ;

  struct TIMDCR : public RegisterBase<0x40017600, 32, ReadWriteMode>
  {
    using UPDGAT = HRTIM_TIMD_TIMDCR_UPDGAT_Values<HRTIM_TIMD::TIMDCR, 28, 4, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using PREEN = HRTIM_TIMD_TIMDCR_PREEN_Values<HRTIM_TIMD::TIMDCR, 27, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using DACSYNC = HRTIM_TIMD_TIMDCR_DACSYNC_Values<HRTIM_TIMD::TIMDCR, 25, 2, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using MSTU = HRTIM_TIMD_TIMDCR_MSTU_Values<HRTIM_TIMD::TIMDCR, 24, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TEU = HRTIM_TIMD_TIMDCR_TEU_Values<HRTIM_TIMD::TIMDCR, 23, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TDU = HRTIM_TIMD_TIMDCR_TDU_Values<HRTIM_TIMD::TIMDCR, 22, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TCU = HRTIM_TIMD_TIMDCR_TCU_Values<HRTIM_TIMD::TIMDCR, 21, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TBU = HRTIM_TIMD_TIMDCR_TBU_Values<HRTIM_TIMD::TIMDCR, 20, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TxRSTU = HRTIM_TIMD_TIMDCR_TxRSTU_Values<HRTIM_TIMD::TIMDCR, 18, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using TxREPU = HRTIM_TIMD_TIMDCR_TxREPU_Values<HRTIM_TIMD::TIMDCR, 17, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using DELCMP4 = HRTIM_TIMD_TIMDCR_DELCMP4_Values<HRTIM_TIMD::TIMDCR, 14, 2, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using DELCMP2 = HRTIM_TIMD_TIMDCR_DELCMP2_Values<HRTIM_TIMD::TIMDCR, 12, 2, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using SYNCSTRTx = HRTIM_TIMD_TIMDCR_SYNCSTRTx_Values<HRTIM_TIMD::TIMDCR, 11, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using SYNCRSTx = HRTIM_TIMD_TIMDCR_SYNCRSTx_Values<HRTIM_TIMD::TIMDCR, 10, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using PSHPLL = HRTIM_TIMD_TIMDCR_PSHPLL_Values<HRTIM_TIMD::TIMDCR, 6, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using HALF = HRTIM_TIMD_TIMDCR_HALF_Values<HRTIM_TIMD::TIMDCR, 5, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using RETRIG = HRTIM_TIMD_TIMDCR_RETRIG_Values<HRTIM_TIMD::TIMDCR, 4, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using CONT = HRTIM_TIMD_TIMDCR_CONT_Values<HRTIM_TIMD::TIMDCR, 3, 1, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using CK_PSCx = HRTIM_TIMD_TIMDCR_CK_PSCx_Values<HRTIM_TIMD::TIMDCR, 0, 3, ReadWriteMode, HRTIM_TIMDTIMDCRBase> ;
    using FieldValues = HRTIM_TIMD_TIMDCR_CK_PSCx_Values<HRTIM_TIMD::TIMDCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMDCRPack  = Register<0x40017600, 32, ReadWriteMode, HRTIM_TIMDTIMDCRBase, T...> ;

  struct HRTIM_TIMDTIMDISRBase {} ;

  struct TIMDISR : public RegisterBase<0x40017604, 32, ReadMode>
  {
    using O2STAT = HRTIM_TIMD_TIMDISR_O2STAT_Values<HRTIM_TIMD::TIMDISR, 19, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using O1STAT = HRTIM_TIMD_TIMDISR_O1STAT_Values<HRTIM_TIMD::TIMDISR, 18, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using IPPSTAT = HRTIM_TIMD_TIMDISR_IPPSTAT_Values<HRTIM_TIMD::TIMDISR, 17, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CPPSTAT = HRTIM_TIMD_TIMDISR_CPPSTAT_Values<HRTIM_TIMD::TIMDISR, 16, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using DLYPRT = HRTIM_TIMD_TIMDISR_DLYPRT_Values<HRTIM_TIMD::TIMDISR, 14, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using RST = HRTIM_TIMD_TIMDISR_RST_Values<HRTIM_TIMD::TIMDISR, 13, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using RSTx2 = HRTIM_TIMD_TIMDISR_RSTx2_Values<HRTIM_TIMD::TIMDISR, 12, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using SETx2 = HRTIM_TIMD_TIMDISR_SETx2_Values<HRTIM_TIMD::TIMDISR, 11, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using RSTx1 = HRTIM_TIMD_TIMDISR_RSTx1_Values<HRTIM_TIMD::TIMDISR, 10, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using SETx1 = HRTIM_TIMD_TIMDISR_SETx1_Values<HRTIM_TIMD::TIMDISR, 9, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CPT2 = HRTIM_TIMD_TIMDISR_CPT2_Values<HRTIM_TIMD::TIMDISR, 8, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CPT1 = HRTIM_TIMD_TIMDISR_CPT1_Values<HRTIM_TIMD::TIMDISR, 7, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using UPD = HRTIM_TIMD_TIMDISR_UPD_Values<HRTIM_TIMD::TIMDISR, 6, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using REP = HRTIM_TIMD_TIMDISR_REP_Values<HRTIM_TIMD::TIMDISR, 4, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CMP4 = HRTIM_TIMD_TIMDISR_CMP4_Values<HRTIM_TIMD::TIMDISR, 3, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CMP3 = HRTIM_TIMD_TIMDISR_CMP3_Values<HRTIM_TIMD::TIMDISR, 2, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CMP2 = HRTIM_TIMD_TIMDISR_CMP2_Values<HRTIM_TIMD::TIMDISR, 1, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using CMP1 = HRTIM_TIMD_TIMDISR_CMP1_Values<HRTIM_TIMD::TIMDISR, 0, 1, ReadMode, HRTIM_TIMDTIMDISRBase> ;
    using FieldValues = HRTIM_TIMD_TIMDISR_CMP1_Values<HRTIM_TIMD::TIMDISR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMDISRPack  = Register<0x40017604, 32, ReadMode, HRTIM_TIMDTIMDISRBase, T...> ;

  struct HRTIM_TIMDTIMDICRBase {} ;

  struct TIMDICR : public RegisterBase<0x40017608, 32, WriteMode>
  {
    using DLYPRTC = HRTIM_TIMD_TIMDICR_DLYPRTC_Values<HRTIM_TIMD::TIMDICR, 14, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using RSTC = HRTIM_TIMD_TIMDICR_RSTC_Values<HRTIM_TIMD::TIMDICR, 13, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using RSTx2C = HRTIM_TIMD_TIMDICR_RSTx2C_Values<HRTIM_TIMD::TIMDICR, 12, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using SET2xC = HRTIM_TIMD_TIMDICR_SET2xC_Values<HRTIM_TIMD::TIMDICR, 11, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using RSTx1C = HRTIM_TIMD_TIMDICR_RSTx1C_Values<HRTIM_TIMD::TIMDICR, 10, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using SET1xC = HRTIM_TIMD_TIMDICR_SET1xC_Values<HRTIM_TIMD::TIMDICR, 9, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CPT2C = HRTIM_TIMD_TIMDICR_CPT2C_Values<HRTIM_TIMD::TIMDICR, 8, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CPT1C = HRTIM_TIMD_TIMDICR_CPT1C_Values<HRTIM_TIMD::TIMDICR, 7, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using UPDC = HRTIM_TIMD_TIMDICR_UPDC_Values<HRTIM_TIMD::TIMDICR, 6, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using REPC = HRTIM_TIMD_TIMDICR_REPC_Values<HRTIM_TIMD::TIMDICR, 4, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CMP4C = HRTIM_TIMD_TIMDICR_CMP4C_Values<HRTIM_TIMD::TIMDICR, 3, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CMP3C = HRTIM_TIMD_TIMDICR_CMP3C_Values<HRTIM_TIMD::TIMDICR, 2, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CMP2C = HRTIM_TIMD_TIMDICR_CMP2C_Values<HRTIM_TIMD::TIMDICR, 1, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using CMP1C = HRTIM_TIMD_TIMDICR_CMP1C_Values<HRTIM_TIMD::TIMDICR, 0, 1, WriteMode, HRTIM_TIMDTIMDICRBase> ;
    using FieldValues = HRTIM_TIMD_TIMDICR_CMP1C_Values<HRTIM_TIMD::TIMDICR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMDICRPack  = Register<0x40017608, 32, WriteMode, HRTIM_TIMDTIMDICRBase, T...> ;

  struct HRTIM_TIMDTIMDDIER5Base {} ;

  struct TIMDDIER5 : public RegisterBase<0x4001760C, 32, ReadWriteMode>
  {
    using DLYPRTDE = HRTIM_TIMD_TIMDDIER5_DLYPRTDE_Values<HRTIM_TIMD::TIMDDIER5, 30, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTDE = HRTIM_TIMD_TIMDDIER5_RSTDE_Values<HRTIM_TIMD::TIMDDIER5, 29, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTx2DE = HRTIM_TIMD_TIMDDIER5_RSTx2DE_Values<HRTIM_TIMD::TIMDDIER5, 28, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using SETx2DE = HRTIM_TIMD_TIMDDIER5_SETx2DE_Values<HRTIM_TIMD::TIMDDIER5, 27, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTx1DE = HRTIM_TIMD_TIMDDIER5_RSTx1DE_Values<HRTIM_TIMD::TIMDDIER5, 26, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using SET1xDE = HRTIM_TIMD_TIMDDIER5_SET1xDE_Values<HRTIM_TIMD::TIMDDIER5, 25, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CPT2DE = HRTIM_TIMD_TIMDDIER5_CPT2DE_Values<HRTIM_TIMD::TIMDDIER5, 24, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CPT1DE = HRTIM_TIMD_TIMDDIER5_CPT1DE_Values<HRTIM_TIMD::TIMDDIER5, 23, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using UPDDE = HRTIM_TIMD_TIMDDIER5_UPDDE_Values<HRTIM_TIMD::TIMDDIER5, 22, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using REPDE = HRTIM_TIMD_TIMDDIER5_REPDE_Values<HRTIM_TIMD::TIMDDIER5, 20, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP4DE = HRTIM_TIMD_TIMDDIER5_CMP4DE_Values<HRTIM_TIMD::TIMDDIER5, 19, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP3DE = HRTIM_TIMD_TIMDDIER5_CMP3DE_Values<HRTIM_TIMD::TIMDDIER5, 18, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP2DE = HRTIM_TIMD_TIMDDIER5_CMP2DE_Values<HRTIM_TIMD::TIMDDIER5, 17, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP1DE = HRTIM_TIMD_TIMDDIER5_CMP1DE_Values<HRTIM_TIMD::TIMDDIER5, 16, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using DLYPRTIE = HRTIM_TIMD_TIMDDIER5_DLYPRTIE_Values<HRTIM_TIMD::TIMDDIER5, 14, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTIE = HRTIM_TIMD_TIMDDIER5_RSTIE_Values<HRTIM_TIMD::TIMDDIER5, 13, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTx2IE = HRTIM_TIMD_TIMDDIER5_RSTx2IE_Values<HRTIM_TIMD::TIMDDIER5, 12, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using SETx2IE = HRTIM_TIMD_TIMDDIER5_SETx2IE_Values<HRTIM_TIMD::TIMDDIER5, 11, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using RSTx1IE = HRTIM_TIMD_TIMDDIER5_RSTx1IE_Values<HRTIM_TIMD::TIMDDIER5, 10, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using SET1xIE = HRTIM_TIMD_TIMDDIER5_SET1xIE_Values<HRTIM_TIMD::TIMDDIER5, 9, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CPT2IE = HRTIM_TIMD_TIMDDIER5_CPT2IE_Values<HRTIM_TIMD::TIMDDIER5, 8, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CPT1IE = HRTIM_TIMD_TIMDDIER5_CPT1IE_Values<HRTIM_TIMD::TIMDDIER5, 7, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using UPDIE = HRTIM_TIMD_TIMDDIER5_UPDIE_Values<HRTIM_TIMD::TIMDDIER5, 6, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using REPIE = HRTIM_TIMD_TIMDDIER5_REPIE_Values<HRTIM_TIMD::TIMDDIER5, 4, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP4IE = HRTIM_TIMD_TIMDDIER5_CMP4IE_Values<HRTIM_TIMD::TIMDDIER5, 3, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP3IE = HRTIM_TIMD_TIMDDIER5_CMP3IE_Values<HRTIM_TIMD::TIMDDIER5, 2, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP2IE = HRTIM_TIMD_TIMDDIER5_CMP2IE_Values<HRTIM_TIMD::TIMDDIER5, 1, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using CMP1IE = HRTIM_TIMD_TIMDDIER5_CMP1IE_Values<HRTIM_TIMD::TIMDDIER5, 0, 1, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base> ;
    using FieldValues = HRTIM_TIMD_TIMDDIER5_CMP1IE_Values<HRTIM_TIMD::TIMDDIER5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMDDIER5Pack  = Register<0x4001760C, 32, ReadWriteMode, HRTIM_TIMDTIMDDIER5Base, T...> ;

  struct HRTIM_TIMDCNTDRBase {} ;

  struct CNTDR : public RegisterBase<0x40017610, 32, ReadWriteMode>
  {
    using CNTx = HRTIM_TIMD_CNTDR_CNTx_Values<HRTIM_TIMD::CNTDR, 0, 16, ReadWriteMode, HRTIM_TIMDCNTDRBase> ;
    using FieldValues = HRTIM_TIMD_CNTDR_CNTx_Values<HRTIM_TIMD::CNTDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CNTDRPack  = Register<0x40017610, 32, ReadWriteMode, HRTIM_TIMDCNTDRBase, T...> ;

  struct HRTIM_TIMDPERDRBase {} ;

  struct PERDR : public RegisterBase<0x40017614, 32, ReadWriteMode>
  {
    using PERx = HRTIM_TIMD_PERDR_PERx_Values<HRTIM_TIMD::PERDR, 0, 16, ReadWriteMode, HRTIM_TIMDPERDRBase> ;
    using FieldValues = HRTIM_TIMD_PERDR_PERx_Values<HRTIM_TIMD::PERDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using PERDRPack  = Register<0x40017614, 32, ReadWriteMode, HRTIM_TIMDPERDRBase, T...> ;

  struct HRTIM_TIMDREPDRBase {} ;

  struct REPDR : public RegisterBase<0x40017618, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMD_REPDR_REPx_Values<HRTIM_TIMD::REPDR, 0, 8, ReadWriteMode, HRTIM_TIMDREPDRBase> ;
    using FieldValues = HRTIM_TIMD_REPDR_REPx_Values<HRTIM_TIMD::REPDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using REPDRPack  = Register<0x40017618, 32, ReadWriteMode, HRTIM_TIMDREPDRBase, T...> ;

  struct HRTIM_TIMDCMP1DRBase {} ;

  struct CMP1DR : public RegisterBase<0x4001761C, 32, ReadWriteMode>
  {
    using CMP1x = HRTIM_TIMD_CMP1DR_CMP1x_Values<HRTIM_TIMD::CMP1DR, 0, 16, ReadWriteMode, HRTIM_TIMDCMP1DRBase> ;
    using FieldValues = HRTIM_TIMD_CMP1DR_CMP1x_Values<HRTIM_TIMD::CMP1DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1DRPack  = Register<0x4001761C, 32, ReadWriteMode, HRTIM_TIMDCMP1DRBase, T...> ;

  struct HRTIM_TIMDCMP1CDRBase {} ;

  struct CMP1CDR : public RegisterBase<0x40017620, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMD_CMP1CDR_REPx_Values<HRTIM_TIMD::CMP1CDR, 16, 8, ReadWriteMode, HRTIM_TIMDCMP1CDRBase> ;
    using CMP1x = HRTIM_TIMD_CMP1CDR_CMP1x_Values<HRTIM_TIMD::CMP1CDR, 0, 16, ReadWriteMode, HRTIM_TIMDCMP1CDRBase> ;
    using FieldValues = HRTIM_TIMD_CMP1CDR_CMP1x_Values<HRTIM_TIMD::CMP1CDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1CDRPack  = Register<0x40017620, 32, ReadWriteMode, HRTIM_TIMDCMP1CDRBase, T...> ;

  struct HRTIM_TIMDCMP2DRBase {} ;

  struct CMP2DR : public RegisterBase<0x40017624, 32, ReadWriteMode>
  {
    using CMP2x = HRTIM_TIMD_CMP2DR_CMP2x_Values<HRTIM_TIMD::CMP2DR, 0, 16, ReadWriteMode, HRTIM_TIMDCMP2DRBase> ;
    using FieldValues = HRTIM_TIMD_CMP2DR_CMP2x_Values<HRTIM_TIMD::CMP2DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP2DRPack  = Register<0x40017624, 32, ReadWriteMode, HRTIM_TIMDCMP2DRBase, T...> ;

  struct HRTIM_TIMDCMP3DRBase {} ;

  struct CMP3DR : public RegisterBase<0x40017628, 32, ReadWriteMode>
  {
    using CMP3x = HRTIM_TIMD_CMP3DR_CMP3x_Values<HRTIM_TIMD::CMP3DR, 0, 16, ReadWriteMode, HRTIM_TIMDCMP3DRBase> ;
    using FieldValues = HRTIM_TIMD_CMP3DR_CMP3x_Values<HRTIM_TIMD::CMP3DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP3DRPack  = Register<0x40017628, 32, ReadWriteMode, HRTIM_TIMDCMP3DRBase, T...> ;

  struct HRTIM_TIMDCMP4DRBase {} ;

  struct CMP4DR : public RegisterBase<0x4001762C, 32, ReadWriteMode>
  {
    using CMP4x = HRTIM_TIMD_CMP4DR_CMP4x_Values<HRTIM_TIMD::CMP4DR, 0, 16, ReadWriteMode, HRTIM_TIMDCMP4DRBase> ;
    using FieldValues = HRTIM_TIMD_CMP4DR_CMP4x_Values<HRTIM_TIMD::CMP4DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP4DRPack  = Register<0x4001762C, 32, ReadWriteMode, HRTIM_TIMDCMP4DRBase, T...> ;

  struct HRTIM_TIMDCPT1DRBase {} ;

  struct CPT1DR : public RegisterBase<0x40017630, 32, ReadMode>
  {
    using CPT1x = HRTIM_TIMD_CPT1DR_CPT1x_Values<HRTIM_TIMD::CPT1DR, 0, 16, ReadMode, HRTIM_TIMDCPT1DRBase> ;
    using FieldValues = HRTIM_TIMD_CPT1DR_CPT1x_Values<HRTIM_TIMD::CPT1DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1DRPack  = Register<0x40017630, 32, ReadMode, HRTIM_TIMDCPT1DRBase, T...> ;

  struct HRTIM_TIMDCPT2DRBase {} ;

  struct CPT2DR : public RegisterBase<0x40017634, 32, ReadMode>
  {
    using CPT2x = HRTIM_TIMD_CPT2DR_CPT2x_Values<HRTIM_TIMD::CPT2DR, 0, 16, ReadMode, HRTIM_TIMDCPT2DRBase> ;
    using FieldValues = HRTIM_TIMD_CPT2DR_CPT2x_Values<HRTIM_TIMD::CPT2DR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2DRPack  = Register<0x40017634, 32, ReadMode, HRTIM_TIMDCPT2DRBase, T...> ;

  struct HRTIM_TIMDDTDRBase {} ;

  struct DTDR : public RegisterBase<0x40017638, 32, ReadWriteMode>
  {
    using DTFLKx = HRTIM_TIMD_DTDR_DTFLKx_Values<HRTIM_TIMD::DTDR, 31, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTFSLKx = HRTIM_TIMD_DTDR_DTFSLKx_Values<HRTIM_TIMD::DTDR, 30, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using SDTFx = HRTIM_TIMD_DTDR_SDTFx_Values<HRTIM_TIMD::DTDR, 25, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTFx = HRTIM_TIMD_DTDR_DTFx_Values<HRTIM_TIMD::DTDR, 16, 9, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTRLKx = HRTIM_TIMD_DTDR_DTRLKx_Values<HRTIM_TIMD::DTDR, 15, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTRSLKx = HRTIM_TIMD_DTDR_DTRSLKx_Values<HRTIM_TIMD::DTDR, 14, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTPRSC = HRTIM_TIMD_DTDR_DTPRSC_Values<HRTIM_TIMD::DTDR, 10, 3, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using SDTRx = HRTIM_TIMD_DTDR_SDTRx_Values<HRTIM_TIMD::DTDR, 9, 1, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using DTRx = HRTIM_TIMD_DTDR_DTRx_Values<HRTIM_TIMD::DTDR, 0, 9, ReadWriteMode, HRTIM_TIMDDTDRBase> ;
    using FieldValues = HRTIM_TIMD_DTDR_DTRx_Values<HRTIM_TIMD::DTDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using DTDRPack  = Register<0x40017638, 32, ReadWriteMode, HRTIM_TIMDDTDRBase, T...> ;

  struct HRTIM_TIMDSETD1RBase {} ;

  struct SETD1R : public RegisterBase<0x4001763C, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMD_SETD1R_UPDATE_Values<HRTIM_TIMD::SETD1R, 31, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT10 = HRTIM_TIMD_SETD1R_EXTEVNT10_Values<HRTIM_TIMD::SETD1R, 30, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT9 = HRTIM_TIMD_SETD1R_EXTEVNT9_Values<HRTIM_TIMD::SETD1R, 29, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT8 = HRTIM_TIMD_SETD1R_EXTEVNT8_Values<HRTIM_TIMD::SETD1R, 28, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT7 = HRTIM_TIMD_SETD1R_EXTEVNT7_Values<HRTIM_TIMD::SETD1R, 27, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT6 = HRTIM_TIMD_SETD1R_EXTEVNT6_Values<HRTIM_TIMD::SETD1R, 26, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT5 = HRTIM_TIMD_SETD1R_EXTEVNT5_Values<HRTIM_TIMD::SETD1R, 25, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT4 = HRTIM_TIMD_SETD1R_EXTEVNT4_Values<HRTIM_TIMD::SETD1R, 24, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT3 = HRTIM_TIMD_SETD1R_EXTEVNT3_Values<HRTIM_TIMD::SETD1R, 23, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT2 = HRTIM_TIMD_SETD1R_EXTEVNT2_Values<HRTIM_TIMD::SETD1R, 22, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using EXTEVNT1 = HRTIM_TIMD_SETD1R_EXTEVNT1_Values<HRTIM_TIMD::SETD1R, 21, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT9 = HRTIM_TIMD_SETD1R_TIMEVNT9_Values<HRTIM_TIMD::SETD1R, 20, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT8 = HRTIM_TIMD_SETD1R_TIMEVNT8_Values<HRTIM_TIMD::SETD1R, 19, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT7 = HRTIM_TIMD_SETD1R_TIMEVNT7_Values<HRTIM_TIMD::SETD1R, 18, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT6 = HRTIM_TIMD_SETD1R_TIMEVNT6_Values<HRTIM_TIMD::SETD1R, 17, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT5 = HRTIM_TIMD_SETD1R_TIMEVNT5_Values<HRTIM_TIMD::SETD1R, 16, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT4 = HRTIM_TIMD_SETD1R_TIMEVNT4_Values<HRTIM_TIMD::SETD1R, 15, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT3 = HRTIM_TIMD_SETD1R_TIMEVNT3_Values<HRTIM_TIMD::SETD1R, 14, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT2 = HRTIM_TIMD_SETD1R_TIMEVNT2_Values<HRTIM_TIMD::SETD1R, 13, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using TIMEVNT1 = HRTIM_TIMD_SETD1R_TIMEVNT1_Values<HRTIM_TIMD::SETD1R, 12, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using MSTCMP4 = HRTIM_TIMD_SETD1R_MSTCMP4_Values<HRTIM_TIMD::SETD1R, 11, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using MSTCMP3 = HRTIM_TIMD_SETD1R_MSTCMP3_Values<HRTIM_TIMD::SETD1R, 10, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using MSTCMP2 = HRTIM_TIMD_SETD1R_MSTCMP2_Values<HRTIM_TIMD::SETD1R, 9, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using MSTCMP1 = HRTIM_TIMD_SETD1R_MSTCMP1_Values<HRTIM_TIMD::SETD1R, 8, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using MSTPER = HRTIM_TIMD_SETD1R_MSTPER_Values<HRTIM_TIMD::SETD1R, 7, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using CMP4 = HRTIM_TIMD_SETD1R_CMP4_Values<HRTIM_TIMD::SETD1R, 6, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using CMP3 = HRTIM_TIMD_SETD1R_CMP3_Values<HRTIM_TIMD::SETD1R, 5, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using CMP2 = HRTIM_TIMD_SETD1R_CMP2_Values<HRTIM_TIMD::SETD1R, 4, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using CMP1 = HRTIM_TIMD_SETD1R_CMP1_Values<HRTIM_TIMD::SETD1R, 3, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using PER = HRTIM_TIMD_SETD1R_PER_Values<HRTIM_TIMD::SETD1R, 2, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using RESYNC = HRTIM_TIMD_SETD1R_RESYNC_Values<HRTIM_TIMD::SETD1R, 1, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using SST = HRTIM_TIMD_SETD1R_SST_Values<HRTIM_TIMD::SETD1R, 0, 1, ReadWriteMode, HRTIM_TIMDSETD1RBase> ;
    using FieldValues = HRTIM_TIMD_SETD1R_SST_Values<HRTIM_TIMD::SETD1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETD1RPack  = Register<0x4001763C, 32, ReadWriteMode, HRTIM_TIMDSETD1RBase, T...> ;

  struct HRTIM_TIMDRSTD1RBase {} ;

  struct RSTD1R : public RegisterBase<0x40017640, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMD_RSTD1R_UPDATE_Values<HRTIM_TIMD::RSTD1R, 31, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT10 = HRTIM_TIMD_RSTD1R_EXTEVNT10_Values<HRTIM_TIMD::RSTD1R, 30, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT9 = HRTIM_TIMD_RSTD1R_EXTEVNT9_Values<HRTIM_TIMD::RSTD1R, 29, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT8 = HRTIM_TIMD_RSTD1R_EXTEVNT8_Values<HRTIM_TIMD::RSTD1R, 28, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT7 = HRTIM_TIMD_RSTD1R_EXTEVNT7_Values<HRTIM_TIMD::RSTD1R, 27, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT6 = HRTIM_TIMD_RSTD1R_EXTEVNT6_Values<HRTIM_TIMD::RSTD1R, 26, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT5 = HRTIM_TIMD_RSTD1R_EXTEVNT5_Values<HRTIM_TIMD::RSTD1R, 25, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT4 = HRTIM_TIMD_RSTD1R_EXTEVNT4_Values<HRTIM_TIMD::RSTD1R, 24, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT3 = HRTIM_TIMD_RSTD1R_EXTEVNT3_Values<HRTIM_TIMD::RSTD1R, 23, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT2 = HRTIM_TIMD_RSTD1R_EXTEVNT2_Values<HRTIM_TIMD::RSTD1R, 22, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using EXTEVNT1 = HRTIM_TIMD_RSTD1R_EXTEVNT1_Values<HRTIM_TIMD::RSTD1R, 21, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT9 = HRTIM_TIMD_RSTD1R_TIMEVNT9_Values<HRTIM_TIMD::RSTD1R, 20, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT8 = HRTIM_TIMD_RSTD1R_TIMEVNT8_Values<HRTIM_TIMD::RSTD1R, 19, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT7 = HRTIM_TIMD_RSTD1R_TIMEVNT7_Values<HRTIM_TIMD::RSTD1R, 18, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT6 = HRTIM_TIMD_RSTD1R_TIMEVNT6_Values<HRTIM_TIMD::RSTD1R, 17, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT5 = HRTIM_TIMD_RSTD1R_TIMEVNT5_Values<HRTIM_TIMD::RSTD1R, 16, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT4 = HRTIM_TIMD_RSTD1R_TIMEVNT4_Values<HRTIM_TIMD::RSTD1R, 15, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT3 = HRTIM_TIMD_RSTD1R_TIMEVNT3_Values<HRTIM_TIMD::RSTD1R, 14, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT2 = HRTIM_TIMD_RSTD1R_TIMEVNT2_Values<HRTIM_TIMD::RSTD1R, 13, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using TIMEVNT1 = HRTIM_TIMD_RSTD1R_TIMEVNT1_Values<HRTIM_TIMD::RSTD1R, 12, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using MSTCMP4 = HRTIM_TIMD_RSTD1R_MSTCMP4_Values<HRTIM_TIMD::RSTD1R, 11, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using MSTCMP3 = HRTIM_TIMD_RSTD1R_MSTCMP3_Values<HRTIM_TIMD::RSTD1R, 10, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using MSTCMP2 = HRTIM_TIMD_RSTD1R_MSTCMP2_Values<HRTIM_TIMD::RSTD1R, 9, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using MSTCMP1 = HRTIM_TIMD_RSTD1R_MSTCMP1_Values<HRTIM_TIMD::RSTD1R, 8, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using MSTPER = HRTIM_TIMD_RSTD1R_MSTPER_Values<HRTIM_TIMD::RSTD1R, 7, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using CMP4 = HRTIM_TIMD_RSTD1R_CMP4_Values<HRTIM_TIMD::RSTD1R, 6, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using CMP3 = HRTIM_TIMD_RSTD1R_CMP3_Values<HRTIM_TIMD::RSTD1R, 5, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using CMP2 = HRTIM_TIMD_RSTD1R_CMP2_Values<HRTIM_TIMD::RSTD1R, 4, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using CMP1 = HRTIM_TIMD_RSTD1R_CMP1_Values<HRTIM_TIMD::RSTD1R, 3, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using PER = HRTIM_TIMD_RSTD1R_PER_Values<HRTIM_TIMD::RSTD1R, 2, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using RESYNC = HRTIM_TIMD_RSTD1R_RESYNC_Values<HRTIM_TIMD::RSTD1R, 1, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using SRT = HRTIM_TIMD_RSTD1R_SRT_Values<HRTIM_TIMD::RSTD1R, 0, 1, ReadWriteMode, HRTIM_TIMDRSTD1RBase> ;
    using FieldValues = HRTIM_TIMD_RSTD1R_SRT_Values<HRTIM_TIMD::RSTD1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTD1RPack  = Register<0x40017640, 32, ReadWriteMode, HRTIM_TIMDRSTD1RBase, T...> ;

  struct HRTIM_TIMDSETD2RBase {} ;

  struct SETD2R : public RegisterBase<0x40017644, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMD_SETD2R_UPDATE_Values<HRTIM_TIMD::SETD2R, 31, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT10 = HRTIM_TIMD_SETD2R_EXTEVNT10_Values<HRTIM_TIMD::SETD2R, 30, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT9 = HRTIM_TIMD_SETD2R_EXTEVNT9_Values<HRTIM_TIMD::SETD2R, 29, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT8 = HRTIM_TIMD_SETD2R_EXTEVNT8_Values<HRTIM_TIMD::SETD2R, 28, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT7 = HRTIM_TIMD_SETD2R_EXTEVNT7_Values<HRTIM_TIMD::SETD2R, 27, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT6 = HRTIM_TIMD_SETD2R_EXTEVNT6_Values<HRTIM_TIMD::SETD2R, 26, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT5 = HRTIM_TIMD_SETD2R_EXTEVNT5_Values<HRTIM_TIMD::SETD2R, 25, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT4 = HRTIM_TIMD_SETD2R_EXTEVNT4_Values<HRTIM_TIMD::SETD2R, 24, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT3 = HRTIM_TIMD_SETD2R_EXTEVNT3_Values<HRTIM_TIMD::SETD2R, 23, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT2 = HRTIM_TIMD_SETD2R_EXTEVNT2_Values<HRTIM_TIMD::SETD2R, 22, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using EXTEVNT1 = HRTIM_TIMD_SETD2R_EXTEVNT1_Values<HRTIM_TIMD::SETD2R, 21, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT9 = HRTIM_TIMD_SETD2R_TIMEVNT9_Values<HRTIM_TIMD::SETD2R, 20, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT8 = HRTIM_TIMD_SETD2R_TIMEVNT8_Values<HRTIM_TIMD::SETD2R, 19, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT7 = HRTIM_TIMD_SETD2R_TIMEVNT7_Values<HRTIM_TIMD::SETD2R, 18, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT6 = HRTIM_TIMD_SETD2R_TIMEVNT6_Values<HRTIM_TIMD::SETD2R, 17, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT5 = HRTIM_TIMD_SETD2R_TIMEVNT5_Values<HRTIM_TIMD::SETD2R, 16, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT4 = HRTIM_TIMD_SETD2R_TIMEVNT4_Values<HRTIM_TIMD::SETD2R, 15, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT3 = HRTIM_TIMD_SETD2R_TIMEVNT3_Values<HRTIM_TIMD::SETD2R, 14, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT2 = HRTIM_TIMD_SETD2R_TIMEVNT2_Values<HRTIM_TIMD::SETD2R, 13, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using TIMEVNT1 = HRTIM_TIMD_SETD2R_TIMEVNT1_Values<HRTIM_TIMD::SETD2R, 12, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using MSTCMP4 = HRTIM_TIMD_SETD2R_MSTCMP4_Values<HRTIM_TIMD::SETD2R, 11, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using MSTCMP3 = HRTIM_TIMD_SETD2R_MSTCMP3_Values<HRTIM_TIMD::SETD2R, 10, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using MSTCMP2 = HRTIM_TIMD_SETD2R_MSTCMP2_Values<HRTIM_TIMD::SETD2R, 9, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using MSTCMP1 = HRTIM_TIMD_SETD2R_MSTCMP1_Values<HRTIM_TIMD::SETD2R, 8, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using MSTPER = HRTIM_TIMD_SETD2R_MSTPER_Values<HRTIM_TIMD::SETD2R, 7, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using CMP4 = HRTIM_TIMD_SETD2R_CMP4_Values<HRTIM_TIMD::SETD2R, 6, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using CMP3 = HRTIM_TIMD_SETD2R_CMP3_Values<HRTIM_TIMD::SETD2R, 5, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using CMP2 = HRTIM_TIMD_SETD2R_CMP2_Values<HRTIM_TIMD::SETD2R, 4, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using CMP1 = HRTIM_TIMD_SETD2R_CMP1_Values<HRTIM_TIMD::SETD2R, 3, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using PER = HRTIM_TIMD_SETD2R_PER_Values<HRTIM_TIMD::SETD2R, 2, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using RESYNC = HRTIM_TIMD_SETD2R_RESYNC_Values<HRTIM_TIMD::SETD2R, 1, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using SST = HRTIM_TIMD_SETD2R_SST_Values<HRTIM_TIMD::SETD2R, 0, 1, ReadWriteMode, HRTIM_TIMDSETD2RBase> ;
    using FieldValues = HRTIM_TIMD_SETD2R_SST_Values<HRTIM_TIMD::SETD2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETD2RPack  = Register<0x40017644, 32, ReadWriteMode, HRTIM_TIMDSETD2RBase, T...> ;

  struct HRTIM_TIMDRSTD2RBase {} ;

  struct RSTD2R : public RegisterBase<0x40017648, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMD_RSTD2R_UPDATE_Values<HRTIM_TIMD::RSTD2R, 31, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT10 = HRTIM_TIMD_RSTD2R_EXTEVNT10_Values<HRTIM_TIMD::RSTD2R, 30, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT9 = HRTIM_TIMD_RSTD2R_EXTEVNT9_Values<HRTIM_TIMD::RSTD2R, 29, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT8 = HRTIM_TIMD_RSTD2R_EXTEVNT8_Values<HRTIM_TIMD::RSTD2R, 28, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT7 = HRTIM_TIMD_RSTD2R_EXTEVNT7_Values<HRTIM_TIMD::RSTD2R, 27, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT6 = HRTIM_TIMD_RSTD2R_EXTEVNT6_Values<HRTIM_TIMD::RSTD2R, 26, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT5 = HRTIM_TIMD_RSTD2R_EXTEVNT5_Values<HRTIM_TIMD::RSTD2R, 25, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT4 = HRTIM_TIMD_RSTD2R_EXTEVNT4_Values<HRTIM_TIMD::RSTD2R, 24, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT3 = HRTIM_TIMD_RSTD2R_EXTEVNT3_Values<HRTIM_TIMD::RSTD2R, 23, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT2 = HRTIM_TIMD_RSTD2R_EXTEVNT2_Values<HRTIM_TIMD::RSTD2R, 22, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using EXTEVNT1 = HRTIM_TIMD_RSTD2R_EXTEVNT1_Values<HRTIM_TIMD::RSTD2R, 21, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT9 = HRTIM_TIMD_RSTD2R_TIMEVNT9_Values<HRTIM_TIMD::RSTD2R, 20, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT8 = HRTIM_TIMD_RSTD2R_TIMEVNT8_Values<HRTIM_TIMD::RSTD2R, 19, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT7 = HRTIM_TIMD_RSTD2R_TIMEVNT7_Values<HRTIM_TIMD::RSTD2R, 18, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT6 = HRTIM_TIMD_RSTD2R_TIMEVNT6_Values<HRTIM_TIMD::RSTD2R, 17, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT5 = HRTIM_TIMD_RSTD2R_TIMEVNT5_Values<HRTIM_TIMD::RSTD2R, 16, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT4 = HRTIM_TIMD_RSTD2R_TIMEVNT4_Values<HRTIM_TIMD::RSTD2R, 15, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT3 = HRTIM_TIMD_RSTD2R_TIMEVNT3_Values<HRTIM_TIMD::RSTD2R, 14, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT2 = HRTIM_TIMD_RSTD2R_TIMEVNT2_Values<HRTIM_TIMD::RSTD2R, 13, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using TIMEVNT1 = HRTIM_TIMD_RSTD2R_TIMEVNT1_Values<HRTIM_TIMD::RSTD2R, 12, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using MSTCMP4 = HRTIM_TIMD_RSTD2R_MSTCMP4_Values<HRTIM_TIMD::RSTD2R, 11, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using MSTCMP3 = HRTIM_TIMD_RSTD2R_MSTCMP3_Values<HRTIM_TIMD::RSTD2R, 10, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using MSTCMP2 = HRTIM_TIMD_RSTD2R_MSTCMP2_Values<HRTIM_TIMD::RSTD2R, 9, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using MSTCMP1 = HRTIM_TIMD_RSTD2R_MSTCMP1_Values<HRTIM_TIMD::RSTD2R, 8, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using MSTPER = HRTIM_TIMD_RSTD2R_MSTPER_Values<HRTIM_TIMD::RSTD2R, 7, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using CMP4 = HRTIM_TIMD_RSTD2R_CMP4_Values<HRTIM_TIMD::RSTD2R, 6, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using CMP3 = HRTIM_TIMD_RSTD2R_CMP3_Values<HRTIM_TIMD::RSTD2R, 5, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using CMP2 = HRTIM_TIMD_RSTD2R_CMP2_Values<HRTIM_TIMD::RSTD2R, 4, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using CMP1 = HRTIM_TIMD_RSTD2R_CMP1_Values<HRTIM_TIMD::RSTD2R, 3, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using PER = HRTIM_TIMD_RSTD2R_PER_Values<HRTIM_TIMD::RSTD2R, 2, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using RESYNC = HRTIM_TIMD_RSTD2R_RESYNC_Values<HRTIM_TIMD::RSTD2R, 1, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using SRT = HRTIM_TIMD_RSTD2R_SRT_Values<HRTIM_TIMD::RSTD2R, 0, 1, ReadWriteMode, HRTIM_TIMDRSTD2RBase> ;
    using FieldValues = HRTIM_TIMD_RSTD2R_SRT_Values<HRTIM_TIMD::RSTD2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTD2RPack  = Register<0x40017648, 32, ReadWriteMode, HRTIM_TIMDRSTD2RBase, T...> ;

  struct HRTIM_TIMDEEFDR1Base {} ;

  struct EEFDR1 : public RegisterBase<0x4001764C, 32, ReadWriteMode>
  {
    using EE5FLTR = HRTIM_TIMD_EEFDR1_EE5FLTR_Values<HRTIM_TIMD::EEFDR1, 25, 4, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE5LTCH = HRTIM_TIMD_EEFDR1_EE5LTCH_Values<HRTIM_TIMD::EEFDR1, 24, 1, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE4FLTR = HRTIM_TIMD_EEFDR1_EE4FLTR_Values<HRTIM_TIMD::EEFDR1, 19, 4, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE4LTCH = HRTIM_TIMD_EEFDR1_EE4LTCH_Values<HRTIM_TIMD::EEFDR1, 18, 1, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE3FLTR = HRTIM_TIMD_EEFDR1_EE3FLTR_Values<HRTIM_TIMD::EEFDR1, 13, 4, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE3LTCH = HRTIM_TIMD_EEFDR1_EE3LTCH_Values<HRTIM_TIMD::EEFDR1, 12, 1, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE2FLTR = HRTIM_TIMD_EEFDR1_EE2FLTR_Values<HRTIM_TIMD::EEFDR1, 7, 4, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE2LTCH = HRTIM_TIMD_EEFDR1_EE2LTCH_Values<HRTIM_TIMD::EEFDR1, 6, 1, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE1FLTR = HRTIM_TIMD_EEFDR1_EE1FLTR_Values<HRTIM_TIMD::EEFDR1, 1, 4, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using EE1LTCH = HRTIM_TIMD_EEFDR1_EE1LTCH_Values<HRTIM_TIMD::EEFDR1, 0, 1, ReadWriteMode, HRTIM_TIMDEEFDR1Base> ;
    using FieldValues = HRTIM_TIMD_EEFDR1_EE1LTCH_Values<HRTIM_TIMD::EEFDR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFDR1Pack  = Register<0x4001764C, 32, ReadWriteMode, HRTIM_TIMDEEFDR1Base, T...> ;

  struct HRTIM_TIMDEEFDR2Base {} ;

  struct EEFDR2 : public RegisterBase<0x40017650, 32, ReadWriteMode>
  {
    using EE10FLTR = HRTIM_TIMD_EEFDR2_EE10FLTR_Values<HRTIM_TIMD::EEFDR2, 25, 4, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE10LTCH = HRTIM_TIMD_EEFDR2_EE10LTCH_Values<HRTIM_TIMD::EEFDR2, 24, 1, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE9FLTR = HRTIM_TIMD_EEFDR2_EE9FLTR_Values<HRTIM_TIMD::EEFDR2, 19, 4, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE9LTCH = HRTIM_TIMD_EEFDR2_EE9LTCH_Values<HRTIM_TIMD::EEFDR2, 18, 1, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE8FLTR = HRTIM_TIMD_EEFDR2_EE8FLTR_Values<HRTIM_TIMD::EEFDR2, 13, 4, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE8LTCH = HRTIM_TIMD_EEFDR2_EE8LTCH_Values<HRTIM_TIMD::EEFDR2, 12, 1, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE7FLTR = HRTIM_TIMD_EEFDR2_EE7FLTR_Values<HRTIM_TIMD::EEFDR2, 7, 4, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE7LTCH = HRTIM_TIMD_EEFDR2_EE7LTCH_Values<HRTIM_TIMD::EEFDR2, 6, 1, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE6FLTR = HRTIM_TIMD_EEFDR2_EE6FLTR_Values<HRTIM_TIMD::EEFDR2, 1, 4, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using EE6LTCH = HRTIM_TIMD_EEFDR2_EE6LTCH_Values<HRTIM_TIMD::EEFDR2, 0, 1, ReadWriteMode, HRTIM_TIMDEEFDR2Base> ;
    using FieldValues = HRTIM_TIMD_EEFDR2_EE6LTCH_Values<HRTIM_TIMD::EEFDR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFDR2Pack  = Register<0x40017650, 32, ReadWriteMode, HRTIM_TIMDEEFDR2Base, T...> ;

  struct HRTIM_TIMDRSTDRBase {} ;

  struct RSTDR : public RegisterBase<0x40017654, 32, ReadWriteMode>
  {
    using TIMECMP4 = HRTIM_TIMD_RSTDR_TIMECMP4_Values<HRTIM_TIMD::RSTDR, 30, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMECMP2 = HRTIM_TIMD_RSTDR_TIMECMP2_Values<HRTIM_TIMD::RSTDR, 29, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMECMP1 = HRTIM_TIMD_RSTDR_TIMECMP1_Values<HRTIM_TIMD::RSTDR, 28, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMCCMP4 = HRTIM_TIMD_RSTDR_TIMCCMP4_Values<HRTIM_TIMD::RSTDR, 27, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMCCMP2 = HRTIM_TIMD_RSTDR_TIMCCMP2_Values<HRTIM_TIMD::RSTDR, 26, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMCCMP1 = HRTIM_TIMD_RSTDR_TIMCCMP1_Values<HRTIM_TIMD::RSTDR, 25, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMBCMP4 = HRTIM_TIMD_RSTDR_TIMBCMP4_Values<HRTIM_TIMD::RSTDR, 24, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMBCMP2 = HRTIM_TIMD_RSTDR_TIMBCMP2_Values<HRTIM_TIMD::RSTDR, 23, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMBCMP1 = HRTIM_TIMD_RSTDR_TIMBCMP1_Values<HRTIM_TIMD::RSTDR, 22, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMACMP4 = HRTIM_TIMD_RSTDR_TIMACMP4_Values<HRTIM_TIMD::RSTDR, 21, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMACMP2 = HRTIM_TIMD_RSTDR_TIMACMP2_Values<HRTIM_TIMD::RSTDR, 20, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using TIMACMP1 = HRTIM_TIMD_RSTDR_TIMACMP1_Values<HRTIM_TIMD::RSTDR, 19, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT10 = HRTIM_TIMD_RSTDR_EXTEVNT10_Values<HRTIM_TIMD::RSTDR, 18, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT9 = HRTIM_TIMD_RSTDR_EXTEVNT9_Values<HRTIM_TIMD::RSTDR, 17, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT8 = HRTIM_TIMD_RSTDR_EXTEVNT8_Values<HRTIM_TIMD::RSTDR, 16, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT7 = HRTIM_TIMD_RSTDR_EXTEVNT7_Values<HRTIM_TIMD::RSTDR, 15, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT6 = HRTIM_TIMD_RSTDR_EXTEVNT6_Values<HRTIM_TIMD::RSTDR, 14, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT5 = HRTIM_TIMD_RSTDR_EXTEVNT5_Values<HRTIM_TIMD::RSTDR, 13, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT4 = HRTIM_TIMD_RSTDR_EXTEVNT4_Values<HRTIM_TIMD::RSTDR, 12, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT3 = HRTIM_TIMD_RSTDR_EXTEVNT3_Values<HRTIM_TIMD::RSTDR, 11, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT2 = HRTIM_TIMD_RSTDR_EXTEVNT2_Values<HRTIM_TIMD::RSTDR, 10, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using EXTEVNT1 = HRTIM_TIMD_RSTDR_EXTEVNT1_Values<HRTIM_TIMD::RSTDR, 9, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using MSTCMP4 = HRTIM_TIMD_RSTDR_MSTCMP4_Values<HRTIM_TIMD::RSTDR, 8, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using MSTCMP3 = HRTIM_TIMD_RSTDR_MSTCMP3_Values<HRTIM_TIMD::RSTDR, 7, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using MSTCMP2 = HRTIM_TIMD_RSTDR_MSTCMP2_Values<HRTIM_TIMD::RSTDR, 6, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using MSTCMP1 = HRTIM_TIMD_RSTDR_MSTCMP1_Values<HRTIM_TIMD::RSTDR, 5, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using MSTPER = HRTIM_TIMD_RSTDR_MSTPER_Values<HRTIM_TIMD::RSTDR, 4, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using CMP4 = HRTIM_TIMD_RSTDR_CMP4_Values<HRTIM_TIMD::RSTDR, 3, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using CMP2 = HRTIM_TIMD_RSTDR_CMP2_Values<HRTIM_TIMD::RSTDR, 2, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using UPDT = HRTIM_TIMD_RSTDR_UPDT_Values<HRTIM_TIMD::RSTDR, 1, 1, ReadWriteMode, HRTIM_TIMDRSTDRBase> ;
    using FieldValues = HRTIM_TIMD_RSTDR_UPDT_Values<HRTIM_TIMD::RSTDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTDRPack  = Register<0x40017654, 32, ReadWriteMode, HRTIM_TIMDRSTDRBase, T...> ;

  struct HRTIM_TIMDCHPDRBase {} ;

  struct CHPDR : public RegisterBase<0x40017658, 32, ReadWriteMode>
  {
    using STRTPW = HRTIM_TIMD_CHPDR_STRTPW_Values<HRTIM_TIMD::CHPDR, 7, 4, ReadWriteMode, HRTIM_TIMDCHPDRBase> ;
    using CHPDTY = HRTIM_TIMD_CHPDR_CHPDTY_Values<HRTIM_TIMD::CHPDR, 4, 3, ReadWriteMode, HRTIM_TIMDCHPDRBase> ;
    using CHPFRQ = HRTIM_TIMD_CHPDR_CHPFRQ_Values<HRTIM_TIMD::CHPDR, 0, 4, ReadWriteMode, HRTIM_TIMDCHPDRBase> ;
    using FieldValues = HRTIM_TIMD_CHPDR_CHPFRQ_Values<HRTIM_TIMD::CHPDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CHPDRPack  = Register<0x40017658, 32, ReadWriteMode, HRTIM_TIMDCHPDRBase, T...> ;

  struct HRTIM_TIMDCPT1DCRBase {} ;

  struct CPT1DCR : public RegisterBase<0x4001765C, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMD_CPT1DCR_TECMP2_Values<HRTIM_TIMD::CPT1DCR, 31, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TECMP1 = HRTIM_TIMD_CPT1DCR_TECMP1_Values<HRTIM_TIMD::CPT1DCR, 30, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TE1RST = HRTIM_TIMD_CPT1DCR_TE1RST_Values<HRTIM_TIMD::CPT1DCR, 29, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TE1SET = HRTIM_TIMD_CPT1DCR_TE1SET_Values<HRTIM_TIMD::CPT1DCR, 28, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TCCMP2 = HRTIM_TIMD_CPT1DCR_TCCMP2_Values<HRTIM_TIMD::CPT1DCR, 23, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TCCMP1 = HRTIM_TIMD_CPT1DCR_TCCMP1_Values<HRTIM_TIMD::CPT1DCR, 22, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TC1RST = HRTIM_TIMD_CPT1DCR_TC1RST_Values<HRTIM_TIMD::CPT1DCR, 21, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TC1SET = HRTIM_TIMD_CPT1DCR_TC1SET_Values<HRTIM_TIMD::CPT1DCR, 20, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TBCMP2 = HRTIM_TIMD_CPT1DCR_TBCMP2_Values<HRTIM_TIMD::CPT1DCR, 19, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TBCMP1 = HRTIM_TIMD_CPT1DCR_TBCMP1_Values<HRTIM_TIMD::CPT1DCR, 18, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TB1RST = HRTIM_TIMD_CPT1DCR_TB1RST_Values<HRTIM_TIMD::CPT1DCR, 17, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TB1SET = HRTIM_TIMD_CPT1DCR_TB1SET_Values<HRTIM_TIMD::CPT1DCR, 16, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TACMP2 = HRTIM_TIMD_CPT1DCR_TACMP2_Values<HRTIM_TIMD::CPT1DCR, 15, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TACMP1 = HRTIM_TIMD_CPT1DCR_TACMP1_Values<HRTIM_TIMD::CPT1DCR, 14, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TA1RST = HRTIM_TIMD_CPT1DCR_TA1RST_Values<HRTIM_TIMD::CPT1DCR, 13, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using TA1SET = HRTIM_TIMD_CPT1DCR_TA1SET_Values<HRTIM_TIMD::CPT1DCR, 12, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV10CPT = HRTIM_TIMD_CPT1DCR_EXEV10CPT_Values<HRTIM_TIMD::CPT1DCR, 11, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV9CPT = HRTIM_TIMD_CPT1DCR_EXEV9CPT_Values<HRTIM_TIMD::CPT1DCR, 10, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV8CPT = HRTIM_TIMD_CPT1DCR_EXEV8CPT_Values<HRTIM_TIMD::CPT1DCR, 9, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV7CPT = HRTIM_TIMD_CPT1DCR_EXEV7CPT_Values<HRTIM_TIMD::CPT1DCR, 8, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV6CPT = HRTIM_TIMD_CPT1DCR_EXEV6CPT_Values<HRTIM_TIMD::CPT1DCR, 7, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV5CPT = HRTIM_TIMD_CPT1DCR_EXEV5CPT_Values<HRTIM_TIMD::CPT1DCR, 6, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV4CPT = HRTIM_TIMD_CPT1DCR_EXEV4CPT_Values<HRTIM_TIMD::CPT1DCR, 5, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV3CPT = HRTIM_TIMD_CPT1DCR_EXEV3CPT_Values<HRTIM_TIMD::CPT1DCR, 4, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV2CPT = HRTIM_TIMD_CPT1DCR_EXEV2CPT_Values<HRTIM_TIMD::CPT1DCR, 3, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using EXEV1CPT = HRTIM_TIMD_CPT1DCR_EXEV1CPT_Values<HRTIM_TIMD::CPT1DCR, 2, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using UDPCPT = HRTIM_TIMD_CPT1DCR_UDPCPT_Values<HRTIM_TIMD::CPT1DCR, 1, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using SWCPT = HRTIM_TIMD_CPT1DCR_SWCPT_Values<HRTIM_TIMD::CPT1DCR, 0, 1, ReadWriteMode, HRTIM_TIMDCPT1DCRBase> ;
    using FieldValues = HRTIM_TIMD_CPT1DCR_SWCPT_Values<HRTIM_TIMD::CPT1DCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1DCRPack  = Register<0x4001765C, 32, ReadWriteMode, HRTIM_TIMDCPT1DCRBase, T...> ;

  struct HRTIM_TIMDCPT2DCRBase {} ;

  struct CPT2DCR : public RegisterBase<0x40017660, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMD_CPT2DCR_TECMP2_Values<HRTIM_TIMD::CPT2DCR, 31, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TECMP1 = HRTIM_TIMD_CPT2DCR_TECMP1_Values<HRTIM_TIMD::CPT2DCR, 30, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TE1RST = HRTIM_TIMD_CPT2DCR_TE1RST_Values<HRTIM_TIMD::CPT2DCR, 29, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TE1SET = HRTIM_TIMD_CPT2DCR_TE1SET_Values<HRTIM_TIMD::CPT2DCR, 28, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TCCMP2 = HRTIM_TIMD_CPT2DCR_TCCMP2_Values<HRTIM_TIMD::CPT2DCR, 23, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TCCMP1 = HRTIM_TIMD_CPT2DCR_TCCMP1_Values<HRTIM_TIMD::CPT2DCR, 22, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TC1RST = HRTIM_TIMD_CPT2DCR_TC1RST_Values<HRTIM_TIMD::CPT2DCR, 21, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TC1SET = HRTIM_TIMD_CPT2DCR_TC1SET_Values<HRTIM_TIMD::CPT2DCR, 20, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TBCMP2 = HRTIM_TIMD_CPT2DCR_TBCMP2_Values<HRTIM_TIMD::CPT2DCR, 19, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TBCMP1 = HRTIM_TIMD_CPT2DCR_TBCMP1_Values<HRTIM_TIMD::CPT2DCR, 18, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TB1RST = HRTIM_TIMD_CPT2DCR_TB1RST_Values<HRTIM_TIMD::CPT2DCR, 17, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TB1SET = HRTIM_TIMD_CPT2DCR_TB1SET_Values<HRTIM_TIMD::CPT2DCR, 16, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TACMP2 = HRTIM_TIMD_CPT2DCR_TACMP2_Values<HRTIM_TIMD::CPT2DCR, 15, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TACMP1 = HRTIM_TIMD_CPT2DCR_TACMP1_Values<HRTIM_TIMD::CPT2DCR, 14, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TA1RST = HRTIM_TIMD_CPT2DCR_TA1RST_Values<HRTIM_TIMD::CPT2DCR, 13, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using TA1SET = HRTIM_TIMD_CPT2DCR_TA1SET_Values<HRTIM_TIMD::CPT2DCR, 12, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV10CPT = HRTIM_TIMD_CPT2DCR_EXEV10CPT_Values<HRTIM_TIMD::CPT2DCR, 11, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV9CPT = HRTIM_TIMD_CPT2DCR_EXEV9CPT_Values<HRTIM_TIMD::CPT2DCR, 10, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV8CPT = HRTIM_TIMD_CPT2DCR_EXEV8CPT_Values<HRTIM_TIMD::CPT2DCR, 9, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV7CPT = HRTIM_TIMD_CPT2DCR_EXEV7CPT_Values<HRTIM_TIMD::CPT2DCR, 8, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV6CPT = HRTIM_TIMD_CPT2DCR_EXEV6CPT_Values<HRTIM_TIMD::CPT2DCR, 7, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV5CPT = HRTIM_TIMD_CPT2DCR_EXEV5CPT_Values<HRTIM_TIMD::CPT2DCR, 6, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV4CPT = HRTIM_TIMD_CPT2DCR_EXEV4CPT_Values<HRTIM_TIMD::CPT2DCR, 5, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV3CPT = HRTIM_TIMD_CPT2DCR_EXEV3CPT_Values<HRTIM_TIMD::CPT2DCR, 4, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV2CPT = HRTIM_TIMD_CPT2DCR_EXEV2CPT_Values<HRTIM_TIMD::CPT2DCR, 3, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using EXEV1CPT = HRTIM_TIMD_CPT2DCR_EXEV1CPT_Values<HRTIM_TIMD::CPT2DCR, 2, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using UDPCPT = HRTIM_TIMD_CPT2DCR_UDPCPT_Values<HRTIM_TIMD::CPT2DCR, 1, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using SWCPT = HRTIM_TIMD_CPT2DCR_SWCPT_Values<HRTIM_TIMD::CPT2DCR, 0, 1, ReadWriteMode, HRTIM_TIMDCPT2DCRBase> ;
    using FieldValues = HRTIM_TIMD_CPT2DCR_SWCPT_Values<HRTIM_TIMD::CPT2DCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2DCRPack  = Register<0x40017660, 32, ReadWriteMode, HRTIM_TIMDCPT2DCRBase, T...> ;

  struct HRTIM_TIMDOUTDRBase {} ;

  struct OUTDR : public RegisterBase<0x40017664, 32, ReadWriteMode>
  {
    using DIDL2 = HRTIM_TIMD_OUTDR_DIDL2_Values<HRTIM_TIMD::OUTDR, 23, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using CHP2 = HRTIM_TIMD_OUTDR_CHP2_Values<HRTIM_TIMD::OUTDR, 22, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using FAULT2 = HRTIM_TIMD_OUTDR_FAULT2_Values<HRTIM_TIMD::OUTDR, 20, 2, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using IDLES2 = HRTIM_TIMD_OUTDR_IDLES2_Values<HRTIM_TIMD::OUTDR, 19, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using IDLEM2 = HRTIM_TIMD_OUTDR_IDLEM2_Values<HRTIM_TIMD::OUTDR, 18, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using POL2 = HRTIM_TIMD_OUTDR_POL2_Values<HRTIM_TIMD::OUTDR, 17, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using DLYPRT = HRTIM_TIMD_OUTDR_DLYPRT_Values<HRTIM_TIMD::OUTDR, 10, 3, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using DLYPRTEN = HRTIM_TIMD_OUTDR_DLYPRTEN_Values<HRTIM_TIMD::OUTDR, 9, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using DTEN = HRTIM_TIMD_OUTDR_DTEN_Values<HRTIM_TIMD::OUTDR, 8, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using DIDL1 = HRTIM_TIMD_OUTDR_DIDL1_Values<HRTIM_TIMD::OUTDR, 7, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using CHP1 = HRTIM_TIMD_OUTDR_CHP1_Values<HRTIM_TIMD::OUTDR, 6, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using FAULT1 = HRTIM_TIMD_OUTDR_FAULT1_Values<HRTIM_TIMD::OUTDR, 4, 2, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using IDLES1 = HRTIM_TIMD_OUTDR_IDLES1_Values<HRTIM_TIMD::OUTDR, 3, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using IDLEM1 = HRTIM_TIMD_OUTDR_IDLEM1_Values<HRTIM_TIMD::OUTDR, 2, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using POL1 = HRTIM_TIMD_OUTDR_POL1_Values<HRTIM_TIMD::OUTDR, 1, 1, ReadWriteMode, HRTIM_TIMDOUTDRBase> ;
    using FieldValues = HRTIM_TIMD_OUTDR_POL1_Values<HRTIM_TIMD::OUTDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OUTDRPack  = Register<0x40017664, 32, ReadWriteMode, HRTIM_TIMDOUTDRBase, T...> ;

  struct HRTIM_TIMDFLTDRBase {} ;

  struct FLTDR : public RegisterBase<0x40017668, 32, ReadWriteMode>
  {
    using FLTLCK = HRTIM_TIMD_FLTDR_FLTLCK_Values<HRTIM_TIMD::FLTDR, 31, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FLT5EN = HRTIM_TIMD_FLTDR_FLT5EN_Values<HRTIM_TIMD::FLTDR, 4, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FLT4EN = HRTIM_TIMD_FLTDR_FLT4EN_Values<HRTIM_TIMD::FLTDR, 3, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FLT3EN = HRTIM_TIMD_FLTDR_FLT3EN_Values<HRTIM_TIMD::FLTDR, 2, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FLT2EN = HRTIM_TIMD_FLTDR_FLT2EN_Values<HRTIM_TIMD::FLTDR, 1, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FLT1EN = HRTIM_TIMD_FLTDR_FLT1EN_Values<HRTIM_TIMD::FLTDR, 0, 1, ReadWriteMode, HRTIM_TIMDFLTDRBase> ;
    using FieldValues = HRTIM_TIMD_FLTDR_FLT1EN_Values<HRTIM_TIMD::FLTDR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using FLTDRPack  = Register<0x40017668, 32, ReadWriteMode, HRTIM_TIMDFLTDRBase, T...> ;

} ;

#endif //#if !defined(HRTIMTIMDREGISTERS_HPP)
