/*******************************************************************************
* Filename      : hrtimtimbregisters.hpp
*
* Details       : High Resolution Timer: TIMB. This header file is
*                 auto-generated for STM32H745_CM7 device.
*
*
*******************************************************************************/

#if !defined(HRTIMTIMBREGISTERS_HPP)
#define HRTIMTIMBREGISTERS_HPP

#include "hrtimtimbfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct HRTIM_TIMB
{
  struct HRTIM_TIMBTIMBCRBase {} ;

  struct TIMBCR : public RegisterBase<0x40017500, 32, ReadWriteMode>
  {
    using UPDGAT = HRTIM_TIMB_TIMBCR_UPDGAT_Values<HRTIM_TIMB::TIMBCR, 28, 4, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using PREEN = HRTIM_TIMB_TIMBCR_PREEN_Values<HRTIM_TIMB::TIMBCR, 27, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using DACSYNC = HRTIM_TIMB_TIMBCR_DACSYNC_Values<HRTIM_TIMB::TIMBCR, 25, 2, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using MSTU = HRTIM_TIMB_TIMBCR_MSTU_Values<HRTIM_TIMB::TIMBCR, 24, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TEU = HRTIM_TIMB_TIMBCR_TEU_Values<HRTIM_TIMB::TIMBCR, 23, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TDU = HRTIM_TIMB_TIMBCR_TDU_Values<HRTIM_TIMB::TIMBCR, 22, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TCU = HRTIM_TIMB_TIMBCR_TCU_Values<HRTIM_TIMB::TIMBCR, 21, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TBU = HRTIM_TIMB_TIMBCR_TBU_Values<HRTIM_TIMB::TIMBCR, 20, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TxRSTU = HRTIM_TIMB_TIMBCR_TxRSTU_Values<HRTIM_TIMB::TIMBCR, 18, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using TxREPU = HRTIM_TIMB_TIMBCR_TxREPU_Values<HRTIM_TIMB::TIMBCR, 17, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using DELCMP4 = HRTIM_TIMB_TIMBCR_DELCMP4_Values<HRTIM_TIMB::TIMBCR, 14, 2, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using DELCMP2 = HRTIM_TIMB_TIMBCR_DELCMP2_Values<HRTIM_TIMB::TIMBCR, 12, 2, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using SYNCSTRTx = HRTIM_TIMB_TIMBCR_SYNCSTRTx_Values<HRTIM_TIMB::TIMBCR, 11, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using SYNCRSTx = HRTIM_TIMB_TIMBCR_SYNCRSTx_Values<HRTIM_TIMB::TIMBCR, 10, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using PSHPLL = HRTIM_TIMB_TIMBCR_PSHPLL_Values<HRTIM_TIMB::TIMBCR, 6, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using HALF = HRTIM_TIMB_TIMBCR_HALF_Values<HRTIM_TIMB::TIMBCR, 5, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using RETRIG = HRTIM_TIMB_TIMBCR_RETRIG_Values<HRTIM_TIMB::TIMBCR, 4, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using CONT = HRTIM_TIMB_TIMBCR_CONT_Values<HRTIM_TIMB::TIMBCR, 3, 1, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using CK_PSCx = HRTIM_TIMB_TIMBCR_CK_PSCx_Values<HRTIM_TIMB::TIMBCR, 0, 3, ReadWriteMode, HRTIM_TIMBTIMBCRBase> ;
    using FieldValues = HRTIM_TIMB_TIMBCR_CK_PSCx_Values<HRTIM_TIMB::TIMBCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMBCRPack  = Register<0x40017500, 32, ReadWriteMode, HRTIM_TIMBTIMBCRBase, T...> ;

  struct HRTIM_TIMBTIMBISRBase {} ;

  struct TIMBISR : public RegisterBase<0x40017504, 32, ReadMode>
  {
    using O2STAT = HRTIM_TIMB_TIMBISR_O2STAT_Values<HRTIM_TIMB::TIMBISR, 19, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using O1STAT = HRTIM_TIMB_TIMBISR_O1STAT_Values<HRTIM_TIMB::TIMBISR, 18, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using IPPSTAT = HRTIM_TIMB_TIMBISR_IPPSTAT_Values<HRTIM_TIMB::TIMBISR, 17, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CPPSTAT = HRTIM_TIMB_TIMBISR_CPPSTAT_Values<HRTIM_TIMB::TIMBISR, 16, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using DLYPRT = HRTIM_TIMB_TIMBISR_DLYPRT_Values<HRTIM_TIMB::TIMBISR, 14, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using RST = HRTIM_TIMB_TIMBISR_RST_Values<HRTIM_TIMB::TIMBISR, 13, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using RSTx2 = HRTIM_TIMB_TIMBISR_RSTx2_Values<HRTIM_TIMB::TIMBISR, 12, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using SETx2 = HRTIM_TIMB_TIMBISR_SETx2_Values<HRTIM_TIMB::TIMBISR, 11, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using RSTx1 = HRTIM_TIMB_TIMBISR_RSTx1_Values<HRTIM_TIMB::TIMBISR, 10, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using SETx1 = HRTIM_TIMB_TIMBISR_SETx1_Values<HRTIM_TIMB::TIMBISR, 9, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CPT2 = HRTIM_TIMB_TIMBISR_CPT2_Values<HRTIM_TIMB::TIMBISR, 8, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CPT1 = HRTIM_TIMB_TIMBISR_CPT1_Values<HRTIM_TIMB::TIMBISR, 7, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using UPD = HRTIM_TIMB_TIMBISR_UPD_Values<HRTIM_TIMB::TIMBISR, 6, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using REP = HRTIM_TIMB_TIMBISR_REP_Values<HRTIM_TIMB::TIMBISR, 4, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CMP4 = HRTIM_TIMB_TIMBISR_CMP4_Values<HRTIM_TIMB::TIMBISR, 3, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CMP3 = HRTIM_TIMB_TIMBISR_CMP3_Values<HRTIM_TIMB::TIMBISR, 2, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CMP2 = HRTIM_TIMB_TIMBISR_CMP2_Values<HRTIM_TIMB::TIMBISR, 1, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using CMP1 = HRTIM_TIMB_TIMBISR_CMP1_Values<HRTIM_TIMB::TIMBISR, 0, 1, ReadMode, HRTIM_TIMBTIMBISRBase> ;
    using FieldValues = HRTIM_TIMB_TIMBISR_CMP1_Values<HRTIM_TIMB::TIMBISR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMBISRPack  = Register<0x40017504, 32, ReadMode, HRTIM_TIMBTIMBISRBase, T...> ;

  struct HRTIM_TIMBTIMBICRBase {} ;

  struct TIMBICR : public RegisterBase<0x40017508, 32, WriteMode>
  {
    using DLYPRTC = HRTIM_TIMB_TIMBICR_DLYPRTC_Values<HRTIM_TIMB::TIMBICR, 14, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using RSTC = HRTIM_TIMB_TIMBICR_RSTC_Values<HRTIM_TIMB::TIMBICR, 13, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using RSTx2C = HRTIM_TIMB_TIMBICR_RSTx2C_Values<HRTIM_TIMB::TIMBICR, 12, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using SET2xC = HRTIM_TIMB_TIMBICR_SET2xC_Values<HRTIM_TIMB::TIMBICR, 11, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using RSTx1C = HRTIM_TIMB_TIMBICR_RSTx1C_Values<HRTIM_TIMB::TIMBICR, 10, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using SET1xC = HRTIM_TIMB_TIMBICR_SET1xC_Values<HRTIM_TIMB::TIMBICR, 9, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CPT2C = HRTIM_TIMB_TIMBICR_CPT2C_Values<HRTIM_TIMB::TIMBICR, 8, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CPT1C = HRTIM_TIMB_TIMBICR_CPT1C_Values<HRTIM_TIMB::TIMBICR, 7, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using UPDC = HRTIM_TIMB_TIMBICR_UPDC_Values<HRTIM_TIMB::TIMBICR, 6, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using REPC = HRTIM_TIMB_TIMBICR_REPC_Values<HRTIM_TIMB::TIMBICR, 4, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CMP4C = HRTIM_TIMB_TIMBICR_CMP4C_Values<HRTIM_TIMB::TIMBICR, 3, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CMP3C = HRTIM_TIMB_TIMBICR_CMP3C_Values<HRTIM_TIMB::TIMBICR, 2, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CMP2C = HRTIM_TIMB_TIMBICR_CMP2C_Values<HRTIM_TIMB::TIMBICR, 1, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using CMP1C = HRTIM_TIMB_TIMBICR_CMP1C_Values<HRTIM_TIMB::TIMBICR, 0, 1, WriteMode, HRTIM_TIMBTIMBICRBase> ;
    using FieldValues = HRTIM_TIMB_TIMBICR_CMP1C_Values<HRTIM_TIMB::TIMBICR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMBICRPack  = Register<0x40017508, 32, WriteMode, HRTIM_TIMBTIMBICRBase, T...> ;

  struct HRTIM_TIMBTIMBDIER5Base {} ;

  struct TIMBDIER5 : public RegisterBase<0x4001750C, 32, ReadWriteMode>
  {
    using DLYPRTDE = HRTIM_TIMB_TIMBDIER5_DLYPRTDE_Values<HRTIM_TIMB::TIMBDIER5, 30, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTDE = HRTIM_TIMB_TIMBDIER5_RSTDE_Values<HRTIM_TIMB::TIMBDIER5, 29, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTx2DE = HRTIM_TIMB_TIMBDIER5_RSTx2DE_Values<HRTIM_TIMB::TIMBDIER5, 28, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using SETx2DE = HRTIM_TIMB_TIMBDIER5_SETx2DE_Values<HRTIM_TIMB::TIMBDIER5, 27, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTx1DE = HRTIM_TIMB_TIMBDIER5_RSTx1DE_Values<HRTIM_TIMB::TIMBDIER5, 26, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using SET1xDE = HRTIM_TIMB_TIMBDIER5_SET1xDE_Values<HRTIM_TIMB::TIMBDIER5, 25, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CPT2DE = HRTIM_TIMB_TIMBDIER5_CPT2DE_Values<HRTIM_TIMB::TIMBDIER5, 24, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CPT1DE = HRTIM_TIMB_TIMBDIER5_CPT1DE_Values<HRTIM_TIMB::TIMBDIER5, 23, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using UPDDE = HRTIM_TIMB_TIMBDIER5_UPDDE_Values<HRTIM_TIMB::TIMBDIER5, 22, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using REPDE = HRTIM_TIMB_TIMBDIER5_REPDE_Values<HRTIM_TIMB::TIMBDIER5, 20, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP4DE = HRTIM_TIMB_TIMBDIER5_CMP4DE_Values<HRTIM_TIMB::TIMBDIER5, 19, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP3DE = HRTIM_TIMB_TIMBDIER5_CMP3DE_Values<HRTIM_TIMB::TIMBDIER5, 18, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP2DE = HRTIM_TIMB_TIMBDIER5_CMP2DE_Values<HRTIM_TIMB::TIMBDIER5, 17, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP1DE = HRTIM_TIMB_TIMBDIER5_CMP1DE_Values<HRTIM_TIMB::TIMBDIER5, 16, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using DLYPRTIE = HRTIM_TIMB_TIMBDIER5_DLYPRTIE_Values<HRTIM_TIMB::TIMBDIER5, 14, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTIE = HRTIM_TIMB_TIMBDIER5_RSTIE_Values<HRTIM_TIMB::TIMBDIER5, 13, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTx2IE = HRTIM_TIMB_TIMBDIER5_RSTx2IE_Values<HRTIM_TIMB::TIMBDIER5, 12, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using SETx2IE = HRTIM_TIMB_TIMBDIER5_SETx2IE_Values<HRTIM_TIMB::TIMBDIER5, 11, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using RSTx1IE = HRTIM_TIMB_TIMBDIER5_RSTx1IE_Values<HRTIM_TIMB::TIMBDIER5, 10, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using SET1xIE = HRTIM_TIMB_TIMBDIER5_SET1xIE_Values<HRTIM_TIMB::TIMBDIER5, 9, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CPT2IE = HRTIM_TIMB_TIMBDIER5_CPT2IE_Values<HRTIM_TIMB::TIMBDIER5, 8, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CPT1IE = HRTIM_TIMB_TIMBDIER5_CPT1IE_Values<HRTIM_TIMB::TIMBDIER5, 7, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using UPDIE = HRTIM_TIMB_TIMBDIER5_UPDIE_Values<HRTIM_TIMB::TIMBDIER5, 6, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using REPIE = HRTIM_TIMB_TIMBDIER5_REPIE_Values<HRTIM_TIMB::TIMBDIER5, 4, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP4IE = HRTIM_TIMB_TIMBDIER5_CMP4IE_Values<HRTIM_TIMB::TIMBDIER5, 3, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP3IE = HRTIM_TIMB_TIMBDIER5_CMP3IE_Values<HRTIM_TIMB::TIMBDIER5, 2, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP2IE = HRTIM_TIMB_TIMBDIER5_CMP2IE_Values<HRTIM_TIMB::TIMBDIER5, 1, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using CMP1IE = HRTIM_TIMB_TIMBDIER5_CMP1IE_Values<HRTIM_TIMB::TIMBDIER5, 0, 1, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base> ;
    using FieldValues = HRTIM_TIMB_TIMBDIER5_CMP1IE_Values<HRTIM_TIMB::TIMBDIER5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using TIMBDIER5Pack  = Register<0x4001750C, 32, ReadWriteMode, HRTIM_TIMBTIMBDIER5Base, T...> ;

  struct HRTIM_TIMBCNTRBase {} ;

  struct CNTR : public RegisterBase<0x40017510, 32, ReadWriteMode>
  {
    using CNTx = HRTIM_TIMB_CNTR_CNTx_Values<HRTIM_TIMB::CNTR, 0, 16, ReadWriteMode, HRTIM_TIMBCNTRBase> ;
    using FieldValues = HRTIM_TIMB_CNTR_CNTx_Values<HRTIM_TIMB::CNTR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CNTRPack  = Register<0x40017510, 32, ReadWriteMode, HRTIM_TIMBCNTRBase, T...> ;

  struct HRTIM_TIMBPERBRBase {} ;

  struct PERBR : public RegisterBase<0x40017514, 32, ReadWriteMode>
  {
    using PERx = HRTIM_TIMB_PERBR_PERx_Values<HRTIM_TIMB::PERBR, 0, 16, ReadWriteMode, HRTIM_TIMBPERBRBase> ;
    using FieldValues = HRTIM_TIMB_PERBR_PERx_Values<HRTIM_TIMB::PERBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using PERBRPack  = Register<0x40017514, 32, ReadWriteMode, HRTIM_TIMBPERBRBase, T...> ;

  struct HRTIM_TIMBREPBRBase {} ;

  struct REPBR : public RegisterBase<0x40017518, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMB_REPBR_REPx_Values<HRTIM_TIMB::REPBR, 0, 8, ReadWriteMode, HRTIM_TIMBREPBRBase> ;
    using FieldValues = HRTIM_TIMB_REPBR_REPx_Values<HRTIM_TIMB::REPBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using REPBRPack  = Register<0x40017518, 32, ReadWriteMode, HRTIM_TIMBREPBRBase, T...> ;

  struct HRTIM_TIMBCMP1BRBase {} ;

  struct CMP1BR : public RegisterBase<0x4001751C, 32, ReadWriteMode>
  {
    using CMP1x = HRTIM_TIMB_CMP1BR_CMP1x_Values<HRTIM_TIMB::CMP1BR, 0, 16, ReadWriteMode, HRTIM_TIMBCMP1BRBase> ;
    using FieldValues = HRTIM_TIMB_CMP1BR_CMP1x_Values<HRTIM_TIMB::CMP1BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1BRPack  = Register<0x4001751C, 32, ReadWriteMode, HRTIM_TIMBCMP1BRBase, T...> ;

  struct HRTIM_TIMBCMP1CBRBase {} ;

  struct CMP1CBR : public RegisterBase<0x40017520, 32, ReadWriteMode>
  {
    using REPx = HRTIM_TIMB_CMP1CBR_REPx_Values<HRTIM_TIMB::CMP1CBR, 16, 8, ReadWriteMode, HRTIM_TIMBCMP1CBRBase> ;
    using CMP1x = HRTIM_TIMB_CMP1CBR_CMP1x_Values<HRTIM_TIMB::CMP1CBR, 0, 16, ReadWriteMode, HRTIM_TIMBCMP1CBRBase> ;
    using FieldValues = HRTIM_TIMB_CMP1CBR_CMP1x_Values<HRTIM_TIMB::CMP1CBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP1CBRPack  = Register<0x40017520, 32, ReadWriteMode, HRTIM_TIMBCMP1CBRBase, T...> ;

  struct HRTIM_TIMBCMP2BRBase {} ;

  struct CMP2BR : public RegisterBase<0x40017524, 32, ReadWriteMode>
  {
    using CMP2x = HRTIM_TIMB_CMP2BR_CMP2x_Values<HRTIM_TIMB::CMP2BR, 0, 16, ReadWriteMode, HRTIM_TIMBCMP2BRBase> ;
    using FieldValues = HRTIM_TIMB_CMP2BR_CMP2x_Values<HRTIM_TIMB::CMP2BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP2BRPack  = Register<0x40017524, 32, ReadWriteMode, HRTIM_TIMBCMP2BRBase, T...> ;

  struct HRTIM_TIMBCMP3BRBase {} ;

  struct CMP3BR : public RegisterBase<0x40017528, 32, ReadWriteMode>
  {
    using CMP3x = HRTIM_TIMB_CMP3BR_CMP3x_Values<HRTIM_TIMB::CMP3BR, 0, 16, ReadWriteMode, HRTIM_TIMBCMP3BRBase> ;
    using FieldValues = HRTIM_TIMB_CMP3BR_CMP3x_Values<HRTIM_TIMB::CMP3BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP3BRPack  = Register<0x40017528, 32, ReadWriteMode, HRTIM_TIMBCMP3BRBase, T...> ;

  struct HRTIM_TIMBCMP4BRBase {} ;

  struct CMP4BR : public RegisterBase<0x4001752C, 32, ReadWriteMode>
  {
    using CMP4x = HRTIM_TIMB_CMP4BR_CMP4x_Values<HRTIM_TIMB::CMP4BR, 0, 16, ReadWriteMode, HRTIM_TIMBCMP4BRBase> ;
    using FieldValues = HRTIM_TIMB_CMP4BR_CMP4x_Values<HRTIM_TIMB::CMP4BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CMP4BRPack  = Register<0x4001752C, 32, ReadWriteMode, HRTIM_TIMBCMP4BRBase, T...> ;

  struct HRTIM_TIMBCPT1BRBase {} ;

  struct CPT1BR : public RegisterBase<0x40017530, 32, ReadMode>
  {
    using CPT1x = HRTIM_TIMB_CPT1BR_CPT1x_Values<HRTIM_TIMB::CPT1BR, 0, 16, ReadMode, HRTIM_TIMBCPT1BRBase> ;
    using FieldValues = HRTIM_TIMB_CPT1BR_CPT1x_Values<HRTIM_TIMB::CPT1BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1BRPack  = Register<0x40017530, 32, ReadMode, HRTIM_TIMBCPT1BRBase, T...> ;

  struct HRTIM_TIMBCPT2BRBase {} ;

  struct CPT2BR : public RegisterBase<0x40017534, 32, ReadMode>
  {
    using CPT2x = HRTIM_TIMB_CPT2BR_CPT2x_Values<HRTIM_TIMB::CPT2BR, 0, 16, ReadMode, HRTIM_TIMBCPT2BRBase> ;
    using FieldValues = HRTIM_TIMB_CPT2BR_CPT2x_Values<HRTIM_TIMB::CPT2BR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2BRPack  = Register<0x40017534, 32, ReadMode, HRTIM_TIMBCPT2BRBase, T...> ;

  struct HRTIM_TIMBDTBRBase {} ;

  struct DTBR : public RegisterBase<0x40017538, 32, ReadWriteMode>
  {
    using DTFLKx = HRTIM_TIMB_DTBR_DTFLKx_Values<HRTIM_TIMB::DTBR, 31, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTFSLKx = HRTIM_TIMB_DTBR_DTFSLKx_Values<HRTIM_TIMB::DTBR, 30, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using SDTFx = HRTIM_TIMB_DTBR_SDTFx_Values<HRTIM_TIMB::DTBR, 25, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTFx = HRTIM_TIMB_DTBR_DTFx_Values<HRTIM_TIMB::DTBR, 16, 9, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTRLKx = HRTIM_TIMB_DTBR_DTRLKx_Values<HRTIM_TIMB::DTBR, 15, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTRSLKx = HRTIM_TIMB_DTBR_DTRSLKx_Values<HRTIM_TIMB::DTBR, 14, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTPRSC = HRTIM_TIMB_DTBR_DTPRSC_Values<HRTIM_TIMB::DTBR, 10, 3, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using SDTRx = HRTIM_TIMB_DTBR_SDTRx_Values<HRTIM_TIMB::DTBR, 9, 1, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using DTRx = HRTIM_TIMB_DTBR_DTRx_Values<HRTIM_TIMB::DTBR, 0, 9, ReadWriteMode, HRTIM_TIMBDTBRBase> ;
    using FieldValues = HRTIM_TIMB_DTBR_DTRx_Values<HRTIM_TIMB::DTBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using DTBRPack  = Register<0x40017538, 32, ReadWriteMode, HRTIM_TIMBDTBRBase, T...> ;

  struct HRTIM_TIMBSETB1RBase {} ;

  struct SETB1R : public RegisterBase<0x4001753C, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMB_SETB1R_UPDATE_Values<HRTIM_TIMB::SETB1R, 31, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT10 = HRTIM_TIMB_SETB1R_EXTEVNT10_Values<HRTIM_TIMB::SETB1R, 30, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT9 = HRTIM_TIMB_SETB1R_EXTEVNT9_Values<HRTIM_TIMB::SETB1R, 29, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT8 = HRTIM_TIMB_SETB1R_EXTEVNT8_Values<HRTIM_TIMB::SETB1R, 28, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT7 = HRTIM_TIMB_SETB1R_EXTEVNT7_Values<HRTIM_TIMB::SETB1R, 27, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT6 = HRTIM_TIMB_SETB1R_EXTEVNT6_Values<HRTIM_TIMB::SETB1R, 26, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT5 = HRTIM_TIMB_SETB1R_EXTEVNT5_Values<HRTIM_TIMB::SETB1R, 25, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT4 = HRTIM_TIMB_SETB1R_EXTEVNT4_Values<HRTIM_TIMB::SETB1R, 24, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT3 = HRTIM_TIMB_SETB1R_EXTEVNT3_Values<HRTIM_TIMB::SETB1R, 23, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT2 = HRTIM_TIMB_SETB1R_EXTEVNT2_Values<HRTIM_TIMB::SETB1R, 22, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using EXTEVNT1 = HRTIM_TIMB_SETB1R_EXTEVNT1_Values<HRTIM_TIMB::SETB1R, 21, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT9 = HRTIM_TIMB_SETB1R_TIMEVNT9_Values<HRTIM_TIMB::SETB1R, 20, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT8 = HRTIM_TIMB_SETB1R_TIMEVNT8_Values<HRTIM_TIMB::SETB1R, 19, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT7 = HRTIM_TIMB_SETB1R_TIMEVNT7_Values<HRTIM_TIMB::SETB1R, 18, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT6 = HRTIM_TIMB_SETB1R_TIMEVNT6_Values<HRTIM_TIMB::SETB1R, 17, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT5 = HRTIM_TIMB_SETB1R_TIMEVNT5_Values<HRTIM_TIMB::SETB1R, 16, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT4 = HRTIM_TIMB_SETB1R_TIMEVNT4_Values<HRTIM_TIMB::SETB1R, 15, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT3 = HRTIM_TIMB_SETB1R_TIMEVNT3_Values<HRTIM_TIMB::SETB1R, 14, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT2 = HRTIM_TIMB_SETB1R_TIMEVNT2_Values<HRTIM_TIMB::SETB1R, 13, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using TIMEVNT1 = HRTIM_TIMB_SETB1R_TIMEVNT1_Values<HRTIM_TIMB::SETB1R, 12, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using MSTCMP4 = HRTIM_TIMB_SETB1R_MSTCMP4_Values<HRTIM_TIMB::SETB1R, 11, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using MSTCMP3 = HRTIM_TIMB_SETB1R_MSTCMP3_Values<HRTIM_TIMB::SETB1R, 10, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using MSTCMP2 = HRTIM_TIMB_SETB1R_MSTCMP2_Values<HRTIM_TIMB::SETB1R, 9, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using MSTCMP1 = HRTIM_TIMB_SETB1R_MSTCMP1_Values<HRTIM_TIMB::SETB1R, 8, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using MSTPER = HRTIM_TIMB_SETB1R_MSTPER_Values<HRTIM_TIMB::SETB1R, 7, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using CMP4 = HRTIM_TIMB_SETB1R_CMP4_Values<HRTIM_TIMB::SETB1R, 6, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using CMP3 = HRTIM_TIMB_SETB1R_CMP3_Values<HRTIM_TIMB::SETB1R, 5, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using CMP2 = HRTIM_TIMB_SETB1R_CMP2_Values<HRTIM_TIMB::SETB1R, 4, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using CMP1 = HRTIM_TIMB_SETB1R_CMP1_Values<HRTIM_TIMB::SETB1R, 3, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using PER = HRTIM_TIMB_SETB1R_PER_Values<HRTIM_TIMB::SETB1R, 2, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using RESYNC = HRTIM_TIMB_SETB1R_RESYNC_Values<HRTIM_TIMB::SETB1R, 1, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using SST = HRTIM_TIMB_SETB1R_SST_Values<HRTIM_TIMB::SETB1R, 0, 1, ReadWriteMode, HRTIM_TIMBSETB1RBase> ;
    using FieldValues = HRTIM_TIMB_SETB1R_SST_Values<HRTIM_TIMB::SETB1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETB1RPack  = Register<0x4001753C, 32, ReadWriteMode, HRTIM_TIMBSETB1RBase, T...> ;

  struct HRTIM_TIMBRSTB1RBase {} ;

  struct RSTB1R : public RegisterBase<0x40017540, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMB_RSTB1R_UPDATE_Values<HRTIM_TIMB::RSTB1R, 31, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT10 = HRTIM_TIMB_RSTB1R_EXTEVNT10_Values<HRTIM_TIMB::RSTB1R, 30, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT9 = HRTIM_TIMB_RSTB1R_EXTEVNT9_Values<HRTIM_TIMB::RSTB1R, 29, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT8 = HRTIM_TIMB_RSTB1R_EXTEVNT8_Values<HRTIM_TIMB::RSTB1R, 28, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT7 = HRTIM_TIMB_RSTB1R_EXTEVNT7_Values<HRTIM_TIMB::RSTB1R, 27, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT6 = HRTIM_TIMB_RSTB1R_EXTEVNT6_Values<HRTIM_TIMB::RSTB1R, 26, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT5 = HRTIM_TIMB_RSTB1R_EXTEVNT5_Values<HRTIM_TIMB::RSTB1R, 25, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT4 = HRTIM_TIMB_RSTB1R_EXTEVNT4_Values<HRTIM_TIMB::RSTB1R, 24, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT3 = HRTIM_TIMB_RSTB1R_EXTEVNT3_Values<HRTIM_TIMB::RSTB1R, 23, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT2 = HRTIM_TIMB_RSTB1R_EXTEVNT2_Values<HRTIM_TIMB::RSTB1R, 22, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using EXTEVNT1 = HRTIM_TIMB_RSTB1R_EXTEVNT1_Values<HRTIM_TIMB::RSTB1R, 21, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT9 = HRTIM_TIMB_RSTB1R_TIMEVNT9_Values<HRTIM_TIMB::RSTB1R, 20, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT8 = HRTIM_TIMB_RSTB1R_TIMEVNT8_Values<HRTIM_TIMB::RSTB1R, 19, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT7 = HRTIM_TIMB_RSTB1R_TIMEVNT7_Values<HRTIM_TIMB::RSTB1R, 18, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT6 = HRTIM_TIMB_RSTB1R_TIMEVNT6_Values<HRTIM_TIMB::RSTB1R, 17, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT5 = HRTIM_TIMB_RSTB1R_TIMEVNT5_Values<HRTIM_TIMB::RSTB1R, 16, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT4 = HRTIM_TIMB_RSTB1R_TIMEVNT4_Values<HRTIM_TIMB::RSTB1R, 15, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT3 = HRTIM_TIMB_RSTB1R_TIMEVNT3_Values<HRTIM_TIMB::RSTB1R, 14, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT2 = HRTIM_TIMB_RSTB1R_TIMEVNT2_Values<HRTIM_TIMB::RSTB1R, 13, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using TIMEVNT1 = HRTIM_TIMB_RSTB1R_TIMEVNT1_Values<HRTIM_TIMB::RSTB1R, 12, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using MSTCMP4 = HRTIM_TIMB_RSTB1R_MSTCMP4_Values<HRTIM_TIMB::RSTB1R, 11, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using MSTCMP3 = HRTIM_TIMB_RSTB1R_MSTCMP3_Values<HRTIM_TIMB::RSTB1R, 10, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using MSTCMP2 = HRTIM_TIMB_RSTB1R_MSTCMP2_Values<HRTIM_TIMB::RSTB1R, 9, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using MSTCMP1 = HRTIM_TIMB_RSTB1R_MSTCMP1_Values<HRTIM_TIMB::RSTB1R, 8, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using MSTPER = HRTIM_TIMB_RSTB1R_MSTPER_Values<HRTIM_TIMB::RSTB1R, 7, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using CMP4 = HRTIM_TIMB_RSTB1R_CMP4_Values<HRTIM_TIMB::RSTB1R, 6, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using CMP3 = HRTIM_TIMB_RSTB1R_CMP3_Values<HRTIM_TIMB::RSTB1R, 5, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using CMP2 = HRTIM_TIMB_RSTB1R_CMP2_Values<HRTIM_TIMB::RSTB1R, 4, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using CMP1 = HRTIM_TIMB_RSTB1R_CMP1_Values<HRTIM_TIMB::RSTB1R, 3, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using PER = HRTIM_TIMB_RSTB1R_PER_Values<HRTIM_TIMB::RSTB1R, 2, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using RESYNC = HRTIM_TIMB_RSTB1R_RESYNC_Values<HRTIM_TIMB::RSTB1R, 1, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using SRT = HRTIM_TIMB_RSTB1R_SRT_Values<HRTIM_TIMB::RSTB1R, 0, 1, ReadWriteMode, HRTIM_TIMBRSTB1RBase> ;
    using FieldValues = HRTIM_TIMB_RSTB1R_SRT_Values<HRTIM_TIMB::RSTB1R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTB1RPack  = Register<0x40017540, 32, ReadWriteMode, HRTIM_TIMBRSTB1RBase, T...> ;

  struct HRTIM_TIMBSETB2RBase {} ;

  struct SETB2R : public RegisterBase<0x40017544, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMB_SETB2R_UPDATE_Values<HRTIM_TIMB::SETB2R, 31, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT10 = HRTIM_TIMB_SETB2R_EXTEVNT10_Values<HRTIM_TIMB::SETB2R, 30, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT9 = HRTIM_TIMB_SETB2R_EXTEVNT9_Values<HRTIM_TIMB::SETB2R, 29, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT8 = HRTIM_TIMB_SETB2R_EXTEVNT8_Values<HRTIM_TIMB::SETB2R, 28, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT7 = HRTIM_TIMB_SETB2R_EXTEVNT7_Values<HRTIM_TIMB::SETB2R, 27, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT6 = HRTIM_TIMB_SETB2R_EXTEVNT6_Values<HRTIM_TIMB::SETB2R, 26, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT5 = HRTIM_TIMB_SETB2R_EXTEVNT5_Values<HRTIM_TIMB::SETB2R, 25, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT4 = HRTIM_TIMB_SETB2R_EXTEVNT4_Values<HRTIM_TIMB::SETB2R, 24, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT3 = HRTIM_TIMB_SETB2R_EXTEVNT3_Values<HRTIM_TIMB::SETB2R, 23, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT2 = HRTIM_TIMB_SETB2R_EXTEVNT2_Values<HRTIM_TIMB::SETB2R, 22, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using EXTEVNT1 = HRTIM_TIMB_SETB2R_EXTEVNT1_Values<HRTIM_TIMB::SETB2R, 21, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT9 = HRTIM_TIMB_SETB2R_TIMEVNT9_Values<HRTIM_TIMB::SETB2R, 20, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT8 = HRTIM_TIMB_SETB2R_TIMEVNT8_Values<HRTIM_TIMB::SETB2R, 19, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT7 = HRTIM_TIMB_SETB2R_TIMEVNT7_Values<HRTIM_TIMB::SETB2R, 18, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT6 = HRTIM_TIMB_SETB2R_TIMEVNT6_Values<HRTIM_TIMB::SETB2R, 17, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT5 = HRTIM_TIMB_SETB2R_TIMEVNT5_Values<HRTIM_TIMB::SETB2R, 16, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT4 = HRTIM_TIMB_SETB2R_TIMEVNT4_Values<HRTIM_TIMB::SETB2R, 15, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT3 = HRTIM_TIMB_SETB2R_TIMEVNT3_Values<HRTIM_TIMB::SETB2R, 14, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT2 = HRTIM_TIMB_SETB2R_TIMEVNT2_Values<HRTIM_TIMB::SETB2R, 13, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using TIMEVNT1 = HRTIM_TIMB_SETB2R_TIMEVNT1_Values<HRTIM_TIMB::SETB2R, 12, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using MSTCMP4 = HRTIM_TIMB_SETB2R_MSTCMP4_Values<HRTIM_TIMB::SETB2R, 11, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using MSTCMP3 = HRTIM_TIMB_SETB2R_MSTCMP3_Values<HRTIM_TIMB::SETB2R, 10, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using MSTCMP2 = HRTIM_TIMB_SETB2R_MSTCMP2_Values<HRTIM_TIMB::SETB2R, 9, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using MSTCMP1 = HRTIM_TIMB_SETB2R_MSTCMP1_Values<HRTIM_TIMB::SETB2R, 8, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using MSTPER = HRTIM_TIMB_SETB2R_MSTPER_Values<HRTIM_TIMB::SETB2R, 7, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using CMP4 = HRTIM_TIMB_SETB2R_CMP4_Values<HRTIM_TIMB::SETB2R, 6, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using CMP3 = HRTIM_TIMB_SETB2R_CMP3_Values<HRTIM_TIMB::SETB2R, 5, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using CMP2 = HRTIM_TIMB_SETB2R_CMP2_Values<HRTIM_TIMB::SETB2R, 4, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using CMP1 = HRTIM_TIMB_SETB2R_CMP1_Values<HRTIM_TIMB::SETB2R, 3, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using PER = HRTIM_TIMB_SETB2R_PER_Values<HRTIM_TIMB::SETB2R, 2, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using RESYNC = HRTIM_TIMB_SETB2R_RESYNC_Values<HRTIM_TIMB::SETB2R, 1, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using SST = HRTIM_TIMB_SETB2R_SST_Values<HRTIM_TIMB::SETB2R, 0, 1, ReadWriteMode, HRTIM_TIMBSETB2RBase> ;
    using FieldValues = HRTIM_TIMB_SETB2R_SST_Values<HRTIM_TIMB::SETB2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SETB2RPack  = Register<0x40017544, 32, ReadWriteMode, HRTIM_TIMBSETB2RBase, T...> ;

  struct HRTIM_TIMBRSTB2RBase {} ;

  struct RSTB2R : public RegisterBase<0x40017548, 32, ReadWriteMode>
  {
    using UPDATE = HRTIM_TIMB_RSTB2R_UPDATE_Values<HRTIM_TIMB::RSTB2R, 31, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT10 = HRTIM_TIMB_RSTB2R_EXTEVNT10_Values<HRTIM_TIMB::RSTB2R, 30, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT9 = HRTIM_TIMB_RSTB2R_EXTEVNT9_Values<HRTIM_TIMB::RSTB2R, 29, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT8 = HRTIM_TIMB_RSTB2R_EXTEVNT8_Values<HRTIM_TIMB::RSTB2R, 28, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT7 = HRTIM_TIMB_RSTB2R_EXTEVNT7_Values<HRTIM_TIMB::RSTB2R, 27, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT6 = HRTIM_TIMB_RSTB2R_EXTEVNT6_Values<HRTIM_TIMB::RSTB2R, 26, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT5 = HRTIM_TIMB_RSTB2R_EXTEVNT5_Values<HRTIM_TIMB::RSTB2R, 25, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT4 = HRTIM_TIMB_RSTB2R_EXTEVNT4_Values<HRTIM_TIMB::RSTB2R, 24, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT3 = HRTIM_TIMB_RSTB2R_EXTEVNT3_Values<HRTIM_TIMB::RSTB2R, 23, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT2 = HRTIM_TIMB_RSTB2R_EXTEVNT2_Values<HRTIM_TIMB::RSTB2R, 22, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using EXTEVNT1 = HRTIM_TIMB_RSTB2R_EXTEVNT1_Values<HRTIM_TIMB::RSTB2R, 21, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT9 = HRTIM_TIMB_RSTB2R_TIMEVNT9_Values<HRTIM_TIMB::RSTB2R, 20, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT8 = HRTIM_TIMB_RSTB2R_TIMEVNT8_Values<HRTIM_TIMB::RSTB2R, 19, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT7 = HRTIM_TIMB_RSTB2R_TIMEVNT7_Values<HRTIM_TIMB::RSTB2R, 18, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT6 = HRTIM_TIMB_RSTB2R_TIMEVNT6_Values<HRTIM_TIMB::RSTB2R, 17, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT5 = HRTIM_TIMB_RSTB2R_TIMEVNT5_Values<HRTIM_TIMB::RSTB2R, 16, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT4 = HRTIM_TIMB_RSTB2R_TIMEVNT4_Values<HRTIM_TIMB::RSTB2R, 15, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT3 = HRTIM_TIMB_RSTB2R_TIMEVNT3_Values<HRTIM_TIMB::RSTB2R, 14, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT2 = HRTIM_TIMB_RSTB2R_TIMEVNT2_Values<HRTIM_TIMB::RSTB2R, 13, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using TIMEVNT1 = HRTIM_TIMB_RSTB2R_TIMEVNT1_Values<HRTIM_TIMB::RSTB2R, 12, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using MSTCMP4 = HRTIM_TIMB_RSTB2R_MSTCMP4_Values<HRTIM_TIMB::RSTB2R, 11, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using MSTCMP3 = HRTIM_TIMB_RSTB2R_MSTCMP3_Values<HRTIM_TIMB::RSTB2R, 10, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using MSTCMP2 = HRTIM_TIMB_RSTB2R_MSTCMP2_Values<HRTIM_TIMB::RSTB2R, 9, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using MSTCMP1 = HRTIM_TIMB_RSTB2R_MSTCMP1_Values<HRTIM_TIMB::RSTB2R, 8, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using MSTPER = HRTIM_TIMB_RSTB2R_MSTPER_Values<HRTIM_TIMB::RSTB2R, 7, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using CMP4 = HRTIM_TIMB_RSTB2R_CMP4_Values<HRTIM_TIMB::RSTB2R, 6, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using CMP3 = HRTIM_TIMB_RSTB2R_CMP3_Values<HRTIM_TIMB::RSTB2R, 5, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using CMP2 = HRTIM_TIMB_RSTB2R_CMP2_Values<HRTIM_TIMB::RSTB2R, 4, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using CMP1 = HRTIM_TIMB_RSTB2R_CMP1_Values<HRTIM_TIMB::RSTB2R, 3, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using PER = HRTIM_TIMB_RSTB2R_PER_Values<HRTIM_TIMB::RSTB2R, 2, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using RESYNC = HRTIM_TIMB_RSTB2R_RESYNC_Values<HRTIM_TIMB::RSTB2R, 1, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using SRT = HRTIM_TIMB_RSTB2R_SRT_Values<HRTIM_TIMB::RSTB2R, 0, 1, ReadWriteMode, HRTIM_TIMBRSTB2RBase> ;
    using FieldValues = HRTIM_TIMB_RSTB2R_SRT_Values<HRTIM_TIMB::RSTB2R, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTB2RPack  = Register<0x40017548, 32, ReadWriteMode, HRTIM_TIMBRSTB2RBase, T...> ;

  struct HRTIM_TIMBEEFBR1Base {} ;

  struct EEFBR1 : public RegisterBase<0x4001754C, 32, ReadWriteMode>
  {
    using EE5FLTR = HRTIM_TIMB_EEFBR1_EE5FLTR_Values<HRTIM_TIMB::EEFBR1, 25, 4, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE5LTCH = HRTIM_TIMB_EEFBR1_EE5LTCH_Values<HRTIM_TIMB::EEFBR1, 24, 1, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE4FLTR = HRTIM_TIMB_EEFBR1_EE4FLTR_Values<HRTIM_TIMB::EEFBR1, 19, 4, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE4LTCH = HRTIM_TIMB_EEFBR1_EE4LTCH_Values<HRTIM_TIMB::EEFBR1, 18, 1, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE3FLTR = HRTIM_TIMB_EEFBR1_EE3FLTR_Values<HRTIM_TIMB::EEFBR1, 13, 4, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE3LTCH = HRTIM_TIMB_EEFBR1_EE3LTCH_Values<HRTIM_TIMB::EEFBR1, 12, 1, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE2FLTR = HRTIM_TIMB_EEFBR1_EE2FLTR_Values<HRTIM_TIMB::EEFBR1, 7, 4, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE2LTCH = HRTIM_TIMB_EEFBR1_EE2LTCH_Values<HRTIM_TIMB::EEFBR1, 6, 1, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE1FLTR = HRTIM_TIMB_EEFBR1_EE1FLTR_Values<HRTIM_TIMB::EEFBR1, 1, 4, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using EE1LTCH = HRTIM_TIMB_EEFBR1_EE1LTCH_Values<HRTIM_TIMB::EEFBR1, 0, 1, ReadWriteMode, HRTIM_TIMBEEFBR1Base> ;
    using FieldValues = HRTIM_TIMB_EEFBR1_EE1LTCH_Values<HRTIM_TIMB::EEFBR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFBR1Pack  = Register<0x4001754C, 32, ReadWriteMode, HRTIM_TIMBEEFBR1Base, T...> ;

  struct HRTIM_TIMBEEFBR2Base {} ;

  struct EEFBR2 : public RegisterBase<0x40017550, 32, ReadWriteMode>
  {
    using EE10FLTR = HRTIM_TIMB_EEFBR2_EE10FLTR_Values<HRTIM_TIMB::EEFBR2, 25, 4, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE10LTCH = HRTIM_TIMB_EEFBR2_EE10LTCH_Values<HRTIM_TIMB::EEFBR2, 24, 1, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE9FLTR = HRTIM_TIMB_EEFBR2_EE9FLTR_Values<HRTIM_TIMB::EEFBR2, 19, 4, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE9LTCH = HRTIM_TIMB_EEFBR2_EE9LTCH_Values<HRTIM_TIMB::EEFBR2, 18, 1, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE8FLTR = HRTIM_TIMB_EEFBR2_EE8FLTR_Values<HRTIM_TIMB::EEFBR2, 13, 4, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE8LTCH = HRTIM_TIMB_EEFBR2_EE8LTCH_Values<HRTIM_TIMB::EEFBR2, 12, 1, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE7FLTR = HRTIM_TIMB_EEFBR2_EE7FLTR_Values<HRTIM_TIMB::EEFBR2, 7, 4, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE7LTCH = HRTIM_TIMB_EEFBR2_EE7LTCH_Values<HRTIM_TIMB::EEFBR2, 6, 1, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE6FLTR = HRTIM_TIMB_EEFBR2_EE6FLTR_Values<HRTIM_TIMB::EEFBR2, 1, 4, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using EE6LTCH = HRTIM_TIMB_EEFBR2_EE6LTCH_Values<HRTIM_TIMB::EEFBR2, 0, 1, ReadWriteMode, HRTIM_TIMBEEFBR2Base> ;
    using FieldValues = HRTIM_TIMB_EEFBR2_EE6LTCH_Values<HRTIM_TIMB::EEFBR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using EEFBR2Pack  = Register<0x40017550, 32, ReadWriteMode, HRTIM_TIMBEEFBR2Base, T...> ;

  struct HRTIM_TIMBRSTBRBase {} ;

  struct RSTBR : public RegisterBase<0x40017554, 32, ReadWriteMode>
  {
    using TIMECMP4 = HRTIM_TIMB_RSTBR_TIMECMP4_Values<HRTIM_TIMB::RSTBR, 30, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMECMP2 = HRTIM_TIMB_RSTBR_TIMECMP2_Values<HRTIM_TIMB::RSTBR, 29, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMECMP1 = HRTIM_TIMB_RSTBR_TIMECMP1_Values<HRTIM_TIMB::RSTBR, 28, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMDCMP4 = HRTIM_TIMB_RSTBR_TIMDCMP4_Values<HRTIM_TIMB::RSTBR, 27, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMDCMP2 = HRTIM_TIMB_RSTBR_TIMDCMP2_Values<HRTIM_TIMB::RSTBR, 26, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMDCMP1 = HRTIM_TIMB_RSTBR_TIMDCMP1_Values<HRTIM_TIMB::RSTBR, 25, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMCCMP4 = HRTIM_TIMB_RSTBR_TIMCCMP4_Values<HRTIM_TIMB::RSTBR, 24, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMCCMP2 = HRTIM_TIMB_RSTBR_TIMCCMP2_Values<HRTIM_TIMB::RSTBR, 23, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMCCMP1 = HRTIM_TIMB_RSTBR_TIMCCMP1_Values<HRTIM_TIMB::RSTBR, 22, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMACMP4 = HRTIM_TIMB_RSTBR_TIMACMP4_Values<HRTIM_TIMB::RSTBR, 21, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMACMP2 = HRTIM_TIMB_RSTBR_TIMACMP2_Values<HRTIM_TIMB::RSTBR, 20, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using TIMACMP1 = HRTIM_TIMB_RSTBR_TIMACMP1_Values<HRTIM_TIMB::RSTBR, 19, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT10 = HRTIM_TIMB_RSTBR_EXTEVNT10_Values<HRTIM_TIMB::RSTBR, 18, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT9 = HRTIM_TIMB_RSTBR_EXTEVNT9_Values<HRTIM_TIMB::RSTBR, 17, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT8 = HRTIM_TIMB_RSTBR_EXTEVNT8_Values<HRTIM_TIMB::RSTBR, 16, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT7 = HRTIM_TIMB_RSTBR_EXTEVNT7_Values<HRTIM_TIMB::RSTBR, 15, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT6 = HRTIM_TIMB_RSTBR_EXTEVNT6_Values<HRTIM_TIMB::RSTBR, 14, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT5 = HRTIM_TIMB_RSTBR_EXTEVNT5_Values<HRTIM_TIMB::RSTBR, 13, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT4 = HRTIM_TIMB_RSTBR_EXTEVNT4_Values<HRTIM_TIMB::RSTBR, 12, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT3 = HRTIM_TIMB_RSTBR_EXTEVNT3_Values<HRTIM_TIMB::RSTBR, 11, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT2 = HRTIM_TIMB_RSTBR_EXTEVNT2_Values<HRTIM_TIMB::RSTBR, 10, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using EXTEVNT1 = HRTIM_TIMB_RSTBR_EXTEVNT1_Values<HRTIM_TIMB::RSTBR, 9, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using MSTCMP4 = HRTIM_TIMB_RSTBR_MSTCMP4_Values<HRTIM_TIMB::RSTBR, 8, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using MSTCMP3 = HRTIM_TIMB_RSTBR_MSTCMP3_Values<HRTIM_TIMB::RSTBR, 7, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using MSTCMP2 = HRTIM_TIMB_RSTBR_MSTCMP2_Values<HRTIM_TIMB::RSTBR, 6, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using MSTCMP1 = HRTIM_TIMB_RSTBR_MSTCMP1_Values<HRTIM_TIMB::RSTBR, 5, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using MSTPER = HRTIM_TIMB_RSTBR_MSTPER_Values<HRTIM_TIMB::RSTBR, 4, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using CMP4 = HRTIM_TIMB_RSTBR_CMP4_Values<HRTIM_TIMB::RSTBR, 3, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using CMP2 = HRTIM_TIMB_RSTBR_CMP2_Values<HRTIM_TIMB::RSTBR, 2, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using UPDT = HRTIM_TIMB_RSTBR_UPDT_Values<HRTIM_TIMB::RSTBR, 1, 1, ReadWriteMode, HRTIM_TIMBRSTBRBase> ;
    using FieldValues = HRTIM_TIMB_RSTBR_UPDT_Values<HRTIM_TIMB::RSTBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using RSTBRPack  = Register<0x40017554, 32, ReadWriteMode, HRTIM_TIMBRSTBRBase, T...> ;

  struct HRTIM_TIMBCHPBRBase {} ;

  struct CHPBR : public RegisterBase<0x40017558, 32, ReadWriteMode>
  {
    using STRTPW = HRTIM_TIMB_CHPBR_STRTPW_Values<HRTIM_TIMB::CHPBR, 7, 4, ReadWriteMode, HRTIM_TIMBCHPBRBase> ;
    using CHPDTY = HRTIM_TIMB_CHPBR_CHPDTY_Values<HRTIM_TIMB::CHPBR, 4, 3, ReadWriteMode, HRTIM_TIMBCHPBRBase> ;
    using CHPFRQ = HRTIM_TIMB_CHPBR_CHPFRQ_Values<HRTIM_TIMB::CHPBR, 0, 4, ReadWriteMode, HRTIM_TIMBCHPBRBase> ;
    using FieldValues = HRTIM_TIMB_CHPBR_CHPFRQ_Values<HRTIM_TIMB::CHPBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CHPBRPack  = Register<0x40017558, 32, ReadWriteMode, HRTIM_TIMBCHPBRBase, T...> ;

  struct HRTIM_TIMBCPT1BCRBase {} ;

  struct CPT1BCR : public RegisterBase<0x4001755C, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMB_CPT1BCR_TECMP2_Values<HRTIM_TIMB::CPT1BCR, 31, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TECMP1 = HRTIM_TIMB_CPT1BCR_TECMP1_Values<HRTIM_TIMB::CPT1BCR, 30, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TE1RST = HRTIM_TIMB_CPT1BCR_TE1RST_Values<HRTIM_TIMB::CPT1BCR, 29, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TE1SET = HRTIM_TIMB_CPT1BCR_TE1SET_Values<HRTIM_TIMB::CPT1BCR, 28, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TDCMP2 = HRTIM_TIMB_CPT1BCR_TDCMP2_Values<HRTIM_TIMB::CPT1BCR, 27, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TDCMP1 = HRTIM_TIMB_CPT1BCR_TDCMP1_Values<HRTIM_TIMB::CPT1BCR, 26, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TD1RST = HRTIM_TIMB_CPT1BCR_TD1RST_Values<HRTIM_TIMB::CPT1BCR, 25, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TD1SET = HRTIM_TIMB_CPT1BCR_TD1SET_Values<HRTIM_TIMB::CPT1BCR, 24, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TCCMP2 = HRTIM_TIMB_CPT1BCR_TCCMP2_Values<HRTIM_TIMB::CPT1BCR, 23, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TCCMP1 = HRTIM_TIMB_CPT1BCR_TCCMP1_Values<HRTIM_TIMB::CPT1BCR, 22, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TC1RST = HRTIM_TIMB_CPT1BCR_TC1RST_Values<HRTIM_TIMB::CPT1BCR, 21, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TC1SET = HRTIM_TIMB_CPT1BCR_TC1SET_Values<HRTIM_TIMB::CPT1BCR, 20, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TACMP2 = HRTIM_TIMB_CPT1BCR_TACMP2_Values<HRTIM_TIMB::CPT1BCR, 15, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TACMP1 = HRTIM_TIMB_CPT1BCR_TACMP1_Values<HRTIM_TIMB::CPT1BCR, 14, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TA1RST = HRTIM_TIMB_CPT1BCR_TA1RST_Values<HRTIM_TIMB::CPT1BCR, 13, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using TA1SET = HRTIM_TIMB_CPT1BCR_TA1SET_Values<HRTIM_TIMB::CPT1BCR, 12, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV10CPT = HRTIM_TIMB_CPT1BCR_EXEV10CPT_Values<HRTIM_TIMB::CPT1BCR, 11, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV9CPT = HRTIM_TIMB_CPT1BCR_EXEV9CPT_Values<HRTIM_TIMB::CPT1BCR, 10, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV8CPT = HRTIM_TIMB_CPT1BCR_EXEV8CPT_Values<HRTIM_TIMB::CPT1BCR, 9, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV7CPT = HRTIM_TIMB_CPT1BCR_EXEV7CPT_Values<HRTIM_TIMB::CPT1BCR, 8, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV6CPT = HRTIM_TIMB_CPT1BCR_EXEV6CPT_Values<HRTIM_TIMB::CPT1BCR, 7, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV5CPT = HRTIM_TIMB_CPT1BCR_EXEV5CPT_Values<HRTIM_TIMB::CPT1BCR, 6, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV4CPT = HRTIM_TIMB_CPT1BCR_EXEV4CPT_Values<HRTIM_TIMB::CPT1BCR, 5, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV3CPT = HRTIM_TIMB_CPT1BCR_EXEV3CPT_Values<HRTIM_TIMB::CPT1BCR, 4, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV2CPT = HRTIM_TIMB_CPT1BCR_EXEV2CPT_Values<HRTIM_TIMB::CPT1BCR, 3, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using EXEV1CPT = HRTIM_TIMB_CPT1BCR_EXEV1CPT_Values<HRTIM_TIMB::CPT1BCR, 2, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using UDPCPT = HRTIM_TIMB_CPT1BCR_UDPCPT_Values<HRTIM_TIMB::CPT1BCR, 1, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using SWCPT = HRTIM_TIMB_CPT1BCR_SWCPT_Values<HRTIM_TIMB::CPT1BCR, 0, 1, ReadWriteMode, HRTIM_TIMBCPT1BCRBase> ;
    using FieldValues = HRTIM_TIMB_CPT1BCR_SWCPT_Values<HRTIM_TIMB::CPT1BCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT1BCRPack  = Register<0x4001755C, 32, ReadWriteMode, HRTIM_TIMBCPT1BCRBase, T...> ;

  struct HRTIM_TIMBCPT2BCRBase {} ;

  struct CPT2BCR : public RegisterBase<0x40017560, 32, ReadWriteMode>
  {
    using TECMP2 = HRTIM_TIMB_CPT2BCR_TECMP2_Values<HRTIM_TIMB::CPT2BCR, 31, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TECMP1 = HRTIM_TIMB_CPT2BCR_TECMP1_Values<HRTIM_TIMB::CPT2BCR, 30, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TE1RST = HRTIM_TIMB_CPT2BCR_TE1RST_Values<HRTIM_TIMB::CPT2BCR, 29, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TE1SET = HRTIM_TIMB_CPT2BCR_TE1SET_Values<HRTIM_TIMB::CPT2BCR, 28, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TDCMP2 = HRTIM_TIMB_CPT2BCR_TDCMP2_Values<HRTIM_TIMB::CPT2BCR, 27, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TDCMP1 = HRTIM_TIMB_CPT2BCR_TDCMP1_Values<HRTIM_TIMB::CPT2BCR, 26, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TD1RST = HRTIM_TIMB_CPT2BCR_TD1RST_Values<HRTIM_TIMB::CPT2BCR, 25, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TD1SET = HRTIM_TIMB_CPT2BCR_TD1SET_Values<HRTIM_TIMB::CPT2BCR, 24, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TCCMP2 = HRTIM_TIMB_CPT2BCR_TCCMP2_Values<HRTIM_TIMB::CPT2BCR, 23, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TCCMP1 = HRTIM_TIMB_CPT2BCR_TCCMP1_Values<HRTIM_TIMB::CPT2BCR, 22, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TC1RST = HRTIM_TIMB_CPT2BCR_TC1RST_Values<HRTIM_TIMB::CPT2BCR, 21, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TC1SET = HRTIM_TIMB_CPT2BCR_TC1SET_Values<HRTIM_TIMB::CPT2BCR, 20, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TACMP2 = HRTIM_TIMB_CPT2BCR_TACMP2_Values<HRTIM_TIMB::CPT2BCR, 15, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TACMP1 = HRTIM_TIMB_CPT2BCR_TACMP1_Values<HRTIM_TIMB::CPT2BCR, 14, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TA1RST = HRTIM_TIMB_CPT2BCR_TA1RST_Values<HRTIM_TIMB::CPT2BCR, 13, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using TA1SET = HRTIM_TIMB_CPT2BCR_TA1SET_Values<HRTIM_TIMB::CPT2BCR, 12, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV10CPT = HRTIM_TIMB_CPT2BCR_EXEV10CPT_Values<HRTIM_TIMB::CPT2BCR, 11, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV9CPT = HRTIM_TIMB_CPT2BCR_EXEV9CPT_Values<HRTIM_TIMB::CPT2BCR, 10, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV8CPT = HRTIM_TIMB_CPT2BCR_EXEV8CPT_Values<HRTIM_TIMB::CPT2BCR, 9, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV7CPT = HRTIM_TIMB_CPT2BCR_EXEV7CPT_Values<HRTIM_TIMB::CPT2BCR, 8, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV6CPT = HRTIM_TIMB_CPT2BCR_EXEV6CPT_Values<HRTIM_TIMB::CPT2BCR, 7, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV5CPT = HRTIM_TIMB_CPT2BCR_EXEV5CPT_Values<HRTIM_TIMB::CPT2BCR, 6, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV4CPT = HRTIM_TIMB_CPT2BCR_EXEV4CPT_Values<HRTIM_TIMB::CPT2BCR, 5, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV3CPT = HRTIM_TIMB_CPT2BCR_EXEV3CPT_Values<HRTIM_TIMB::CPT2BCR, 4, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV2CPT = HRTIM_TIMB_CPT2BCR_EXEV2CPT_Values<HRTIM_TIMB::CPT2BCR, 3, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using EXEV1CPT = HRTIM_TIMB_CPT2BCR_EXEV1CPT_Values<HRTIM_TIMB::CPT2BCR, 2, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using UDPCPT = HRTIM_TIMB_CPT2BCR_UDPCPT_Values<HRTIM_TIMB::CPT2BCR, 1, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using SWCPT = HRTIM_TIMB_CPT2BCR_SWCPT_Values<HRTIM_TIMB::CPT2BCR, 0, 1, ReadWriteMode, HRTIM_TIMBCPT2BCRBase> ;
    using FieldValues = HRTIM_TIMB_CPT2BCR_SWCPT_Values<HRTIM_TIMB::CPT2BCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using CPT2BCRPack  = Register<0x40017560, 32, ReadWriteMode, HRTIM_TIMBCPT2BCRBase, T...> ;

  struct HRTIM_TIMBOUTBRBase {} ;

  struct OUTBR : public RegisterBase<0x40017564, 32, ReadWriteMode>
  {
    using DIDL2 = HRTIM_TIMB_OUTBR_DIDL2_Values<HRTIM_TIMB::OUTBR, 23, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using CHP2 = HRTIM_TIMB_OUTBR_CHP2_Values<HRTIM_TIMB::OUTBR, 22, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using FAULT2 = HRTIM_TIMB_OUTBR_FAULT2_Values<HRTIM_TIMB::OUTBR, 20, 2, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using IDLES2 = HRTIM_TIMB_OUTBR_IDLES2_Values<HRTIM_TIMB::OUTBR, 19, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using IDLEM2 = HRTIM_TIMB_OUTBR_IDLEM2_Values<HRTIM_TIMB::OUTBR, 18, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using POL2 = HRTIM_TIMB_OUTBR_POL2_Values<HRTIM_TIMB::OUTBR, 17, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using DLYPRT = HRTIM_TIMB_OUTBR_DLYPRT_Values<HRTIM_TIMB::OUTBR, 10, 3, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using DLYPRTEN = HRTIM_TIMB_OUTBR_DLYPRTEN_Values<HRTIM_TIMB::OUTBR, 9, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using DTEN = HRTIM_TIMB_OUTBR_DTEN_Values<HRTIM_TIMB::OUTBR, 8, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using DIDL1 = HRTIM_TIMB_OUTBR_DIDL1_Values<HRTIM_TIMB::OUTBR, 7, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using CHP1 = HRTIM_TIMB_OUTBR_CHP1_Values<HRTIM_TIMB::OUTBR, 6, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using FAULT1 = HRTIM_TIMB_OUTBR_FAULT1_Values<HRTIM_TIMB::OUTBR, 4, 2, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using IDLES1 = HRTIM_TIMB_OUTBR_IDLES1_Values<HRTIM_TIMB::OUTBR, 3, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using IDLEM1 = HRTIM_TIMB_OUTBR_IDLEM1_Values<HRTIM_TIMB::OUTBR, 2, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using POL1 = HRTIM_TIMB_OUTBR_POL1_Values<HRTIM_TIMB::OUTBR, 1, 1, ReadWriteMode, HRTIM_TIMBOUTBRBase> ;
    using FieldValues = HRTIM_TIMB_OUTBR_POL1_Values<HRTIM_TIMB::OUTBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OUTBRPack  = Register<0x40017564, 32, ReadWriteMode, HRTIM_TIMBOUTBRBase, T...> ;

  struct HRTIM_TIMBFLTBRBase {} ;

  struct FLTBR : public RegisterBase<0x40017568, 32, ReadWriteMode>
  {
    using FLTLCK = HRTIM_TIMB_FLTBR_FLTLCK_Values<HRTIM_TIMB::FLTBR, 31, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FLT5EN = HRTIM_TIMB_FLTBR_FLT5EN_Values<HRTIM_TIMB::FLTBR, 4, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FLT4EN = HRTIM_TIMB_FLTBR_FLT4EN_Values<HRTIM_TIMB::FLTBR, 3, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FLT3EN = HRTIM_TIMB_FLTBR_FLT3EN_Values<HRTIM_TIMB::FLTBR, 2, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FLT2EN = HRTIM_TIMB_FLTBR_FLT2EN_Values<HRTIM_TIMB::FLTBR, 1, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FLT1EN = HRTIM_TIMB_FLTBR_FLT1EN_Values<HRTIM_TIMB::FLTBR, 0, 1, ReadWriteMode, HRTIM_TIMBFLTBRBase> ;
    using FieldValues = HRTIM_TIMB_FLTBR_FLT1EN_Values<HRTIM_TIMB::FLTBR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using FLTBRPack  = Register<0x40017568, 32, ReadWriteMode, HRTIM_TIMBFLTBRBase, T...> ;

} ;

#endif //#if !defined(HRTIMTIMBREGISTERS_HPP)
