/*******************************************************************************
* Filename      : otg2hsglobalregisters.hpp
*
* Details       : USB 1 on the go high speed. This header file is auto-generated
*                 for STM32H745_CM7 device.
*
*
*******************************************************************************/

#if !defined(OTG2HSGLOBALREGISTERS_HPP)
#define OTG2HSGLOBALREGISTERS_HPP

#include "otg2hsglobalfieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct OTG2_HS_GLOBAL
{
  struct OTG2_HS_GLOBALOTG_HS_GOTGCTLBase {} ;

  struct OTG_HS_GOTGCTL : public RegisterBase<0x40080000, 32, ReadWriteMode>
  {
    using SRQSCS = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_SRQSCS_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 0, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using SRQ = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_SRQ_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HNGSCS = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_HNGSCS_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 8, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HNPRQ = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_HNPRQ_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 9, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using HSHNPEN = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_HSHNPEN_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 10, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using DHNPEN = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_DHNPEN_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 11, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using CIDSTS = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_CIDSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 16, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using DBCT = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_DBCT_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 17, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using ASVLD = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_ASVLD_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 18, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using BSVLD = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_BSVLD_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 19, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using EHEN = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_EHEN_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 12, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GOTGCTL_EHEN_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GOTGCTLPack  = Register<0x40080000, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGCTLBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GOTGINTBase {} ;

  struct OTG_HS_GOTGINT : public RegisterBase<0x40080004, 32, ReadWriteMode>
  {
    using SEDET = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_SEDET_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 2, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using SRSSCHG = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_SRSSCHG_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 8, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using HNSSCHG = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_HNSSCHG_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 9, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using HNGDET = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_HNGDET_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 17, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using ADTOCHG = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_ADTOCHG_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 18, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using DBCDNE = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_DBCDNE_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 19, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using IDCHNG = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_IDCHNG_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 20, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GOTGINT_IDCHNG_Values<OTG2_HS_GLOBAL::OTG_HS_GOTGINT, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GOTGINTPack  = Register<0x40080004, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GOTGINTBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GAHBCFGBase {} ;

  struct OTG_HS_GAHBCFG : public RegisterBase<0x40080008, 32, ReadWriteMode>
  {
    using GINT = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_GINT_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 0, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using HBSTLEN = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_HBSTLEN_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 1, 4, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using DMAEN = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_DMAEN_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 5, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using TXFELVL = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_TXFELVL_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 7, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using PTXFELVL = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_PTXFELVL_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 8, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GAHBCFG_PTXFELVL_Values<OTG2_HS_GLOBAL::OTG_HS_GAHBCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GAHBCFGPack  = Register<0x40080008, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GAHBCFGBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GUSBCFGBase {} ;

  struct OTG_HS_GUSBCFG : public RegisterBase<0x4008000C, 32, ReadWriteMode>
  {
    using TOCAL = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_TOCAL_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 0, 3, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PHYSEL = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_PHYSEL_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 6, 1, WriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using SRPCAP = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_SRPCAP_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 8, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using HNPCAP = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_HNPCAP_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 9, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using TRDT = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_TRDT_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 10, 4, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PHYLPCS = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_PHYLPCS_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 15, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIFSLS = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIFSLS_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 17, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIAR = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIAR_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 18, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPICSM = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPICSM_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 19, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIEVBUSD = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSD_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 20, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIEVBUSI = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIEVBUSI_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 21, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using TSDPS = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_TSDPS_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 22, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PCCI = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_PCCI_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 23, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using PTCI = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_PTCI_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 24, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using ULPIIPD = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_ULPIIPD_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 25, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FHMOD = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_FHMOD_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 29, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FDMOD = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_FDMOD_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 30, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GUSBCFG_FDMOD_Values<OTG2_HS_GLOBAL::OTG_HS_GUSBCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GUSBCFGPack  = Register<0x4008000C, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GUSBCFGBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRSTCTLBase {} ;

  struct OTG_HS_GRSTCTL : public RegisterBase<0x40080010, 32, ReadWriteMode>
  {
    using CSRST = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_CSRST_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 0, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using HSRST = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_HSRST_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using FCRST = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_FCRST_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 2, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using RXFFLSH = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_RXFFLSH_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 4, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using TXFFLSH = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_TXFFLSH_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 5, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using TXFNUM = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_TXFNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 6, 5, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using AHBIDL = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_AHBIDL_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 31, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using DMAREQ = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_DMAREQ_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 30, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRSTCTL_DMAREQ_Values<OTG2_HS_GLOBAL::OTG_HS_GRSTCTL, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRSTCTLPack  = Register<0x40080010, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRSTCTLBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GINTSTSBase {} ;

  struct OTG_HS_GINTSTS : public RegisterBase<0x40080014, 32, ReadWriteMode>
  {
    using CMOD = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_CMOD_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 0, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using MMIS = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_MMIS_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using OTGINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_OTGINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 2, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using SOF = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_SOF_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 3, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using RXFLVL = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_RXFLVL_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 4, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using NPTXFE = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_NPTXFE_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 5, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using GINAKEFF = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_GINAKEFF_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 6, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using BOUTNAKEFF = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_BOUTNAKEFF_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 7, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ESUSP = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_ESUSP_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 10, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using USBSUSP = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_USBSUSP_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 11, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using USBRST = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_USBRST_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 12, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ENUMDNE = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_ENUMDNE_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 13, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using ISOODRP = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_ISOODRP_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 14, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using EOPF = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_EOPF_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 15, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using IEPINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_IEPINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 18, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using OEPINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_OEPINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 19, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using IISOIXFR = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_IISOIXFR_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 20, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using PXFR_INCOMPISOOUT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_PXFR_INCOMPISOOUT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 21, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using DATAFSUSP = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_DATAFSUSP_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 22, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using HPRTINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_HPRTINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 24, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using HCINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_HCINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 25, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using PTXFE = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_PTXFE_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 26, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using CIDSCHG = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_CIDSCHG_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 28, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using DISCINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_DISCINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 29, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using SRQINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_SRQINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 30, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using WKUINT = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_WKUINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 31, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GINTSTS_WKUINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTSTS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GINTSTSPack  = Register<0x40080014, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTSTSBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GINTMSKBase {} ;

  struct OTG_HS_GINTMSK : public RegisterBase<0x40080018, 32, ReadWriteMode>
  {
    using MMISM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_MMISM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using OTGINT = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_OTGINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 2, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using SOFM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_SOFM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 3, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using RXFLVLM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_RXFLVLM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 4, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using NPTXFEM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_NPTXFEM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 5, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using GINAKEFFM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_GINAKEFFM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 6, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using GONAKEFFM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_GONAKEFFM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 7, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ESUSPM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_ESUSPM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 10, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using USBSUSPM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_USBSUSPM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 11, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using USBRST = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_USBRST_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 12, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ENUMDNEM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_ENUMDNEM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 13, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using ISOODRPM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_ISOODRPM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 14, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using EOPFM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_EOPFM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 15, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using IEPINT = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_IEPINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 18, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using OEPINT = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_OEPINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 19, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using IISOIXFRM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_IISOIXFRM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 20, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PXFRM_IISOOXFRM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_PXFRM_IISOOXFRM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 21, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using FSUSPM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_FSUSPM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 22, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PRTIM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_PRTIM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 24, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using HCIM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_HCIM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 25, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using PTXFEM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_PTXFEM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 26, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using CIDSCHGM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_CIDSCHGM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 28, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using DISCINT = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_DISCINT_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 29, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using SRQIM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_SRQIM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 30, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using WUIM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_WUIM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 31, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using RSTDE = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_RSTDE_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 23, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using LPMINTM = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_LPMINTM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 27, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GINTMSK_LPMINTM_Values<OTG2_HS_GLOBAL::OTG_HS_GINTMSK, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GINTMSKPack  = Register<0x40080018, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GINTMSKBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase {} ;

  struct OTG_HS_GRXSTSR_Host : public RegisterBase<0x4008001C, 32, ReadMode>
  {
    using CHNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Host_CHNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 0, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using BCNT = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Host_BCNT_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 4, 11, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using DPID = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Host_DPID_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 15, 2, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using PKTSTS = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Host_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 17, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Host_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSR_HostPack  = Register<0x4008001C, 32, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_HostBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase {} ;

  struct OTG_HS_GRXSTSP_Host : public RegisterBase<0x40080020, 32, ReadMode>
  {
    using CHNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Host_CHNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 0, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using BCNT = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Host_BCNT_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 4, 11, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using DPID = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Host_DPID_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 15, 2, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using PKTSTS = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Host_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 17, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Host_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSP_HostPack  = Register<0x40080020, 32, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_HostBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRXFSIZBase {} ;

  struct OTG_HS_GRXFSIZ : public RegisterBase<0x40080024, 32, ReadWriteMode>
  {
    using RXFD = OTG2_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD_Values<OTG2_HS_GLOBAL::OTG_HS_GRXFSIZ, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRXFSIZBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRXFSIZ_RXFD_Values<OTG2_HS_GLOBAL::OTG_HS_GRXFSIZ, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXFSIZPack  = Register<0x40080024, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GRXFSIZBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_HNPTXFSIZ_HostBase {} ;

  struct OTG_HS_HNPTXFSIZ_Host : public RegisterBase<0x40080028, 32, ReadWriteMode>
  {
    using NPTXFSA = OTG2_HS_GLOBAL_OTG_HS_HNPTXFSIZ_Host_NPTXFSA_Values<OTG2_HS_GLOBAL::OTG_HS_HNPTXFSIZ_Host, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HNPTXFSIZ_HostBase> ;
    using NPTXFD = OTG2_HS_GLOBAL_OTG_HS_HNPTXFSIZ_Host_NPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_HNPTXFSIZ_Host, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HNPTXFSIZ_HostBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_HNPTXFSIZ_Host_NPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_HNPTXFSIZ_Host, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_HNPTXFSIZ_HostPack  = Register<0x40080028, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HNPTXFSIZ_HostBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF0_DeviceBase {} ;

  struct OTG_HS_DIEPTXF0_Device : public RegisterBase<0x40080028, 32, ReadWriteMode>
  {
    using TX0FSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF0_Device_TX0FSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF0_Device, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF0_DeviceBase> ;
    using TX0FD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF0_Device_TX0FD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF0_Device, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF0_DeviceBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF0_Device_TX0FD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF0_Device, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF0_DevicePack  = Register<0x40080028, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF0_DeviceBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GNPTXSTSBase {} ;

  struct OTG_HS_GNPTXSTS : public RegisterBase<0x4008002C, 32, ReadMode>
  {
    using NPTXFSAV = OTG2_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXFSAV_Values<OTG2_HS_GLOBAL::OTG_HS_GNPTXSTS, 0, 16, ReadMode, OTG2_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using NPTQXSAV = OTG2_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTQXSAV_Values<OTG2_HS_GLOBAL::OTG_HS_GNPTXSTS, 16, 8, ReadMode, OTG2_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using NPTXQTOP = OTG2_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP_Values<OTG2_HS_GLOBAL::OTG_HS_GNPTXSTS, 24, 7, ReadMode, OTG2_HS_GLOBALOTG_HS_GNPTXSTSBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GNPTXSTS_NPTXQTOP_Values<OTG2_HS_GLOBAL::OTG_HS_GNPTXSTS, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GNPTXSTSPack  = Register<0x4008002C, 32, ReadMode, OTG2_HS_GLOBALOTG_HS_GNPTXSTSBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GCCFGBase {} ;

  struct OTG_HS_GCCFG : public RegisterBase<0x40080038, 32, ReadWriteMode>
  {
    using PWRDWN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_PWRDWN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 16, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using BCDEN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_BCDEN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 17, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using DCDEN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_DCDEN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 18, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using PDEN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_PDEN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 19, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using SDEN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_SDEN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 20, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using VBDEN = OTG2_HS_GLOBAL_OTG_HS_GCCFG_VBDEN_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 21, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using DCDET = OTG2_HS_GLOBAL_OTG_HS_GCCFG_DCDET_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 0, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using PDET = OTG2_HS_GLOBAL_OTG_HS_GCCFG_PDET_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using SDET = OTG2_HS_GLOBAL_OTG_HS_GCCFG_SDET_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 2, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using PS2DET = OTG2_HS_GLOBAL_OTG_HS_GCCFG_PS2DET_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 3, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GCCFG_PS2DET_Values<OTG2_HS_GLOBAL::OTG_HS_GCCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GCCFGPack  = Register<0x40080038, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GCCFGBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_CIDBase {} ;

  struct OTG_HS_CID : public RegisterBase<0x4008003C, 32, ReadWriteMode>
  {
    using PRODUCT_ID = OTG2_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID_Values<OTG2_HS_GLOBAL::OTG_HS_CID, 0, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_CIDBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_CID_PRODUCT_ID_Values<OTG2_HS_GLOBAL::OTG_HS_CID, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_CIDPack  = Register<0x4008003C, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_CIDBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_HPTXFSIZBase {} ;

  struct OTG_HS_HPTXFSIZ : public RegisterBase<0x40080100, 32, ReadWriteMode>
  {
    using PTXSA = OTG2_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_HPTXFSIZ, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HPTXFSIZBase> ;
    using PTXFD = OTG2_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_HPTXFSIZ, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HPTXFSIZBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_HPTXFSIZ_PTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_HPTXFSIZ, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_HPTXFSIZPack  = Register<0x40080100, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_HPTXFSIZBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF1Base {} ;

  struct OTG_HS_DIEPTXF1 : public RegisterBase<0x40080104, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF1, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF1Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF1, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF1Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF1_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF1Pack  = Register<0x40080104, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF1Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF2Base {} ;

  struct OTG_HS_DIEPTXF2 : public RegisterBase<0x40080108, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF2, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF2Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF2, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF2Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF2_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF2Pack  = Register<0x40080108, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF2Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF3Base {} ;

  struct OTG_HS_DIEPTXF3 : public RegisterBase<0x4008011C, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF3, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF3Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF3, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF3Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF3_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF3Pack  = Register<0x4008011C, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF3Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF4Base {} ;

  struct OTG_HS_DIEPTXF4 : public RegisterBase<0x40080120, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF4, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF4Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF4, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF4Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF4_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF4Pack  = Register<0x40080120, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF4Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF5Base {} ;

  struct OTG_HS_DIEPTXF5 : public RegisterBase<0x40080124, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF5, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF5Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF5, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF5Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF5_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF5, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF5Pack  = Register<0x40080124, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF5Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF6Base {} ;

  struct OTG_HS_DIEPTXF6 : public RegisterBase<0x40080128, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF6, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF6Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF6, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF6Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF6_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF6, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF6Pack  = Register<0x40080128, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF6Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_DIEPTXF7Base {} ;

  struct OTG_HS_DIEPTXF7 : public RegisterBase<0x4008012C, 32, ReadWriteMode>
  {
    using INEPTXSA = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXSA_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF7, 0, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF7Base> ;
    using INEPTXFD = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF7, 16, 16, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF7Base> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_DIEPTXF7_INEPTXFD_Values<OTG2_HS_GLOBAL::OTG_HS_DIEPTXF7, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_DIEPTXF7Pack  = Register<0x4008012C, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_DIEPTXF7Base, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase {} ;

  struct OTG_HS_GRXSTSR_Device : public RegisterBase<0x4008001C, 32, ReadMode>
  {
    using EPNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_EPNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 0, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase> ;
    using BCNT = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_BCNT_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 4, 11, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase> ;
    using DPID = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_DPID_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 15, 2, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase> ;
    using PKTSTS = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 17, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase> ;
    using FRMNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_FRMNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 21, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRXSTSR_Device_FRMNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSR_Device, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSR_DevicePack  = Register<0x4008001C, 32, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSR_DeviceBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase {} ;

  struct OTG_HS_GRXSTSP_Device : public RegisterBase<0x40080020, 32, ReadMode>
  {
    using EPNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_EPNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 0, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase> ;
    using BCNT = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_BCNT_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 4, 11, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase> ;
    using DPID = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_DPID_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 15, 2, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase> ;
    using PKTSTS = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_PKTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 17, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase> ;
    using FRMNUM = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_FRMNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 21, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GRXSTSP_Device_FRMNUM_Values<OTG2_HS_GLOBAL::OTG_HS_GRXSTSP_Device, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GRXSTSP_DevicePack  = Register<0x40080020, 32, ReadMode, OTG2_HS_GLOBALOTG_HS_GRXSTSP_DeviceBase, T...> ;

  struct OTG2_HS_GLOBALOTG_HS_GLPMCFGBase {} ;

  struct OTG_HS_GLPMCFG : public RegisterBase<0x40080054, 32, ReadWriteMode>
  {
    using LPMEN = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMEN_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 0, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using LPMACK = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMACK_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 1, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using BESL = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_BESL_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 2, 4, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using REMWAKE = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_REMWAKE_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 6, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using L1SSEN = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_L1SSEN_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 7, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using BESLTHRS = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_BESLTHRS_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 8, 4, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using L1DSEN = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_L1DSEN_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 12, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using LPMRST = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRST_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 13, 2, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using SLPSTS = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_SLPSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 15, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using L1RSMOK = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_L1RSMOK_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 16, 1, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using LPMCHIDX = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMCHIDX_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 17, 4, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using LPMRCNT = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNT_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 21, 3, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using SNDLPM = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_SNDLPM_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 24, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using LPMRCNTSTS = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_LPMRCNTSTS_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 25, 3, ReadMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using ENBESL = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_ENBESL_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 28, 1, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase> ;
    using FieldValues = OTG2_HS_GLOBAL_OTG_HS_GLPMCFG_ENBESL_Values<OTG2_HS_GLOBAL::OTG_HS_GLPMCFG, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using OTG_HS_GLPMCFGPack  = Register<0x40080054, 32, ReadWriteMode, OTG2_HS_GLOBALOTG_HS_GLPMCFGBase, T...> ;

} ;

#endif //#if !defined(OTG2HSGLOBALREGISTERS_HPP)
